const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let state,selected=0,revision=null,lastKey='',timer;
const labels={price_minor:'가격',metric:'납품할 지표',periods:'기간',source_required:'출처',deadline_seconds:'납기',deadline_anchor:'기산 시점',refund_policy:'환불 조건'};
const display=(field,v)=>v===undefined?'아직 제안되지 않음':field==='price_minor'?(v/100).toFixed(2)+' DEMO':field==='metric'?(v==='ACTUAL_QUARTERLY_FACILITY_INVESTMENT'?'분기별 실제 시설투자 현금유출':'연간 CAPEX 전망치'):field==='periods'?v.join(' · '):field==='source_required'?(v?'공식 원문 + 셀 근거 필수':'출처 필수 아님'):field==='deadline_seconds'?v/60+'분':field==='deadline_anchor'?'예치가 체인에 기록된 때부터':'검수 실패 또는 만료 → 구매자 환불';
function sourceButton(id,text){const b=el('button',text,'source-button');b.addEventListener('click',()=>{$$('.message').forEach(n=>n.classList.remove('selected'));const n=document.getElementById(id);n?.classList.add('selected');n?.scrollIntoView({behavior:'smooth',block:'center'});});return b;}const $$=s=>[...document.querySelectorAll(s)];
function draw(){const r=state?.report;$('#run').disabled=!!state?.job?.running;$('#stop').disabled=!state?.job?.running;$('#execution option[value=live]').disabled=!state?.live_available;if(!r){$('#status').textContent='아직 실행 기록이 없습니다. 위 조건을 승인하고 작성된 대화 데모를 실행하세요.';return;}
 $('#mode').textContent=r.mode==='LIVE_KILN_LOCAL_EVM'?'실제 Kiln 대화 · 로컬 체인':'작성된 대화 · 로컬 체인';$('#status').classList.toggle('error',['FAIL','STOPPED'].includes(r.status));$('#status').textContent=state.job?.running?`새 실행 중 · ${r.stage} · 모델 ${r.usage.length}회. 새 메시지마다 조건과 근거를 추출합니다.`:`저장된 실행 ${r.run.slice(0,8)} · ${r.status} · ${r.summary?.passed??0}/${r.summary?.checks??0} 검증 · ${r.summary?.model_calls??0}회 / ${(r.summary?.total_tokens??0).toLocaleString()} 토큰${r.error?' · '+r.error:''}`;
 const names=['Seller A · 가격 협상','Seller B · 의미 충돌','같은 Seller A · 재거래','권한 초과 · 대조','정상 지급 · 대조'];$('#sessions').replaceChildren();(r.sessions??[]).forEach((s,i)=>{const b=el('button',names[i]??`협상 ${i+1}`);b.setAttribute('aria-pressed',String(selected===i));b.addEventListener('click',()=>{selected=i;revision=null;draw();});$('#sessions').append(b);});
 const s=r.sessions?.[selected]??r.sessions?.[0];if(!s)return;const latest=s.revisions.at(-1),rev=s.revisions.find(v=>v.revision===revision)??latest;$('#turn-count').textContent=s.events.length+'개 외부 메시지';$('#revision').textContent=rev?`v${rev.revision} / ${latest.revision}`:'의미 추출 대기';$('#messages').replaceChildren();for(const m of s.events){const n=el('div',undefined,'message '+(m.sender_agent===s.buyer?'buyer':'seller'));n.id=m.event_id;const meta=el('div',undefined,'message-meta');meta.append(el('span',m.sender_agent===s.buyer?'BUYER AGENT':m.sender_agent.toUpperCase()),el('span',`TURN ${m.sequence}`));n.append(meta,el('p',m.content),el('code','서명된 메시지 '+m.message_hash.slice(0,18)+'…'));$('#messages').append(n);}
 $('#terms').replaceChildren();for(const [field,label] of Object.entries(labels)){const t=el('div',undefined,'term'),content=el('div');t.append(el('span',label,'term-label'));content.append(el('strong',display(field,rev?.terms[field])));const p=rev?.provenance[field];if(p){const m=s.events.find(e=>e.event_id===p.event_id);content.append(sourceButton(p.event_id,`TURN #${m?.sequence} · ${p.proposed_by} ↗`));}t.append(content);$('#terms').append(t);}
 $('#conflicts').replaceChildren();for(const c of rev?.conflicts??[]){const d=el('div',undefined,'conflict');d.append(el('b','미해결 충돌 · 거래 확정 불가'),el('p',`제안: ${display(c.field,c.actual)}`),el('p',`요청: ${display(c.field,c.expected)}`));$('#conflicts').append(d);}
 $('#price-history').replaceChildren();for(const v of s.revisions)for(const d of v.diff.filter(d=>d.field==='price_minor')){const b=el('button',display('price_minor',d.after),'price-step');b.append(el('small',`TURN #${v.event_count} · v${v.revision}`));b.setAttribute('aria-pressed',String(rev?.revision===v.revision));b.addEventListener('click',()=>{revision=v.revision;draw();});$('#price-history').append(b);}if(revision){const b=el('button','최종 조건 보기');b.onclick=()=>{revision=null;draw();};$('#price-history').append(b);}
 $('#confirmations').replaceChildren();const h=el('div',undefined,'hashes');h.append(el('h3','동일한 최종 조건을 확인했나요?'));for(const role of [s.buyer,s.seller]){const ack=s.confirmations.find(a=>a.agent_id===role&&a.revision_hash===latest?.revision_hash);const row=el('div',undefined,'signed');row.append(el('span',role),el('b',ack?'동일 해시 서명 ✓':'서명 없음'));h.append(row);}h.append(el('p','대화상 “Agreed”만으로는 확정하지 않습니다.','small'));if(s.commit){h.append(el('small','합의 버전 해시'),el('code',s.commit.revision_hash),el('p','에스크로에 연결된 Deal 해시','small'),el('code',s.commit.deal_hash));}$('#confirmations').append(h);
 const outcome=r.outcomes.find(o=>o.deal_id===s.deal_id),checks=outcome?.policy??[];$('#final-state').textContent=outcome?.state??(s.commit?'COMMITTED':'NOT COMMITTED');$('#policy').replaceChildren();const groups=[['양측 합의',checks.filter(c=>c.name==='BILATERAL_AGREEMENT'),!!s.commit],['사람의 위임',checks.filter(c=>!['BILATERAL_AGREEMENT','PREVIEW_REQUIRED'].includes(c.name)),null],['이전 거래가 만든 조건',checks.filter(c=>c.name==='PREVIEW_REQUIRED'),null]];for(const [title,list,fallback] of groups){const passed=list.length?list.every(c=>c.pass):fallback;const g=el('div',undefined,'gate '+(passed===false?'block':passed===null?'pending':''));g.append(el('h3',title),el('strong',passed===null?'검사 전':passed?'PASS':'BLOCK'));const ul=el('ul');for(const c of list)ul.append(el('li',(c.pass?'✓ ':'✕ ')+c.name));if(!list.length)ul.append(el('li',fallback?'두 에이전트 서명 확인':'미해결 조건이나 확인 누락'));g.append(ul);$('#policy').append(g);}
 $('#memory').replaceChildren();const text=el('div');text.append(el('span','OUTCOME → PERMISSION','eyebrow'),el('h2','“이번에는 잘하겠습니다.”\n그래도 샘플부터.'),el('p','같은 회사·같은 공급자의 실패만 다음 주문의 권한을 좁힙니다. 에이전트의 새 합의가 이 조건을 지울 수 없습니다.'));const flow=el('div',undefined,'memory-flow');for(const line of ['이전 거래: 3,014 대신 3,441 → 검수 실패 · 환불','새 조건: REQUIRE_PREVIEW · 해당 회사 × Seller A','다음 거래: 양측 서명 ✓ · 예산 ✓ · 샘플 ✕ → 예치 차단'])flow.append(el('span',line));if(!r.outcomes.some(o=>o.control))flow.append(el('b','아직 이 실행에서 실패·기억 생성 전입니다.'));$('#memory').append(text,flow);
 $('#outcomes').replaceChildren();for(const o of r.outcomes){const card=el('article',undefined,'outcome');card.append(el('h3',o.label),el('p',o.state+' · 영수증 '+o.verification.verdict));const tx=o.transactions.release??o.transactions.refund;card.append(el('code',tx?.tx_hash??'새 지급/환불 거래 없음'));const a=el('a','승인·합의·정산 영수증 받기');a.href='/api/evidence/'+o.receipt_file;card.append(el('p'),a);$('#outcomes').append(card);}
 $('#trace').replaceChildren();const audit=el('details');audit.append(el('summary','선택한 협상의 메시지 → 버전 → 서명 → 확정 이력'));for(const e of s.audit){const row=el('div',e.type,'trace-row');row.append(el('code',JSON.stringify(e.payload)));audit.append(row);}$('#trace').append(audit);
 const table=el('table'),tr=el('tr');for(const title of ['흐름','호출','토큰'])tr.append(el('th',title));table.append(tr);const usage={};for(const u of r.usage){const k=u.flow_name;usage[k]??={calls:0,tokens:0};usage[k].calls++;usage[k].tokens+=u.total_tokens??0;}for(const [flow,v] of Object.entries(usage)){const row=el('tr');row.append(el('td',flow),el('td',v.calls),el('td',v.tokens.toLocaleString()));table.append(row);}if(!r.usage.length){const row=el('tr');row.append(el('td','작성된 대화와 추출 후보'),el('td','0'),el('td','0'));table.append(row);}$('#usage').replaceChildren(table,el('p','전력은 측정하지 않았습니다. 서명·예산·재거래 검사는 코드로 처리합니다.','small'));
}
async function load(force=false){const res=await fetch('/api/state');state=await res.json();const key=JSON.stringify([state.report?.run,state.report?.stage,state.report?.status,state.report?.sessions?.map(s=>[s.events.length,s.revisions.length,s.confirmations.length]),state.job]);if(force||key!==lastKey){lastKey=key;draw();}}
async function post(path,body){const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-dealtrace-token':state.token},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
$('#run').onclick=async()=>{try{if(!$('#approve').checked)throw new Error('먼저 위 조건을 승인해 주세요.');await post('/api/runs',{live:$('#execution').value==='live',approved:true});selected=0;revision=null;await load(true);}catch(e){$('#status').textContent=e.message;$('#status').classList.add('error');}};
$('#stop').onclick=async()=>{try{await post('/api/stop',{});$('#status').textContent='위임 중지를 요청했습니다. 진행 중 추론은 끝날 수 있으며 이미 서명한 거래는 상태를 확인합니다.';}catch(e){$('#status').textContent=e.message;}};
load(true).catch(e=>{console.error('DealTrace UI:',e.message);$('#status').textContent='화면을 불러오지 못했습니다: '+e.message;});timer=setInterval(()=>load().catch(()=>{}),1800);window.addEventListener('pagehide',()=>clearInterval(timer));
