const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let state,stage='blocked',last='',timer,copyRun=null;const amount=v=>Number.isFinite(v)?(v/100).toFixed(2)+' DEMO':'—';
const labels={price_minor:'총액',metric:'작업',periods:'기간',source_required:'출처',deadline_seconds:'납기',deadline_anchor:'기산점',refund_policy:'실패 시'};
const value=(k,v)=>v===undefined?'확인 전':k==='price_minor'?amount(v):k==='metric'?(v==='ACTUAL_QUARTERLY_FACILITY_INVESTMENT'?'분기별 실제 시설투자 현금유출':'연간 CAPEX 전망치'):k==='periods'?v.join(' · '):k==='source_required'?(v?'공식 원본 페이지·표 위치 필수':'필수 아님'):k==='deadline_seconds'?v/60+'분':k==='deadline_anchor'?'예치 transaction의 block 시각':'검수 실패 또는 만료 → 전액 환불';
function detail(title,data){const d=el('details');d.append(el('summary',title),el('pre',JSON.stringify(data,null,2)));return d;}
function link(label,url){const a=el('a',label,'download');a.href=url;if(url.startsWith('https:')){a.target='_blank';a.rel='noopener';}return a;}
function evidenceButton(s,field){const p=s.revisions.at(-1)?.provenance[field],m=s.events.find(e=>e.event_id===p?.event_id);if(!m)return el('span');const b=el('button',`TURN ${m.sequence} · 원문 확인 ↗`,'source');b.onclick=()=>{$$('.message').forEach(n=>n.classList.remove('selected'));const n=document.getElementById(m.event_id);n.classList.add('selected');n.scrollIntoView({behavior:'smooth',block:'center'});};return b;}
function selected(r,key){return r.sessions.find(s=>s.session_id===r.session_roles[key]);}
function outcome(r,s){return r.outcomes.find(o=>o.deal_id===s?.deal_id)??r.financial_states?.find(o=>o.deal_id===s?.deal_id);}
function draw(){const r=state?.report;$('#run').disabled=!!state?.job?.running;$('#stop').disabled=!state?.job?.running;$('#execution option[value=live]').disabled=!state?.live_available;if(!r){$('#status').textContent='승인 범위를 확인하고 새 실행을 시작하세요.';return;}if(r.version!==3){$('#status').textContent='이전 버전 기록입니다. 아래에서 새 DealTrace 실행을 시작하세요.';return;}
 $('#mode').textContent=(r.mode.startsWith('LIVE_KILN')?'실제 Kiln Qwen':'작성된 대화')+' · '+(r.network?.chainId===11155111?'Sepolia':'로컬 EVM');$('#status').classList.toggle('error',['FAIL','STOPPED'].includes(r.status));$('#status').textContent=`${state.job?.running?(r.status==='RUNNING'?'새 실행 중':'새 실행 준비 중 · 아래는 이전 저장 기록'):'저장된 실행 재생'} · ${r.run.slice(0,8)} · ${r.status} / ${r.stage} · 검증 ${r.summary?.passed??r.checks.filter(c=>c.pass).length}/${r.summary?.checks??r.checks.length} · 모델 ${r.usage.length}회${r.error?' · '+r.error:''}`;
 const s=selected(r,'normal');if(!s)return;const rev=s.revisions.at(-1),o=outcome(r,s),history=o?.claims??[],rejected=history.find(h=>h.decision.verdict==='REJECTED'),accepted=history.find(h=>h.decision.verdict==='ACCEPTED');const paid=stage==='paid'&&o?.state==='SETTLED',blocked=stage==='blocked'&&!!rejected,funded=o?.transactions?.fund?.status==='CONFIRMED';
 $('#verify-copy').disabled=!!state.job?.running||!o?.receipt_file;if(copyRun!==r.run){$('#copy-verification').replaceChildren();copyRun=r.run;}
 $$('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stage===stage)));
 $('#budget').textContent=amount(s.mandate_snapshot.task_budget_minor);$('#agreed').textContent=s.commit?amount(rev?.terms.price_minor):'미확정';$('#claimed').textContent=stage==='commit'?'아직 없음':amount((stage==='paid'?accepted:rejected)?.claim.amount_minor);$('#claim-label').textContent=stage==='paid'?'판매자 정정 청구':'판매자 청구';$('#claim-note').textContent=stage==='blocked'&&rejected?'예산 안이지만 합의 금액과 다름':'서명된 청구서와 납품 연결';
 $('#decision').textContent=paid?'26 지급 완료':blocked?'지급 차단':stage==='commit'&&s.commit?'양측 확정':'확인 중';$('#decision-note').textContent=paid?'납품 검수 + 청구 일치 → 한 번 지급':blocked?'추가 예치 0 · 판매자 지급 0':'저장 기록을 재생합니다. 새 거래 없음';$('.verdict').classList.toggle('pass',paid||(stage==='commit'&&!!s.commit));
 $('#turn-count').textContent=s.events.length+' messages';$('#messages').replaceChildren();for(const m of s.events){const n=el('div',undefined,'message '+(m.sender_agent===s.buyer?'buyer':'seller'));n.id=m.event_id;n.append(el('small',`${m.sender_agent.toUpperCase()} · TURN ${m.sequence}`),el('p',m.content));$('#messages').append(n);}
 $('#revision').textContent=rev?`v${rev.revision}`:'초안';$('#terms').replaceChildren();for(const [k,label] of Object.entries(labels)){const n=el('div',undefined,'term'),v=el('div');n.append(el('span',label));v.append(el('strong',value(k,rev?.terms[k])),evidenceButton(s,k));n.append(v);$('#terms').append(n);}
 $('#conflicts').replaceChildren(...(rev?.conflicts??[]).map(c=>el('p',`${labels[c.field]} 충돌: ${value(c.field,c.actual)}`,'conflict')));$('#changes').replaceChildren();for(const v of s.revisions)for(const d of v.diff.filter(d=>['price_minor','deadline_seconds'].includes(d.field)&&d.before!==null))$('#changes').append(el('div',`${labels[d.field]} ${value(d.field,d.before)} → ${value(d.field,d.after)} · TURN ${v.event_count}`,'change'));
 $('#signatures').replaceChildren();for(const role of [s.buyer,s.seller]){const n=el('div',undefined,'signature');n.append(el('span',role),el('b',s.confirmations.some(a=>a.agent_id===role&&a.revision_hash===rev?.revision_hash)?'동일 조건 서명 ✓':'확인 대기'));$('#signatures').append(n);}$('#commit-proof').replaceChildren(detail('확정 Deal / 양측 서명',{commit:s.commit,deal:rev?.deal,confirmations:s.confirmations}));$('#policy').replaceChildren(...(o?.policy??[]).map(c=>el('p',(c.pass?'✓ ':'✕ ')+c.name,c.pass?'good':'bad')));
 $('#money-state').textContent=paid?'SETTLED':funded?'LOCKED':'예치 전';const nodes=el('div',undefined,'money-nodes');for(const [title,v,active] of [['남은 예산',funded?s.mandate_snapshot.task_budget_minor-rev.terms.price_minor:s.mandate_snapshot.task_budget_minor,false],['예치금',funded&&!paid?rev.terms.price_minor:0,funded&&!paid],['판매자 지급',paid?rev.terms.price_minor:0,paid]]){const n=el('div',undefined,'money-node '+(active?'active':''));n.append(el('span',title),el('strong',amount(v).replace(' DEMO','')));nodes.append(n);}$('#money').replaceChildren(nodes,el('p',`단위 DEMO · 이 작업의 ${stage==='paid'?'정산 결과':stage==='blocked'?'청구 거절 당시':'예치 당시'} 기록`,'hint'));
 $('#claim-history').replaceChildren();for(const h of stage==='commit'?[]:history.filter(h=>stage==='paid'||h.decision.verdict==='REJECTED')){const box=el('div',undefined,'claim-row '+h.decision.verdict.toLowerCase());box.append(el('span',h.decision.verdict==='REJECTED'?'거절':'정정 승인','tag'),el('strong',amount(h.claim.amount_minor)),el('p',h.decision.reason==='CLAIM_AMOUNT'?'합의 26과 청구 31이 달라 지급하지 않았습니다.':'수령인·자산·거래·납품 해시까지 일치합니다.'),detail('서명과 검사 기록',h));$('#claim-history').append(box);}
 $('#delivery').replaceChildren();if(stage!=='commit'&&o?.validation){$('#delivery').append(el('h3','납품 검수 '+(o.validation.verified?'PASS':'FAIL')));const ul=el('ul',undefined,'proof-list');for(const c of o.validation.checks.filter(c=>c.name.startsWith('REFERENCE_')||c.name==='DELIVERY_DEADLINE'))ul.append(el('li',(c.pass?'✓ ':'✕ ')+({REFERENCE_PERIODS:'네 분기 실적',REFERENCE_VALUES:'기준 원문 수치와 일치',REFERENCE_UNIT:'단위 일치',REFERENCE_PROVENANCE:'공식 문서·페이지·표 근거',DELIVERY_DEADLINE:'납품 기한'}[c.name]??c.name),c.pass?'good':'bad'));$('#delivery').append(ul);if(o.delivery)$('#delivery').append(link('검수한 결과물 JSON 받기','/api/result/'+s.deal_id));}
 $('#receipt').replaceChildren();if(paid){$('#receipt').append(el('h3','영수증 '+o.verification?.verdict));if(r.network.chainId===11155111)$('#receipt').append(link('Sepolia 지급 transaction ↗','https://sepolia.etherscan.io/tx/'+o.transactions.release.tx_hash));$('#receipt').append(link('대화·승인·청구·정산 증거 받기','/api/evidence/'+o.receipt_file));}else $('#receipt').append(el('p',blocked?'거절된 청구와 정정 이력은 최종 영수증에 남습니다.':'확정과 예치가 판매자 지급을 뜻하지 않습니다.','hint'));
 const trail=$('#audit-trail');trail.replaceChildren();for(const [text,k] of [['사람이 작업당 40 DEMO와 Seller A/B를 승인',null],['Seller 제안 → Buyer 역제안 → 최종 총액','price_minor'],['최종 납기와 그 조건을 만든 메시지','deadline_seconds'],[s.commit?'두 프로세스가 전체 거래를 검토하고 동일 버전 서명':'양측 확인 전',null],[rejected?'31 청구 거절: 합의된 총액과 불일치':'청구 확인 전',null],[paid?'납품 검수 + 26 정정 청구 → 실제 지급':'03 지급·감사에서 정산 결과 확인',null]]){const n=el('div',text,'audit-step');if(k)n.append(evidenceButton(s,k));trail.append(n);}
 $('#cases').replaceChildren();for(const [key,title] of [['semantic_conflict','다른 작업 제안'],['bad_delivery','오납품 → 환불'],['repeat','다음 거래 → 샘플 필수'],['revoked','위임 중지'],['expired','만료 경계']]){const b=el('button',title);b.onclick=()=>showCase(r,key);$('#cases').append(b);}
 const usage={};for(const u of r.usage){const v=usage[u.flow_name]??={calls:0,input:0,output:0,ms:0};v.calls++;v.input+=u.prompt_tokens??0;v.output+=u.completion_tokens??0;v.ms+=u.latency_ms??0;}const table=el('table'),head=el('tr');for(const v of ['흐름','호출','입력 토큰','출력 토큰','지연 ms'])head.append(el('th',v));table.append(head);for(const [name,v] of Object.entries(usage)){const row=el('tr');for(const x of [name,v.calls,v.input,v.output,v.ms])row.append(el('td',String(x)));table.append(row);}$('#usage').replaceChildren(table);$('#agents').replaceChildren(...(r.agent_processes??[]).map(a=>el('p',`${a.role} · PID ${a.pid} · 독립 키/저장소 · ${a.transport}`)));}
function showCase(r,key){const s=selected(r,key),o=outcome(r,s);$('#case-note').textContent=({semantic_conflict:'가격이 저렴해도 연간 전망치는 분기 실적과 다릅니다.',bad_delivery:'별도 승인 작업에 작성된 잘못된 값을 납품했습니다.',repeat:'새 위임이어도 같은 회사·판매자에 남은 REQUIRE_PREVIEW를 지울 수 없습니다.',revoked:'사람의 위임 철회가 새 funding을 차단합니다.',expired:'저장된 만료 이후로 정책 시계를 주입한 경계 시험입니다. 실제 시간을 기다린 시험은 아닙니다.'})[key];const box=$('#case-result');box.replaceChildren();if(!s){box.append(el('p','아직 실행되지 않았습니다.'));return;}box.append(el('strong',o?.state??'UNRESOLVED CONFLICT'));if(o){box.append(el('p',o.state==='REFUNDED'?'예치한 26 DEMO → 구매자 환불':'서명된 funding 거래 0건'),detail('기록된 검사',{policy:o.policy,validation:o.validation,control:o.control}),link('이 상황의 영수증 받기','/api/evidence/'+o.receipt_file));}else box.append(detail('원문과 의미 충돌',{messages:s.events,conflicts:s.revisions.at(-1)?.conflicts}));}
async function load(force=false){const res=await fetch('/api/state');if(!res.ok)throw new Error('STATE_UNAVAILABLE');state=await res.json();const key=JSON.stringify([state.report?.run,state.report?.stage,state.report?.status,state.report?.usage?.length,state.job]);if(force||last!==key){last=key;draw();}}
async function post(route,body){const res=await fetch(route,{method:'POST',headers:{'content-type':'application/json','x-dealtrace-token':state.token},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
$$('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;draw();});$('#run').onclick=async()=>{try{if(!$('#approve').checked)throw new Error('먼저 작업과 한도를 승인해 주세요.');await post('/api/runs',{live:$('#execution').value==='live',approved:true});stage='commit';await load(true);}catch(e){$('#status').textContent=e.message;$('#status').classList.add('error');}};$('#stop').onclick=async()=>{try{await post('/api/stop',{});await load(true);}catch(e){$('#status').textContent=e.message;}};
$('#verify-copy').onclick=async()=>{const button=$('#verify-copy'),box=$('#copy-verification'),r=state.report,s=selected(r,'normal');button.disabled=true;box.replaceChildren(el('p','사본 검증 중…'));try{const result=await post('/api/verify-copy/'+s.deal_id,{});if(state.report?.run!==result.run)return;box.replaceChildren(el('h3',`사본 검증: ${result.verification.verdict}`,result.verification.verdict==='INVALID'?'bad':'good'),el('p',`원본 ${amount(result.original_price_minor)} → 사본 ${amount(result.copy_price_minor)}`),el('p',result.verification.verdict==='INVALID'?'가격이 바뀌어 원래 서명된 거래와 일치하지 않습니다. 원본 영수증과 실제 거래는 그대로입니다.':'검증 결과의 범위를 상세 기록에서 확인하세요.'),detail('검증 원본 결과',result));}catch(e){box.replaceChildren(el('p','사본 검증을 완료하지 못했습니다: '+e.message,'bad'));}finally{button.disabled=!!state.job?.running;}};
load(true).catch(e=>{console.error(e.message);$('#status').textContent='기록을 불러오지 못했습니다: '+e.message;});timer=setInterval(()=>load().catch(()=>{}),1800);window.addEventListener('pagehide',()=>clearInterval(timer));
