const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let state,selected=0,revision=null,lastKey='',timer,scene='normal',view='live',moneyPhase='final';
const labels={price_minor:'가격',metric:'납품할 지표',periods:'기간',source_required:'출처',deadline_seconds:'납기',deadline_anchor:'기산 시점',refund_policy:'환불 조건'};
const display=(field,v)=>v===undefined?'아직 제안되지 않음':field==='price_minor'?(v/100).toFixed(2)+' DEMO':field==='metric'?(v==='ACTUAL_QUARTERLY_FACILITY_INVESTMENT'?'분기별 실제 시설투자 현금유출':'연간 CAPEX 전망치'):field==='periods'?v.join(' · '):field==='source_required'?(v?'공식 원문 + 셀 근거 필수':'출처 필수 아님'):field==='deadline_seconds'?v/60+'분':field==='deadline_anchor'?'예치가 체인에 기록된 때부터':'검수 실패 또는 만료 → 구매자 환불';
function showView(name){view=name;$$('[data-view]').forEach(n=>n.hidden=n.dataset.view!==name);$$('[data-target]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.target===name)));}
function sourceButton(id,text){const b=el('button',text,'source-button');b.addEventListener('click',()=>{showView('live');$$('.message').forEach(n=>n.classList.remove('selected'));const n=document.getElementById(id);n?.classList.add('selected');n?.scrollIntoView({behavior:'smooth',block:'center'});});return b;}const $$=s=>[...document.querySelectorAll(s)];
function draw(){const r=state?.report;$('#run').disabled=!!state?.job?.running;$('#stop').disabled=!state?.job?.running;$('#execution option[value=live]').disabled=!state?.live_available;if(!r){$('#status').textContent='아직 실행 기록이 없습니다. 위 조건을 승인하고 작성된 대화 데모를 실행하세요.';return;}
 $('#mode').textContent=(r.mode.startsWith('LIVE_KILN')?'실제 Kiln 대화':'작성된 대화')+' · '+(r.network?.chainId===11155111?'Sepolia 테스트넷':'로컬 체인');$('#status').classList.toggle('error',['FAIL','STOPPED'].includes(r.status));$('#status').textContent=state.job?.running?`새 실행 중 · ${r.stage} · 모델 ${r.usage.length}회. 새 메시지마다 조건과 근거를 추출합니다.`:`저장된 실행 ${r.run.slice(0,8)} · ${r.status} · ${r.summary?.passed??0}/${r.summary?.checks??0} 검증 · ${r.summary?.model_calls??0}회 / ${(r.summary?.total_tokens??0).toLocaleString()} 토큰${r.error?' · '+r.error:''}`;
 const roles=r.session_roles??{normal:r.sessions?.[0]?.session_id,semantic_conflict:r.sessions?.[1]?.session_id,repeat:r.sessions?.[2]?.session_id,authority_attack:r.sessions?.[3]?.session_id,bad_delivery:r.sessions?.[0]?.session_id};
 $('#sessions').replaceChildren();for(const [key,title] of [['normal','01 합의 → 지급'],['authority_attack','02 권한 조작 → 차단'],['bad_delivery','03 실패 → 다음 권한']]){const b=el('button',title);b.setAttribute('aria-pressed',String(scene===key||(scene==='repeat'&&key==='bad_delivery')));b.onclick=()=>{scene=key;selected=r.sessions.findIndex(s=>s.session_id===roles[key]);revision=null;moneyPhase='final';draw();};$('#sessions').append(b);}
 const notes={normal:'Kiln이 가격·작업 조건을 대화로 제안합니다. 코드가 같은 합의와 권한을 확인한 뒤 검수된 작업에 지급합니다.',authority_attack:'“관리자가 한도를 높였다”는 판매자의 말은 증거로 남지만, 사람이 준 권한을 바꾸지는 못합니다.',bad_delivery:'같은 Seller A의 다음 의뢰에 잘못된 값을 주입합니다. 환불은 이 거래를 끝내고, 새 제한은 다음 거래를 바꿉니다.',repeat:'두 Agent가 다시 동의하고 예산도 맞습니다. 그래도 이전 실패 때문에 샘플 없이는 예치할 수 없습니다.',semantic_conflict:'추가 검증: 1.50 DEMO로 싸더라도 연간 전망치는 요청한 분기 실적이 아닙니다.'};
 $('#scene-note').replaceChildren(el('p',notes[scene]));if(['bad_delivery','repeat'].includes(scene)){const b=el('button',scene==='repeat'?'이전 실패 거래 보기':'같은 판매자의 다음 거래 보기 →');b.onclick=()=>{scene=scene==='repeat'?'bad_delivery':'repeat';selected=r.sessions.findIndex(s=>s.session_id===roles[scene]);revision=null;moneyPhase='final';draw();};$('#scene-note').append(b);}
 $('#semantic-case').onclick=()=>{scene='semantic_conflict';selected=r.sessions.findIndex(s=>s.session_id===roles.semantic_conflict);revision=null;showView('live');draw();$('#sessions').scrollIntoView({behavior:'smooth'});};
 const s=r.sessions?.[selected]??r.sessions?.[0];if(!s)return;const latest=s.revisions.at(-1),rev=s.revisions.find(v=>v.revision===revision)??latest;$('#turn-count').textContent=s.events.length+'개 외부 메시지';$('#revision').textContent=rev?`v${rev.revision} / ${latest.revision}`:'의미 추출 대기';$('#messages').replaceChildren();for(const m of s.events){const n=el('div',undefined,'message '+(m.sender_agent===s.buyer?'buyer':'seller'));n.id=m.event_id;const meta=el('div',undefined,'message-meta');meta.append(el('span',m.sender_agent===s.buyer?'BUYER AGENT':m.sender_agent.toUpperCase()),el('span',`TURN ${m.sequence}`));n.append(meta,el('p',m.content));const proof=el('details');proof.append(el('summary','메시지 서명'),el('code',m.message_hash));n.append(proof);$('#messages').append(n);}
 $('#terms').replaceChildren();for(const [field,label] of Object.entries(labels)){const t=el('div',undefined,'term'),content=el('div');t.append(el('span',label,'term-label'));content.append(el('strong',display(field,rev?.terms[field])));const p=rev?.provenance[field];if(p){const m=s.events.find(e=>e.event_id===p.event_id);content.append(sourceButton(p.event_id,`TURN #${m?.sequence} · ${p.proposed_by} ↗`));}t.append(content);$('#terms').append(t);}
 $('#conflicts').replaceChildren();for(const c of rev?.conflicts??[]){const d=el('div',undefined,'conflict');d.append(el('b','미해결 충돌 · 거래 확정 불가'),el('p',`제안: ${display(c.field,c.actual)}`),el('p',`요청: ${display(c.field,c.expected)}`));$('#conflicts').append(d);}
 $('#price-history').replaceChildren();for(const v of s.revisions)for(const d of v.diff.filter(d=>d.field==='price_minor')){const b=el('button',display('price_minor',d.after),'price-step');b.append(el('small',`TURN #${v.event_count} · v${v.revision}`));b.setAttribute('aria-pressed',String(rev?.revision===v.revision));b.addEventListener('click',()=>{revision=v.revision;draw();});$('#price-history').append(b);}if(revision){const b=el('button','최종 조건 보기');b.onclick=()=>{revision=null;draw();};$('#price-history').append(b);}
 $('#confirmations').replaceChildren();const h=el('div',undefined,'hashes');h.append(el('h3','동일한 최종 조건을 확인했나요?'));for(const role of [s.buyer,s.seller]){const ack=s.confirmations.find(a=>a.agent_id===role&&a.revision_hash===latest?.revision_hash);const row=el('div',undefined,'signed');row.append(el('span',role),el('b',ack?'동일 해시 서명 ✓':'서명 없음'));h.append(row);}h.append(el('p','대화상 “Agreed”만으로는 확정하지 않습니다.','small'));if(s.commit){h.append(el('strong','DEAL COMMITTED','committed'));const hashes=el('details');hashes.append(el('summary','같은 버전·Deal 해시 확인'),el('code',s.commit.revision_hash),el('p','에스크로 Deal 해시','small'),el('code',s.commit.deal_hash));h.append(hashes);}$('#confirmations').append(h);
 const outcome=r.outcomes.find(o=>o.deal_id===s.deal_id)??r.financial_states?.find(o=>o.deal_id===s.deal_id),checks=outcome?.policy??[];$('#final-state').textContent=outcome?.state??(s.commit?'COMMITTED':'NOT COMMITTED');$('#policy').replaceChildren();const groups=[['양측 합의',checks.filter(c=>c.name==='BILATERAL_AGREEMENT'),!!s.commit],['사람의 위임',checks.filter(c=>!['BILATERAL_AGREEMENT','PREVIEW_REQUIRED'].includes(c.name)),null],['이전 거래가 만든 조건',checks.filter(c=>c.name==='PREVIEW_REQUIRED'),null]];for(const [title,list,fallback] of groups){const passed=list.length?list.every(c=>c.pass):fallback;const g=el('div',undefined,'gate '+(passed===false?'block':passed===null?'pending':''));g.append(el('h3',title),el('strong',passed===null?'검사 전':passed?'PASS':'BLOCK'));const ul=el('ul');for(const c of list)ul.append(el('li',(c.pass?'✓ ':'✕ ')+c.name));if(!list.length)ul.append(el('li',fallback?'두 에이전트 서명 확인':'미해결 조건이나 확인 누락'));const detail=el('details');detail.append(el('summary','검사 근거'),ul);g.append(detail);$('#policy').append(g);}
 $('#memory').replaceChildren();const text=el('div');text.append(el('span','OUTCOME → PERMISSION','eyebrow'),el('h2','“이번에는 잘하겠습니다.”\n그래도 샘플부터.'),el('p','같은 회사·같은 공급자의 실패만 다음 주문의 권한을 좁힙니다. 에이전트의 새 합의가 이 조건을 지울 수 없습니다.'));const flow=el('div',undefined,'memory-flow');for(const line of ['이전 거래: 원문과 납품 값 불일치 → 검수 실패 · 환불','새 조건: REQUIRE_PREVIEW · 해당 회사 × Seller A','다음 거래: 양측 서명 ✓ · 예산 ✓ · 샘플 ✕ → 예치 차단'])flow.append(el('span',line));if(!r.outcomes.some(o=>o.control))flow.append(el('b','아직 이 실행에서 실패·기억 생성 전입니다.'));$('#memory').append(text,flow);
 $('#outcomes').replaceChildren();for(const o of r.outcomes.filter(o=>o.deal_id===s.deal_id)){const card=el('article',undefined,'outcome');card.append(el('h3',o.label),el('p',o.state+' · 영수증 '+o.verification.verdict));const tx=o.transactions.release??o.transactions.refund;if(tx?.tx_hash&&r.network?.chainId===11155111){const link=el('a','Sepolia에서 정산 확인 ↗');link.href='https://sepolia.etherscan.io/tx/'+tx.tx_hash;link.target='_blank';link.rel='noopener';card.append(link);}const hashes=el('details');hashes.append(el('summary','정산 거래 해시'),el('code',tx?.tx_hash??'새 지급/환불 거래 없음'));card.append(hashes);const a=el('a','승인·합의·정산 영수증 받기');a.href='/api/evidence/'+o.receipt_file;card.append(el('p'),a);$('#outcomes').append(card);}
 renderOutcome(r,s,outcome);showView(view);
 $('#trace').replaceChildren();const audit=el('details');audit.append(el('summary','선택한 협상의 메시지 → 버전 → 서명 → 확정 이력'));for(const e of s.audit){const row=el('div',e.type,'trace-row');row.append(el('code',JSON.stringify(e.payload)));audit.append(row);}$('#trace').append(audit);
 const table=el('table'),tr=el('tr');for(const title of ['흐름','호출','입력','출력','지연 ms'])tr.append(el('th',title));table.append(tr);const usage={};for(const u of r.usage){const k=u.flow_name;usage[k]??={calls:0,tokens:0,input:0,output:0,latency:0};usage[k].calls++;usage[k].tokens+=u.total_tokens??0;usage[k].input+=u.prompt_tokens??0;usage[k].output+=u.completion_tokens??0;usage[k].latency+=u.latency_ms??0;}for(const [flow,v] of Object.entries(usage)){const row=el('tr');row.append(el('td',flow),el('td',v.calls),el('td',v.input.toLocaleString()),el('td',v.output.toLocaleString()),el('td',v.latency.toLocaleString()));table.append(row);}if(!r.usage.length){const row=el('tr');row.append(el('td','작성된 대화와 추출 후보'),el('td','0'),el('td','0'));table.append(row);}$('#usage').replaceChildren(table,el('p','전력은 측정하지 않았습니다. 서명·예산·재거래 검사는 코드로 처리합니다.','small'));
}
async function load(force=false){const res=await fetch('/api/state');state=await res.json();const key=JSON.stringify([state.report?.run,state.report?.stage,state.report?.status,state.report?.sessions?.map(s=>[s.events.length,s.revisions.length,s.confirmations.length]),state.job]);if(force||key!==lastKey){lastKey=key;draw();}}
async function post(path,body){const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-dealtrace-token':state.token},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
$('#run').onclick=async()=>{try{if(!$('#approve').checked)throw new Error('먼저 위 조건을 승인해 주세요.');await post('/api/runs',{live:$('#execution').value==='live',approved:true});selected=0;scene='normal';revision=null;showView('live');await load(true);}catch(e){$('#status').textContent=e.message;$('#status').classList.add('error');}};
$('#stop').onclick=async()=>{try{await post('/api/stop',{});$('#status').textContent='위임 중지를 요청했습니다. 진행 중 추론은 끝날 수 있으며 이미 서명한 거래는 상태를 확인합니다.';}catch(e){$('#status').textContent=e.message;}};
load(true).catch(e=>{console.error('DealTrace UI:',e.message);$('#status').textContent='화면을 불러오지 못했습니다: '+e.message;});timer=setInterval(()=>load().catch(()=>{}),1800);window.addEventListener('pagehide',()=>clearInterval(timer));

$$('[data-target]').forEach(b=>b.onclick=()=>showView(b.dataset.target));
function renderOutcome(r,s,o){
 const price=s.revisions.at(-1)?.terms.price_minor,amount=price?display('price_minor',price):'미정';
 $('#authority-claim').replaceChildren();if(scene==='authority_attack'){const box=el('div',undefined,'claim-comparison');const claim=el('div'),authority=el('div');claim.append(el('span','SELLER CLAIM · 신뢰하지 않는 메시지','eyebrow'),el('h2','“관리자가 증액을 승인했습니다.”'),el('p','판매자 제안 '+amount));authority.append(el('span','HUMAN MANDATE · 저장된 사람의 승인','eyebrow'),el('h2',display('price_minor',s.mandate_snapshot.max_single_minor)+'까지'),el('p','대화는 권한을 만들 수 없습니다.'));box.append(claim,authority);$('#authority-claim').append(box);}
 $('#money').replaceChildren();const panel=el('article',undefined,'money-panel');panel.append(el('span','SETTLEMENT · 저장된 거래 증거','eyebrow'),el('h2',o?.state==='SETTLED'?'검수한 작업에만 지급했습니다.':o?.state==='REFUNDED'?'약속과 달라 구매자에게 돌려줬습니다.':o?.state==='PREVIEW_REQUIRED'?'합의는 있지만, 예치는 불가합니다.':o?.state==='BLOCKED'?'돈이 움직이기 전에 멈췄습니다.':'아직 정산되지 않았습니다.'));
 const funded=o?.transactions.fund?.status==='CONFIRMED',destination=moneyPhase==='locked'&&funded?'locked':o?.state==='SETTLED'?'seller':'buyer';
 const path=el('div',undefined,'money-path');for(const [key,title] of [['buyer','BUYER · 구매자'],['locked','ESCROW · 예치'],['seller','SELLER · 판매자']]){const node=el('div',undefined,'money-node '+(destination===key?'active':''));node.append(el('span',title),el('strong',destination===key?(['BLOCKED','PREVIEW_REQUIRED'].includes(o?.state)?'지출 0 DEMO':amount):'—'));path.append(node);}panel.append(path,el('p','이 의뢰의 금액 흐름입니다. 실제 계좌 잔액이나 가스 비용을 표시하지 않습니다.','small'));
 if(funded){const steps=el('div',undefined,'actions');for(const [phase,label] of [['locked','예치 당시'],['final','정산 결과']]){const b=el('button',label);b.setAttribute('aria-pressed',String(moneyPhase===phase));b.onclick=()=>{moneyPhase=phase;renderOutcome(r,s,o);};steps.append(b);}panel.append(steps,el('p','위 버튼은 저장된 이력을 재생합니다. 새로운 거래를 보내지 않습니다.','small'));}else panel.append(el('p',['BLOCKED','PREVIEW_REQUIRED'].includes(o?.state)?'서명된 funding 거래 0건 · 구매자 측에 그대로 유지':'아직 확정된 예치 기록 없음 · 진행 상태 확인 중','stop-proof'));
 $('#money').append(panel);$('#delivery-checks').replaceChildren();const checks=el('article',undefined,'delivery-panel');checks.append(el('h2','무엇을 검사했나요?'));if(o?.validation){const result=o.validation;checks.append(el('p',result.verified?'PASS · 약속한 네 분기 값과 출처 검사를 통과했습니다.':'FAIL · 약속한 데이터와 납품이 달랐습니다.',result.verified?'pass-proof':'stop-proof'));const expected=r.reference_rows?.find(x=>x.quarter==='2025-Q1');let delivered;try{delivered=JSON.parse(o.delivery??'[]').find(x=>x.quarter==='2025-Q1');}catch{}if(!result.verified&&expected&&delivered)checks.append(el('p',`작성된 오류 주입 · Q1 원문 기준 ${expected.capex.toLocaleString()} / 납품 ${delivered.capex.toLocaleString()} (${expected.unit} ${expected.currency})`));const list=el('ul','', 'validation-list');const names={REFERENCE_PERIODS:'네 분기의 실제값',REFERENCE_VALUES:'원문 수치와 일치',REFERENCE_UNIT:'단위 일치',REFERENCE_PROVENANCE:'공식 원문·셀 근거',DELIVERY_DEADLINE:'납품 기한'};for(const c of result.checks.filter(c=>names[c.name]))list.append(el('li',`${c.pass?'✓':'✕'} ${names[c.name]}`,c.pass?'pass-proof':'stop-proof'));checks.append(list);const d=el('details');d.append(el('summary','실제 검수 기록'),el('pre',JSON.stringify(result,null,2)));checks.append(d);}else checks.append(el('p','예치 전 단계에서 중지했으므로 납품·정산 검사는 실행하지 않았습니다.'));$('#delivery-checks').append(checks);
 $('#memory').hidden=!['bad_delivery','repeat'].includes(scene);
 const answer=el('ol',undefined,'audit-steps');const lines=[`사람이 정한 거래당 한도: ${display('price_minor',s.mandate_snapshot.max_single_minor)}`,`현재 합의: ${amount} · ${s.commit?'양측이 같은 Deal에 서명':'합의 미확정'}`,o?.state==='BLOCKED'?'한도 초과 → 서명 전 차단':o?.state==='PREVIEW_REQUIRED'?'이전 실패로 샘플 필수 → 샘플 없음 → 예치 차단':o?.state==='SETTLED'?'검수 통과 → Seller에게 지급':o?.state==='REFUNDED'?'검수 실패 → Buyer에게 환불 → 다음 거래 샘플 필수':'정산 없음',o?`내보낸 영수증 재검증: ${o.verification?.verdict??'아직 대기 중'}`:'아직 영수증 없음'];for(const line of lines)answer.append(el('li',line));$('#audit-answer').replaceChildren(answer);
}
