const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let data,token,active='overbill';
const cases={overbill:{labels:['사람이 서명한 예산','양측이 서명한 거래','서버가 체인에 요청'],values:['40 DEMO','26 DEMO','31 DEMO'],notes:['등록한 전체 위임 한도','같은 거래 해시 · 같은 총액','판매자와 검수자 모두 서명'],reason:'CLAIM_MISMATCH',story:'예산 안의 청구라도 합의 총액과 다르면 지급할 수 없습니다. 판매자와 검수자의 유효한 서명까지 넣어, 금액 검사를 우회할 수 있는지 시험했습니다.',attack:'attack-overbill',title:'26으로 정정한 뒤 지급',outcomes:['release-success','withdraw-seller']},preview:{labels:['이전 납품','새 위임의 거래','필수 샘플'],values:['검수 실패','양측 서명','없음'],notes:['환불과 동시에 제한 기록','같은 구매자 · 같은 판매자','검수자의 샘플 승인도 없음'],reason:'PREVIEW_REQUIRED',story:'오납품을 환불한 뒤 완전히 새로운 위임과 거래 서명을 만들었습니다. 구매자·판매자 쌍에 남은 체인상의 샘플 요구가 예치를 막았습니다.',attack:'attack-preview',title:'환불도, 다음 거래의 제한도 체인에',outcomes:['refund-failure','withdraw-buyer']},revoked:{labels:['사람의 결정','에이전트의 서명','새 예치 시도'],values:['권한 철회','아직 유효','차단'],notes:['구매자 키로 철회 거래 제출','철회 전 받아 둔 거래 서명','오래된 서명으로 우회 불가'],reason:'AUTHORITY_INACTIVE',story:'사용자가 권한을 철회한 뒤, 기존의 유효한 거래 서명으로 다시 예치를 시도했습니다. 체인은 현재 위임 상태를 읽고 거절했습니다.',attack:'attack-revoked',title:'철회 후 새 지출 없음',outcomes:['revoke-repeat']}};
const names={'release-success':'정정 26 → 판매자 인출 권리','withdraw-seller':'26 → 판매자 실제 송금','refund-failure':'오납품 환불 + 샘플 요구 기록','withdraw-buyer':'26 → 구매자 실제 환불','revoke-repeat':'사용자 권한 철회'};
function proof(label){const t=data.report.transactions.find(t=>t.label===label),n=el('div',undefined,'vault-proof');n.append(el('strong',names[label]??label));const a=el('a',t.status===0?'실패한 실제 거래 확인 ↗':'성공한 실제 거래 확인 ↗','download');a.href='https://sepolia.etherscan.io/tx/'+t.tx_hash;a.target='_blank';a.rel='noopener';n.append(a,el('code',t.tx_hash),el('small',`블록 ${t.block.toLocaleString()} · receipt status ${t.status}`));return n;}
function draw(){const c=cases[active];for(const [i,id] of ['left','middle','right'].entries()){ $('#'+id+'-label').textContent=c.labels[i];$('#'+id+'-value').textContent=c.values[i];$('#'+id+'-note').textContent=c.notes[i];}$('#reason').textContent=c.reason;$('#attack-story').textContent=c.story;$('#outcome-title').textContent=c.title;$('#attack-proof').replaceChildren(proof(c.attack));$('#outcome-proof').replaceChildren(...c.outcomes.map(proof));document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===active)));}
function verification(v){const box=$('#verification-detail');box.replaceChildren();if(!v){$('#verification').textContent='finalized 검증 대기';box.append(el('p','체인 최종 확정 결과를 기다립니다.'));return;}const final=v.verdict==='VALID'&&v.block_tag==='finalized',pending=v.reason==='FINALITY_PENDING';$('#verification').textContent=final?`FINALIZED · ${v.checks}개 검사 통과`:pending?'체인 최종 확정 대기':v.verdict;box.append(el('strong',final?'독립 검증 VALID':pending?'최종 확정 대기':v.verdict,final?'good':pending?'pending':'bad'));if(v.reason)box.append(el('p',pending?'거래는 기록됐고, finalized 블록이 도달하면 최종 검증할 수 있습니다.':v.reason));if(v.block)box.append(el('p',`finalized 블록 ${v.block.toLocaleString()} · ${v.checks}개 검사`));box.append(el('p','원문·양측 서명 → 거래 입력 → 이벤트 → 현재 상태를 대조합니다.'));if(v.checked_at)box.append(el('small',new Date(v.checked_at).toLocaleString('ko-KR')));}
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{active=b.dataset.case;draw();});
$('#verify-vault').onclick=async()=>{const b=$('#verify-vault');b.disabled=true;$('#verification-detail').replaceChildren(el('p','별도 RPC에서 finalized 블록을 검증하는 중…'));try{const response=await fetch('/api/vault-verify',{method:'POST',headers:{'content-type':'application/json','x-dealtrace-token':token},body:'{}'});const result=await response.json();if(!response.ok)throw new Error(result.error);verification(result);}catch(e){$('#verification-detail').replaceChildren(el('p','검증 미완료: '+e.message,'bad'));}finally{b.disabled=false;}};
async function load(){const [state,response]=await Promise.all([fetch('/api/state').then(r=>r.json()),fetch('/api/vault-proof')]);if(!response.ok)throw new Error('아직 공개 V2 실증을 준비 중입니다.');token=state.token;data=await response.json();draw();verification(data.verification);$('#vault-status').textContent=`저장된 V2 공개 실증 · ${data.report.transactions.length}건 실제 거래 · 실패 3건 포함 · 새 거래나 모델 호출 없음`;$('#all-transactions').replaceChildren(...data.report.transactions.map(t=>proof(t.label)));const a=el('a',data.report.network.contract);a.href='https://sepolia.etherscan.io/address/'+data.report.network.contract;a.target='_blank';a.rel='noopener';$('#deployment').append(el('p','검증 대상 V2 컨트랙트'),a);}
load().catch(e=>{$('#vault-status').textContent=e.message;$('#verify-vault').disabled=true;console.error(e.message);});
