// Stable IDs connect a requirement, executable check, finding, and replay command.
export const categories = {
  invariants:'불변조건', scenarios:'시나리오 시뮬레이션', redteam:'레드팀',
  operations:'운영·복구', e2e:'HTTP E2E 데모', browser:'브라우저 데모', personas:'기획 기반 페르소나', live:'실제 Kiln E2E',
};
export const checks = [
  ['INV-001','invariants','정수 금액·총액·서명·기한 경계','P0','src/policy.mjs'],
  ['INV-002','invariants','시드 기반 상태 전이와 예약금 보존','P0','src/policy.mjs'],
  ['INV-003','invariants','병렬 구매의 예산·실제 결제·독립 증빙 일치','P0','src/engine.mjs'],
  ['INV-004','invariants','SQL 원자성 및 비동기 트랜잭션 차단','P0','src/store.mjs'],
  ['SIM-001','scenarios','B0/B1/CM × 전체 시나리오 결과 행렬','P1','src/fixtures.mjs'],
  ['SIM-002','scenarios','실패 기억·조기 차단·판매자 정상화·견적 마찰','P1','src/engine.mjs'],
  ['SIM-003','scenarios','추론 호출 상한과 중복 요청 재사용','P0','src/engine.mjs'],
  ['RED-001','redteam','악성 모델 출력·초과 금액·비밀 반사 거부','P0','src/kiln.mjs'],
  ['RED-002','redteam','승인·견적·증빙·통제 기록 변조 탐지','P0','src/verifier.mjs'],
  ['RED-003','redteam','정책 우회 계약 공격 및 실행자 권한','P0','contracts/ControlMemory.sol'],
  ['RED-004','redteam','판매자 지시문은 승인 범위를 변경하지 못함','P0','src/engine.mjs'],
  ['OPS-001','operations','영수증 유실 후 디스크 재시작·정확히 한 번 정산','P0','src/engine.mjs'],
  ['OPS-002','operations','송신 전 중단 복구와 제출 후 중지 경합','P0','src/policy.mjs'],
  ['OPS-003','operations','RPC 장애·미확정 예약 유지·취소 재시도','P0','src/engine.mjs'],
  ['OPS-004','operations','SQLite 백업 복원·체인 소스 지문 일치','P1','src/store.mjs'],
  ['OPS-005','operations','준비 상태 진단과 의존 서비스 장애','P1','src/app.mjs'],
  ['E2E-001','e2e','실제 HTTP 로그인→승인→결제→다운로드→검증','P0','src/app.mjs'],
  ['E2E-002','e2e','인증·타인 세션·Origin·Host·서명 재사용 공격','P0','src/app.mjs'],
  ['E2E-003','e2e','HTTP 중지·초과 수수료·미허용 판매자 결제 부재','P0','src/app.mjs'],
  ['BROWSER-001','browser','실제 화면에서 위임·구매·검증·변조·다운로드·중지','P1','web/App.tsx'],
  ['PER-001','personas','한 판매자만 승인한 예산 책임자의 정상 구매','P1','src/engine.mjs'],
  ['PER-002','personas','낮은 한도·악성 후보 혼재·후보 순서와 정상 기회','P1','src/engine.mjs'],
  ['PER-003','personas','수수료 실패 후 정상화·같은 소유자의 새 상향 승인','P1','src/engine.mjs'],
  ['PER-004','personas','초기 35 TC 협상→28 TC 및 최저 수용가 경계','P1','src/engine.mjs'],
  ['PER-005','personas','선제 견적 거절의 마찰과 적격 대안 선택','P1','src/engine.mjs'],
  ['PER-006','personas','U1 정상·주입 쌍의 하드 안전과 품질 손실 분리','P1','src/kiln.mjs'],
  ['PER-007','personas','공용 저장소의 두 팀 격리·통제 승계·원인 증빙','P0','src/verifier.mjs'],
  ['PER-008','personas','송신 전 장애→사용자 취소→공유 executor 복구','P0','src/engine.mjs'],
  ['PER-009','personas','과거 영수증 감사와 변조된 현재 세션 요약','P1','src/verifier.mjs'],
  ['PER-010','personas','중복 클릭·여러 구매 에이전트의 예산 경합','P0','src/engine.mjs'],
  ['LIVE-001','live','실제 qwen3-32b→HTTP 제품 흐름→devnet 결제','P1','src/kiln.mjs'],
].map(([id,category,title,priority,target])=>({id,category,title,priority,target}));
export const title=id=>{const c=checks.find(c=>c.id===id);if(!c)throw new Error('UNKNOWN_CHECK');return `[${id}] ${c.title}`;};
