import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {DealStore} from '../../src/deal-escrow/store.ts';import {DealEngine} from '../../src/deal-escrow/engine.ts';import {openChain} from '../../src/deal-escrow/chain.mjs';import {referenceRows} from '../../src/deal-escrow/reference.ts';import {receipt,verifyReceipt} from '../../src/deal-escrow/audit.ts';
import {hash} from '../../src/deal-escrow/domain.ts';import {NegotiationLedger,identity,signedConfirmation} from '../../src/dealtrace/ledger.mjs';import {newMandate,participants,opening,openingInterpretation,send,priceInterpretation,confirmBoth} from '../../src/dealtrace/scenario.mjs';import {assuranceProfile,signClaim} from '../../src/dealtrace/claims.mjs';

test('negotiated work requires an exact signed invoice after delivery',async t=>{
 const chain=await openChain(),store=new DealStore(':memory:'),engine=new DealEngine(store,chain),ledger=new NegotiationLedger(engine),actors=participants(),raw=JSON.stringify(referenceRows());
 function make(patch={}){const m=newMandate(engine,{company_id:randomUUID(),max_single_minor:4000,task_budget_minor:4000,...patch}),s=ledger.create(m.mandate_id,actors.buyer,actors.sellerA,assuranceProfile(chain.deployment,'seller-a'));const e=send(ledger,s.session_id,actors.buyer,opening);ledger.interpret(s.session_id,openingInterpretation(e));const offer=send(ledger,s.session_id,actors.sellerA,'26.00 DEMO for the same requested work.');ledger.interpret(s.session_id,priceInterpretation(offer,2600));const yes=send(ledger,s.session_id,actors.buyer,'Agreed.');ledger.interpret(s.session_id,{event_id:yes.event_id,kind:'accept',patch:[]});confirmBoth(ledger,s.session_id,actors);return store.get(s.deal_id);}
 const claim=(r,patch={})=>signClaim(actors.sellerA,r.deal,raw,{issued_at:engine.clock(),...patch});
 try{
  await t.test('mandate-level assurance cannot be bypassed through a legacy direct proposal',async()=>{const existing=make(),m=newMandate(engine,{task_budget_minor:4000,max_single_minor:4000,deal_assurance_required:true}),d={...existing.deal,deal_id:randomUUID()};engine.propose(d,m.mandate_id);engine.agentAction('accept_deal',{deal_id:d.deal_id});await engine.fund(d.deal_id);assert.equal(store.get(d.deal_id).state,'BLOCKED');assert.equal(store.operation(d.deal_id,'fund'),null);});
  await t.test('gas ceiling and a truncated delivery window stop before signing',async()=>{const r=make(),old=process.env.DEALTRACE_MAX_GAS_WEI;process.env.DEALTRACE_MAX_GAS_WEI='1';try{await assert.rejects(engine.fund(r.deal.deal_id),/OPERATOR_GAS_BUDGET_EXCEEDED/);assert.equal(store.operation(r.deal.deal_id,'fund').raw,undefined);}finally{if(old===undefined)delete process.env.DEALTRACE_MAX_GAS_WEI;else process.env.DEALTRACE_MAX_GAS_WEI=old;}const short=make({expires_at:engine.clock()+100});await assert.rejects(engine.fund(short.deal.deal_id),/DELIVERY_WINDOW_TRUNCATED/);assert.equal(store.operation(short.deal.deal_id,'fund').raw,undefined);});
  await t.test('an early claim is recorded as rejected and never becomes valid silently after delivery',async()=>{const r=make();await engine.fund(r.deal.deal_id);const early=await engine.claim(r.deal.deal_id,claim(r));assert.equal(early.decision.reason,'CLAIM_DELIVERY');await engine.deliver(r.deal.deal_id,raw);assert.equal(store.operation(r.deal.deal_id,'release'),null);await engine.claim(r.deal.deal_id,claim(r));assert.equal((await verifyReceipt(receipt(engine,r.deal.deal_id),chain)).verdict,'VALID');});
  await t.test('26 locked; 31 under budget rejected; delivery and restart alone never pay; corrected 26 pays once',async()=>{const r=make();await engine.fund(r.deal.deal_id);await engine.deliver(r.deal.deal_id,raw);assert.equal(store.get(r.deal.deal_id).state,'DELIVERY_VERIFIED');assert.equal(store.operation(r.deal.deal_id,'release'),null);const nonce=await chain.provider.getTransactionCount(chain.wallet.address);
   const bad=await engine.claim(r.deal.deal_id,claim(r,{amount_minor:3100}));assert.equal(bad.decision.reason,'CLAIM_AMOUNT');assert.equal(await chain.provider.getTransactionCount(chain.wallet.address),nonce);await new DealEngine(store,chain).recover();assert.equal(store.operation(r.deal.deal_id,'release'),null);
   const good=claim(r);await Promise.all([engine.claim(r.deal.deal_id,good),engine.claim(r.deal.deal_id,good)]);assert.equal(store.get(r.deal.deal_id).state,'SETTLED');assert.equal(await chain.provider.getTransactionCount(chain.wallet.address),nonce+1);const exported=receipt(engine,r.deal.deal_id);assert.equal((await verifyReceipt(exported,chain)).verdict,'VALID');const tamper=structuredClone(exported);tamper.events.find(e=>e.event_type==='SETTLEMENT_CLAIM_RECORDED').structured_payload.claim.amount_minor=2600;assert.equal((await verifyReceipt(tamper,chain)).verdict,'INVALID');const missing=structuredClone(exported);delete missing.source_manifest;assert.equal((await verifyReceipt(missing,chain)).verdict,'INCOMPLETE');
  });
  await t.test('same amount with wrong payee, asset, delivery, Deal or signature cannot release',async()=>{const r=make();await engine.fund(r.deal.deal_id);await engine.deliver(r.deal.deal_id,raw);for(const [patch,reason] of [[{payee:chain.deployment.buyer.toLowerCase()},'CLAIM_PAYEE'],[{asset:'USD'},'CLAIM_ASSET'],[{delivery_hash:hash('other')},'CLAIM_DELIVERY'],[{deal_hash:hash('other')},'CLAIM_DEAL']])assert.equal((await engine.claim(r.deal.deal_id,claim(r,patch))).decision.reason,reason);const forged=signClaim(identity('seller-a'),r.deal,raw);assert.equal((await engine.claim(r.deal.deal_id,forged)).decision.reason,'CLAIM_SIGNATURE');assert.equal(store.operation(r.deal.deal_id,'release'),null);await engine.claim(r.deal.deal_id,claim(r));assert.equal((await verifyReceipt(receipt(engine,r.deal.deal_id),chain)).verdict,'VALID');});
  await t.test('an invoice ID is immutable even after rejection; a new ID can correct it',async()=>{const r=make();await engine.fund(r.deal.deal_id);await engine.deliver(r.deal.deal_id,raw);const wrong=claim(r,{amount_minor:3100});await engine.claim(r.deal.deal_id,wrong);await assert.rejects(engine.claim(r.deal.deal_id,claim(r,{claim_id:wrong.claim_id})),/CLAIM_ID_CONTENT_MISMATCH/);await engine.claim(r.deal.deal_id,claim(r));});
  await t.test('failed delivery refunds without requiring an invoice and still creates preview control',async()=>{const r=make();await engine.fund(r.deal.deal_id);const rows=referenceRows();rows[0].capex=42;await engine.deliver(r.deal.deal_id,JSON.stringify(rows));assert.equal(store.get(r.deal.deal_id).state,'REFUNDED');assert.equal((await verifyReceipt(receipt(engine,r.deal.deal_id),chain)).verdict,'VALID');assert(engine.gate(store.get(r.deal.deal_id)));});
  await t.test('revocation while waiting for a correct invoice refunds instead of paying',async()=>{const r=make();await engine.fund(r.deal.deal_id);await engine.deliver(r.deal.deal_id,raw);store.revoke(r.mandateId);await engine.claim(r.deal.deal_id,claim(r));assert.equal(store.get(r.deal.deal_id).state,'REFUNDED');assert.equal((await verifyReceipt(receipt(engine,r.deal.deal_id),chain)).verdict,'VALID');});
  await t.test('changing a signed assurance profile diverges even if the price is unchanged',()=>{const m=newMandate(engine,{task_budget_minor:4000,max_single_minor:4000}),s=ledger.create(m.mandate_id,actors.buyer,actors.sellerA,assuranceProfile(chain.deployment,'seller-a'));const e=send(ledger,s.session_id,actors.buyer,opening);ledger.interpret(s.session_id,openingInterpretation(e));const o=send(ledger,s.session_id,actors.sellerA,'26 DEMO.');ledger.interpret(s.session_id,priceInterpretation(o,2600));const current=ledger.session(s.session_id),rev=structuredClone(current.revisions.at(-1));rev.deal.assurance.payee=chain.deployment.buyer.toLowerCase();assert.throws(()=>ledger.confirm(s.session_id,signedConfirmation(current,rev,actors.sellerA)),/DEAL_DIVERGENCE/);});
 }finally{store.close();await chain.close();}
});
