import test from 'node:test';import assert from 'node:assert/strict';import {KilnClient,approvedToolNames} from '../../src/deal-escrow/kiln.ts';
const answer={model:'organizer-model',id:'request-test',usage:{prompt_tokens:11,completion_tokens:7,total_tokens:18},choices:[{finish_reason:'tool_calls',message:{tool_calls:[{type:'function',function:{name:'accept_deal',arguments:'{"deal_id":"deal-1"}'}}]}}]};
test('Kiln identifier is required and telemetry records real response usage',async()=>{assert.throws(()=>new KilnClient({model:'',key:'test'}),/MODEL_REQUIRED/);const records=[];let request;const c=new KilnClient({model:'organizer-model',key:'test',fetchImpl:async(_u,options)=>{request=JSON.parse(options.body);return Response.json(answer);},onRecord:r=>records.push(r)});assert.deepEqual((await c.call('selection','Buyer',{deal_id:'deal-1'},'accept_deal')).args,{deal_id:'deal-1'});assert.equal(request.model,'organizer-model');assert.equal(records[0].total_tokens,18);assert.equal(records[0].first_token_time,null);assert.equal(records[0].result,'VALID_TOOL_PROPOSAL');assert.equal(request.tools.length,1);assert.ok(!approvedToolNames.some(n=>/money|escrow|budget|control/.test(n)));});
test('unsafe model tools, unknown fields, malformed actions and truncation fail closed',async()=>{for(const change of [b=>b.choices[0].message.tool_calls[0].function.name='release_escrow',b=>b.choices[0].message.tool_calls[0].function.arguments='{"deal_id":"deal-1","amount":999}',b=>b.choices[0].message.tool_calls[0].function.arguments='{"deal_id":"other"}',b=>b.choices[0].finish_reason='length',b=>b.model='wrong-model']){const body=structuredClone(answer);change(body);const records=[],c=new KilnClient({model:'organizer-model',key:'test',fetchImpl:async()=>Response.json(body),onRecord:r=>records.push(r)});await assert.rejects(c.call('selection','Buyer',{deal_id:'deal-1'},'accept_deal'));assert.equal(records.length,1);assert.notEqual(records[0].result,'VALID_TOOL_PROPOSAL');}});
test('network and invalid model listing never invent usage',async()=>{const records=[],c=new KilnClient({model:'organizer-model',key:'test',fetchImpl:async()=>{throw new Error('NETWORK_FAILED');},onRecord:r=>records.push(r)});await assert.rejects(c.call('selection','Buyer',{deal_id:'deal-1'},'accept_deal'));assert.equal(records[0].total_tokens,null);const missing=new KilnClient({model:'organizer-model',key:'test',fetchImpl:async()=>Response.json({data:[{id:'different'}]})});await assert.rejects(missing.models(),/UNAVAILABLE/);});

test('provider cost is copied only when reported; a missing currency or cost stays unknown',async()=>{
 for(const usage of [{...answer.usage,cost:.001},{...answer.usage,cost:.002,cost_currency:'USD'},answer.usage]){
  const records=[],c=new KilnClient({model:'organizer-model',key:'test',fetchImpl:async()=>Response.json({...answer,usage}),onRecord:r=>records.push(r)});
  await c.call('selection','Buyer',{deal_id:'deal-1'},'accept_deal');assert.equal(records[0].provider_reported_cost,usage.cost??null);assert.equal(records[0].provider_cost_unit,usage.cost_currency??null);
 }
});
