import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Wallet} from 'ethers';
import {startChain} from '../src/chain.mjs';
import {Store} from '../src/store.mjs';
import {Engine} from '../src/engine.mjs';
import {checkOffer,reserve,startSubmission,stopLocally} from '../src/policy.mjs';
import {verifyBundle} from '../src/verifier.mjs';
import {MANDATE_TYPES,REVOKE_TYPES,hash,nowSeconds,scopeKey,PURPOSE} from '../shared/schema.mjs';
let chain,temp;
before(async()=>{temp=await mkdtemp(path.join(os.tmpdir(),'cm-engine-test-'));chain=await startChain({directory:temp,port:18545,persist:false});});
after(async()=>{await chain?.close();if(temp&&path.resolve(temp).startsWith(path.resolve(os.tmpdir())+path.sep))await rm(temp,{recursive:true,force:true});});
class FixtureModel {
  calls=0;
  async call({flow,candidates,tool='propose_purchase',onUsage,maxTotal}){this.calls++;onUsage?.({flow,model:'OFFLINE_TEST_FIXTURE',promptTokens:null,completionTokens:null,totalTokens:null,costUsd:null,generationId:null,latencyMs:0,outcome:'MOCK_RESPONSE'});const chosen=candidates.find(x=>x.seller==='beta')??candidates[0];return {tool,model:'OFFLINE_TEST_FIXTURE',args:{offer_id:chosen.id,reason:'Deterministic test fixture',...(tool==='request_counteroffer'?{total_minor:Number(maxTotal)}:{})}};}
}
async function setup(options={}){const store=new Store(':memory:'),kiln=new FixtureModel(),engine=new Engine({store,chain,kiln}),owner=Wallet.createRandom();const draft=await engine.draft(owner.address,options);const signature=await owner.signTypedData(chain.domain,MANDATE_TYPES,draft.value);await engine.approve(draft.session.id,signature);return {store,kiln,engine,owner,id:draft.session.id};}
async function run(ctx,scenarioId){const r=ctx.engine.enqueue(ctx.id,{scenarioId});await ctx.engine.wait(r.id);return ctx.store.get('run',r.id);}
async function offer(ctx,total='2000',merchant='alpha',overrides={}){const s=ctx.engine.session(ctx.id);return chain.signOffer(merchant,{sessionId:ctx.id,offerId:hash({nonce:Math.random().toString()}),merchant:chain.merchant(merchant).address,purposeHash:s.mandate.purposeHash,skuHash:s.mandate.skuHash,quantity:'100',refundHours:'24',subtotal:total,fee:'0',total,expiresAt:String(nowSeconds()+600),...overrides});}

test('fees are blocked after the proposal; evidence activates only a scoped early gate',async()=>{const c=await setup();const first=await run(c,'hidden-fee');assert.equal(first.status,'STOPPED');assert.equal(first.reason,'PER_PURCHASE_LIMIT_EXCEEDED');assert.equal(c.kiln.calls,1);assert.equal(c.store.all('control').length,1);const second=await run(c,'hidden-fee');assert.equal(second.status,'STOPPED');assert.equal(second.usage.length,0);assert.equal(second.controls.length,1);assert.equal(await chain.vault.spent(c.id),0n);assert.equal(c.store.get('control',scopeKey(Wallet.createRandom().address,PURPOSE,chain.merchant('beta').address)),null);c.store.close();});
test('normal purchase transfers real devnet TestCredit and independently verifies',async()=>{const c=await setup();const r=await run(c,'normal');assert.equal(r.status,'SETTLED');assert.equal(r.receipt.status,1);assert.equal(await chain.vault.spent(c.id),800n);const b=c.engine.bundle(r.id);const verifier={provider:chain.provider,deployment:chain.deployment,abi:chain.artifacts.vault.abi};assert.equal((await verifyBundle(b,verifier)).status,'VALID');const changed=structuredClone(b);changed.run.offer.offer.total='1';assert.equal((await verifyBundle(changed,verifier)).status,'INVALID');const missing=structuredClone(b);delete missing.preEvidence;assert.equal((await verifyBundle(missing,verifier)).status,'INCOMPLETE');assert.equal((await verifyBundle(b)).status,'INCOMPLETE');c.store.close();});
test('unknown merchant and expired quote stop without settlement',async()=>{const c=await setup();const outsider=await run(c,'unlisted');assert.equal(outsider.reason,'MERCHANT_NOT_ALLOWED');assert.equal(outsider.usage.length,0);const expired=await run(c,'expired');assert.equal(expired.reason,'OFFER_EXPIRED');assert.equal(await chain.vault.spent(c.id),0n);c.store.close();});
test('changed amount, purpose, signature and deadline cannot cross policy',async()=>{const c=await setup({totalCap:'3000',perTxCap:'3000'});const good=await offer(c);const s=c.engine.session(c.id);assert.equal(checkOffer(s,good,chain.domain).allowed,true);const tampered=structuredClone(good);tampered.offer.total='100';assert.equal(checkOffer(s,tampered,chain.domain).allowed,false);const purpose=await offer(c,'2000','alpha',{purposeHash:hash('wrong purpose')});assert.equal(checkOffer(s,purpose,chain.domain).reason,'PURPOSE_MISMATCH');assert.equal(checkOffer(s,good,chain.domain,{now:Number(s.mandate.expiresAt)}).reason,'DEADLINE_EXPIRED');c.store.close();});
test('atomic reservations reject 20+20 against 30, then stop releases only unsubmitted funds',async()=>{const c=await setup({totalCap:'3000',perTxCap:'3000'});const a=await offer(c),b=await offer(c);for(const id of ['one','two'])c.store.put('run',id,{id,sessionId:c.id,status:'RUNNING'});reserve(c.store,c.id,'one',a,chain.domain);assert.throws(()=>reserve(c.store,c.id,'two',b,chain.domain),/ALL_IN_BUDGET_EXCEEDED/);stopLocally(c.store,c.id);assert.equal(c.engine.session(c.id).reserved,'0');assert.throws(()=>startSubmission(c.store,'one',{hash:hash('tx'),raw:'0x',nonce:0}),/STOPPED_BEFORE_SUBMISSION/);c.store.close();});
test('contract rejects bypassed budget, merchant, replay and revoked mandate',async()=>{const c=await setup();const high=await offer(c,'1200');await assert.rejects(()=>chain.vault.executePayment.staticCall(high.offer,high.signature,hash('high'),hash('e')),/BUDGET_EXCEEDED/);const bad=await offer(c,'100','outsider');await assert.rejects(()=>chain.vault.executePayment.staticCall(bad.offer,bad.signature,hash('bad'),hash('e')),/MERCHANT_NOT_ALLOWED/);const r=await run(c,'normal');await assert.rejects(()=>chain.vault.executePayment.staticCall(r.offer.offer,r.offer.signature,r.paymentKey,r.evidenceHash),/DUPLICATE_PAYMENT/);const sig=await c.owner.signTypedData(chain.domain,REVOKE_TYPES,{sessionId:c.id,owner:c.owner.address});await c.engine.stop(c.id,sig);const fresh=await offer(c,'100');await assert.rejects(()=>chain.vault.executePayment.staticCall(fresh.offer,fresh.signature,hash('new'),hash('e')),/MANDATE_INACTIVE/);c.store.close();});
test('lost receipt retains reservation; restart recovers same transaction exactly once',async()=>{const c=await setup();const original=chain.broadcast;let interrupted=true;chain.broadcast=async tx=>{const receipt=await original(tx);if(interrupted){interrupted=false;throw new Error('simulated lost receipt');}return receipt;};try{const r=await run(c,'normal');assert.equal(r.status,'UNKNOWN');assert.equal(c.engine.session(c.id).reserved,'800');await c.engine.recover();await c.engine.recover();assert.equal(c.store.get('run',r.id).status,'SETTLED');assert.equal(c.engine.session(c.id).spent,'800');assert.equal(c.engine.session(c.id).reserved,'0');assert.equal(await chain.vault.spent(c.id),800n);}finally{chain.broadcast=original;c.store.close();}});
test('stop during inference prevents subsequent reservation and payment',async()=>{const c=await setup();let release;const wait=new Promise(r=>release=r);const original=c.kiln.call.bind(c.kiln);c.kiln.call=async args=>{await wait;return original(args);};const r=c.engine.enqueue(c.id,{scenarioId:'normal'});await new Promise(r=>setTimeout(r,20));const sig=await c.owner.signTypedData(chain.domain,REVOKE_TYPES,{sessionId:c.id,owner:c.owner.address});await c.engine.stop(c.id,sig);release();await c.engine.wait(r.id);assert.equal(c.store.get('run',r.id).reason,'USER_REVOKED');assert.equal(await chain.vault.spent(c.id),0n);c.store.close();});
test('a corrected seller remains usable under an existing restriction',async()=>{const c=await setup();await run(c,'hidden-fee');const r=await run(c,'reformed');assert.equal(r.status,'SETTLED');assert.equal(r.offer.offer.total,'600');assert.equal(r.controls.length,1);assert.equal(c.store.all('control')[0].status,'ACTIVE');c.store.close();});
test('legacy per-purchase failure remains provable without inventing cumulative balances',async()=>{const c=await setup(),event=c.store.event.bind(c.store);c.store.event=(session,type,data,runId)=>{if(type==='POLICY_BLOCKED'){data={...data};delete data.policyContext;}return event(session,type,data,runId);};await run(c,'hidden-fee');const paid=await run(c,'reformed');const report=await verifyBundle(c.engine.bundle(paid.id),{provider:chain.provider,deployment:chain.deployment,abi:chain.artifacts.vault.abi});assert.equal(report.status,'VALID',report.reason);c.store.close();const other=await setup({totalCap:'1000'}),original=other.store.event.bind(other.store);other.store.event=(session,type,data,runId)=>{if(type==='POLICY_BLOCKED'){data={...data};delete data.policyContext;}return original(session,type,data,runId);};await run(other,'normal');assert.equal((await run(other,'reformed')).reason,'ALL_IN_BUDGET_EXCEEDED');const blocked=await run(other,'reformed');const missing=await verifyBundle(other.engine.bundle(blocked.id));assert.equal(missing.status,'INCOMPLETE');assert.equal(missing.reason,'CONTROL_SOURCE_CONTEXT_MISSING');other.store.close();});
test('same request is idempotent and caller cannot modify owner approval',async()=>{const c=await setup();const a=c.engine.enqueue(c.id,{scenarioId:'normal',requestId:'stable'});const b=c.engine.enqueue(c.id,{scenarioId:'hidden-fee',requestId:'stable'});assert.equal(a.id,b.id);await c.engine.wait(a.id);assert.equal(c.store.all('run').length,1);const d=await c.engine.draft(c.owner.address);const wrong=await Wallet.createRandom().signTypedData(chain.domain,MANDATE_TYPES,d.value);await assert.rejects(()=>c.engine.approve(d.session.id,wrong),/OWNER_SIGNATURE/);c.store.close();});
test('lost approval receipt recovers one on-chain approval after restart',async()=>{const store=new Store(':memory:'),engine=new Engine({store,chain,kiln:new FixtureModel()}),owner=Wallet.createRandom();const d=await engine.draft(owner.address);const signature=await owner.signTypedData(chain.domain,MANDATE_TYPES,d.value),original=chain.create;chain.create=async(...args)=>{await original(...args);throw new Error('lost approval response');};try{await assert.rejects(()=>engine.approve(d.session.id,signature));assert.equal(engine.session(d.session.id).status,'AWAITING_APPROVAL');}finally{chain.create=original;}await engine.recover();await engine.recover();assert.equal(engine.session(d.session.id).status,'ACTIVE');assert.equal(await chain.vault.nonces(owner.address),1n);assert.equal(store.events(d.session.id).filter(e=>e.type==='HUMAN_APPROVED').length,1);store.close();});
test('stop racing an approval receipt never reactivates the mandate',async()=>{const store=new Store(':memory:'),engine=new Engine({store,chain,kiln:new FixtureModel()}),owner=Wallet.createRandom();const d=await engine.draft(owner.address);const signature=await owner.signTypedData(chain.domain,MANDATE_TYPES,d.value),original=chain.create;let release,entered;const barrier=new Promise(r=>release=r),inside=new Promise(r=>entered=r);chain.create=async(...args)=>{const receipt=await original(...args);entered();await barrier;return receipt;};try{const approving=engine.approve(d.session.id,signature);await inside;const revocation=await owner.signTypedData(chain.domain,REVOKE_TYPES,{sessionId:d.session.id,owner:owner.address});await engine.stop(d.session.id,revocation);release();await approving;assert.equal(engine.session(d.session.id).status,'STOPPED');assert.equal(await chain.vault.active(d.session.id),false);assert.throws(()=>engine.enqueue(d.session.id),/MANDATE_INACTIVE/);}finally{chain.create=original;release?.();store.close();}});
