const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let token='',busy=false,rendered='';
const money=n=>(Number(n??0)/100).toFixed(2)+' DEMO';const wei=n=>money(BigInt(n??0)/1000000000n);
async function api(path,body){const r=await fetch('/api/'+path,{...(body===undefined?{}:{method:'POST',headers:{'content-type':'application/json','x-dealtrace-token':token},body:JSON.stringify(body)})});const v=await r.json();if(!r.ok)throw Error(v.error??'Request failed');return v;}
function fill(id,nodes){$(id).replaceChildren(...nodes);}function line(label,value){const n=el('div',undefined,'termrow');n.append(el('span',label),el('strong',value));return n;}
function render(r){
 if(!r)return;const n=r.negotiation,p=r.plan;$('#status').textContent=`${r.status} · ${r.stage??''} · ${r.mode} · ${r.network?.chainId===11155111?'Sepolia':'Local EVM'}`;
 const values=[['Human budget',money(r.rfq?.budget_minor),'Authorized ceiling'],['Committed maximum',p?wei(p.deal.amount):'—','Bilateral agreement'],['Seller received',r.paid_wei?wei(r.paid_wei):'—','After withdrawal'],['Unused returned',r.refunded_wei?wei(r.refunded_wei):'—','Failed units are not billed']];
 fill('#metrics',values.map(([label,value,note])=>{const e=el('div',undefined,'metric');e.append(el('span',label),el('strong',value),el('span',note));return e;}));
 fill('#providers',(n?.providers??[]).map(provider=>{const s=n.sessions[provider.id],q=s?.events?.at(-1)?.body.quote,selected=n.selection===provider.id,e=el('div',undefined,'provider'+(selected?' selected':''));e.append(el('strong',provider.id),el('div',q?money(q.items.reduce((sum,i)=>sum+i.units*i.unit_price_minor,0)):'—','price'),el('span',selected?'SELECTED':s?.reason??'WAITING','badge'+(s?.reason!=='ELIGIBLE'&&!selected?' blocked':'')),el('p',q?`${q.delivery_seconds}s · ${q.quality}`:'','muted'),el('div',provider.address,'hash'));return e;}));
 const events=n?.sessions[n.selection]?.events??[];fill('#conversation',events.map(e=>{const q=e.body.quote,box=el('article',undefined,'message '+e.body.role);box.id='event-'+e.body.sequence;box.append(el('h3',`${e.body.role.toUpperCase()} · message ${e.body.sequence}`),el('p',q.message),el('div',q.items.map(i=>`${i.service}: ${i.units} × ${money(i.unit_price_minor)}`).join(' · '),'terms'),el('div',`${q.delivery_seconds} seconds · ${q.quality}`,'terms'));return box;}));
 const terms=[];if(p){terms.push(line('Buyer signature',p.buyerSignature?'Confirmed':'Pending'),line('Seller signature',p.sellerSignature?'Confirmed':'Pending'));
  for(const [field,value] of [['items',p.packet.terms.items.map(i=>`${i.service} × ${i.units} @ ${money(i.unit_price_minor)}`).join(' / ')],['delivery_seconds',`${p.deal.deliveryWindow}s after funding`],['quality',p.packet.terms.quality]]){const row=line(field,value),button=el('button','View source','jump');button.onclick=()=>{const event=[...p.packet.events].reverse().find(e=>JSON.stringify(e.body.quote[field])===JSON.stringify(p.packet.provenance[field].value));const box=$('#event-'+event?.body.sequence);if(box){box.scrollIntoView({behavior:'smooth',block:'center'});box.classList.add('highlight');setTimeout(()=>box.classList.remove('highlight'),2000);}};row.append(button);terms.push(row);}terms.push(el('div',p.deal.dealHash,'hash'));}
 if(r.error)terms.push(el('p',r.error,'notice'));if(r.claims)terms.push(el('p',`Overbill ${wei(r.claims.bad.amount)} rejected. Verified bill ${wei(r.claims.correct.amount)}.`, 'notice'));fill('#deal',terms);
 fill('#units',(r.units??[]).map(u=>line(`${u.body.service} #${u.body.index+1}`,u.body.status==='SUCCESS'?'Verified success':'Failed · 0 charge')));
 fill('#chain',(r.transactions??[]).map(t=>{const row=el('div',undefined,'tx'),link=el(r.network?.chainId===11155111?'a':'span',t.tx_hash);if(link.tagName==='A'){link.href='https://sepolia.etherscan.io/tx/'+t.tx_hash;link.target='_blank';link.rel='noopener';}row.append(el('strong',`${t.label} · ${t.status===1?'confirmed':'reverted'}`),link);return row;}));
 const flows=new Map();for(const u of r.usage??[]){const f=flows.get(u.flow_name)??{calls:0,input:0,output:0,unknown:0};f.calls++;if(u.prompt_tokens==null||u.completion_tokens==null)f.unknown++;else{f.input+=u.prompt_tokens;f.output+=u.completion_tokens;}flows.set(u.flow_name,f);}fill('#usage',[...flows].map(([name,v])=>line(name,`${v.calls} calls · ${v.input} in / ${v.output} out${v.unknown?' · usage unavailable for '+v.unknown:''}`)).concat((r.limits??[]).map(s=>el('p',s,'muted'))));
 if(!r.verification)$('#verification').textContent='';
 if(r.verification)$('#verification').textContent=`Saved run: ${r.verification.verdict} · ${r.verification.checks} checks · ${r.verification.block_tag} block ${r.verification.block}`;
}
async function poll(){try{const s=await api('state');token=s.token;busy=!!s.job?.running;$('#run').disabled=busy;$('#stop').disabled=!busy;$('#history').disabled=busy;$('#live').disabled=!s.live_available;if(!s.live_available)$('#live').checked=false;const key=JSON.stringify([s.report?.run,s.report?.stage,s.report?.status,s.report?.transactions?.length,s.report?.model_calls,s.report?.units?.length]);if(key!==rendered){render(s.report);rendered=key;}if(!s.report)$('#status').textContent='Ready · approve a test job to begin';}catch(e){$('#status').textContent=e.message;}}
$('#run').onclick=async()=>{try{const budget=Math.round(Number($('#budget').value)*100);await api('run',{approved:$('#approve').checked,live:$('#live').checked,metered:$('#package').value==='metered',publicNetwork:$('#public').checked,budget});rendered='';$('#verification').textContent='';await poll();}catch(e){$('#status').textContent=e.message;}};
$('#stop').onclick=async()=>{try{await api('stop',{});$('#status').textContent='Stop requested. Already submitted transactions remain observable.';}catch(e){$('#status').textContent=e.message;}};
for(const [id,tamper] of [['#verify',false],['#tamper',true]])$(id).onclick=async()=>{try{$('#verification').textContent='Checking original messages, signatures, usage and chain…';const v=await api('verify',{tamper});$('#verification').textContent=`${v.verdict} · ${v.checks} checks${v.reason?' · '+v.reason:''}`;}catch(e){$('#verification').textContent=e.message;}};
$('#history').onchange=async e=>{if(e.target.value){await api('select',{run:e.target.value});rendered='';await poll();}};
await poll();const h=await api('history');for(const r of h.runs){const option=el('option',`${r.status} · ${r.mode} · ${r.run.slice(0,8)}`);option.value=r.run;$('#history').append(option);}setInterval(poll,1500);
