import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
export function render(report){
  const data={id:report.id,kind:report.kind,status:report.status,analysisVersion:report.analysisVersion??null,modelSafety:report.modelSafety??null,actualApiCalls:report.actualApiCalls,byArm:report.byArm,sellerBatches:report.sellerBatches.map(b=>({mode:b.mode,wallTimeMs:b.wallTimeMs,errors:b.errors,sellers:b.sellers})),rows:[...report.rows,...report.robustnessRows].map(r=>({runId:r.runId,family:r.family,arm:r.arm,status:r.status,reason:r.reason,expectedPayable:r.expectedPayable,unsafe:r.unsafeAcceptAttempts,caught:r.caughtUnsafeAccepts,violations:r.unauthorizedAuthorizations,calls:r.usage.length,tokens:r.usage.every(u=>u.totalTokens!==null)?r.usage.reduce((n,u)=>n+u.totalTokens,0):null,steps:r.steps,usage:r.usage.map(({request,response,...u})=>u),events:r.events,quotes:r.quotes}))};
  return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Qwen Safety Harness · Evaluation</title><style>
  :root{color-scheme:dark;font-family:Inter,"Segoe UI",sans-serif;background:#0b1220;color:#e4edf6}*{box-sizing:border-box}body{max-width:1320px;margin:auto;padding:36px 26px}h1{font-size:34px;letter-spacing:-1px;margin:12px 0}h2{font-size:20px}p{color:#adbed0;line-height:1.65}.eyebrow{color:#68ddc1;font-weight:600;letter-spacing:2px;font-size:12px}.badge{font:12px monospace;border:1px solid #41536c;border-radius:16px;padding:5px 10px}header{border-bottom:1px solid #29364a;padding-bottom:22px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:22px 0}.card{background:#131e30;border:1px solid #293c53;border-radius:15px;padding:22px}.big{font-size:36px;font-weight:650;color:#7ce4cb}.label{color:#93a9bd;font-size:13px}.pairs{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:18px}.metric{padding:9px 0}.metric b{display:block;margin-top:4px;font-size:19px}.bar{height:7px;background:#30475b;border-radius:4px;margin-top:8px;overflow:hidden}.bar i{display:block;height:100%;background:#58b9ff}.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:20px 0}select,input,button{background:#17263b;color:#e1ebf3;border:1px solid #41516b;border-radius:8px;padding:10px;font:inherit}input{flex:1;min-width:200px}button{cursor:pointer}.tablewrap{overflow:auto;border:1px solid #2d3b52;border-radius:12px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:13px 14px;border-bottom:1px solid #233147}th{background:#172236;color:#adbed0}tr:hover{background:#192941}.good{color:#74dec4}.warn{color:#ffca7c}.bad{color:#ff91a2}dialog{width:min(980px,95vw);max-height:90vh;background:#111d2d;border:1px solid #465a72;border-radius:16px;color:#dbe7f2;padding:24px}dialog::backdrop{background:#000b}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#09121f;padding:16px;border-radius:8px;max-height:400px;overflow:auto;font-size:12px}.right{float:right}.note{border-left:3px solid #58b9ff;padding:10px 16px;background:#111f31;font-size:13px}footer{font-size:12px;margin-top:28px;color:#8c9fb4}@media(max-width:760px){.cards{grid-template-columns:1fr}body{padding:22px 14px}h1{font-size:26px}}
  </style><header><div class="eyebrow">INTELLIGENCE / SAFETY / EVALUATION</div><h1>Qwen Agent Safety Harness</h1><p>모델의 선택과 시스템의 승인 결과를 따로 봅니다. 판매자 조건이 바뀌어도 승인 범위가 유지되는지, 얼마나 많은 추론이 필요한지 확인합니다.</p><span class="badge" id="run"></span></header>
  <div class="cards" id="cards"></div><div class="note">금융 결과는 제품 정책·예약 코드를 통과한 <b>모의 승인</b>입니다. 실제 결제 건수는 0건입니다. TTFT는 클라이언트의 첫 유효 delta 도착 시간이며 NPU 전력·장치 처리량을 뜻하지 않습니다. API 오류와 턴 제한은 성공에서 제외합니다.</div>
  <h2>직렬·병렬 판매자 추론</h2><div id="batches"></div><h2>거래별 도구 호출과 차단 근거</h2>
  <div class="controls"><label>비교군 <select id="arm"><option value="">전체</option><option>B0</option><option>B1</option><option>CM</option></select></label><label>시나리오 <select id="family"><option value="">전체</option></select></label><input id="search" aria-label="결과 검색" placeholder="거래 ID, 결과, 중지 사유 검색"><span id="count"></span></div>
  <div class="tablewrap"><table><thead><tr><th>거래</th><th>군 / 시나리오</th><th>결과</th><th>호출 / 토큰</th><th>위험 수락 / 차단</th><th>기록</th></tr></thead><tbody id="rows"></tbody></table></div>
  <dialog id="detail"><button id="close" class="right">닫기</button><h2 id="detail-title"></h2><p id="detail-reason"></p><h3>도구 실행</h3><pre id="steps"></pre><h3>흐름별 측정</h3><pre id="usage"></pre><h3>서명 견적과 이벤트</h3><pre id="evidence"></pre></dialog>
  <footer>실험은 고정된 합성 구매 조건과 비결정적 판매자 테스트에 한정됩니다. 일반적 무사고 보장이나 Control Memory의 보편적 우월성을 주장하지 않습니다. 원본 report.json과 실행 코드 source/를 함께 보관하세요.</footer>
  <script id="data" type="application/json">${JSON.stringify(data).replaceAll('<','\\u003c')}</script><script>
  const d=JSON.parse(document.getElementById('data').textContent),el=id=>document.getElementById(id),fmt=n=>n==null?'미측정':new Intl.NumberFormat('ko-KR',{maximumFractionDigits:1}).format(n),pct=r=>r.value==null?'—':fmt(r.value*100)+'%';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const incomplete=d.rows.filter(r=>['INCOMPLETE','RESOURCE_STOP'].includes(r.status)).length;
  el('run').textContent=d.kind+' · '+d.id+' · 실제 API '+d.actualApiCalls+'회 · 불완전 '+incomplete+'건'+(d.analysisVersion?' · 채점 v'+d.analysisVersion:'');
  const labels={B0:'기본 검사',B1:'모든 판매자 조기 검사',CM:'실패 범위에 조기 검사'};
  el('cards').innerHTML=Object.entries(d.byArm).map(([arm,s])=>'<article class="card"><span class="label">'+arm+' / '+labels[arm]+'</span><div class="big">'+fmt(s.unauthorizedAuthorizations)+'</div><div class="label">권한 밖 모의 승인 · '+s.rows+'회 평가</div><div class="pairs"><div class="metric">정상 구매 성공<b>'+pct(s.normalSuccessRate)+'</b></div><div class="metric">공격 안전 해결<b>'+pct(s.attackSafeResolutionRate)+'</b></div><div class="metric">호출 / 토큰<b>'+fmt(s.calls)+' / '+fmt(s.totalTokens)+'</b></div><div class="metric">TTFT p50 / p95<b>'+fmt(s.ttftMs.p50)+' / '+fmt(s.ttftMs.p95)+' ms</b></div><div class="metric">위험 수락 → 차단<b>'+s.unsafeAcceptAttempts+' → '+s.policyCaughtUnsafeAccepts+'</b></div><div class="metric">형식 오류 / 불완전<b>'+s.invalidToolRate.numerator+' / '+s.incomplete+'</b></div></div><div class="label">Fixture 도구 정확도 '+pct(s.toolAccuracy)+'</div><div class="bar"><i style="width:'+((s.toolAccuracy.value??0)*100)+'%"></i></div></article>').join('');
  el('batches').innerHTML=d.sellerBatches.length?'<p>'+d.sellerBatches.map(b=>esc(b.mode)+' '+fmt(b.wallTimeMs)+' ms · 유효 판매자 '+b.sellers.length+'/3 · 오류 '+b.errors.length).join('<br>')+'</p>':'<p>오프라인 실행: 판매자 API 측정 없음</p>';
  for(const f of new Set(d.rows.map(r=>r.family))){const o=document.createElement('option');o.value=f;o.textContent=f;el('family').append(o);}
  function draw(){const term=el('search').value.toLowerCase(),rs=d.rows.filter(r=>(!el('arm').value||r.arm===el('arm').value)&&(!el('family').value||r.family===el('family').value)&&JSON.stringify([r.runId,r.status,r.reason]).toLowerCase().includes(term));el('count').textContent=rs.length+'개';el('rows').innerHTML=rs.map(r=>'<tr><td>'+esc(r.runId)+'</td><td>'+esc(r.arm)+' / '+esc(r.family)+'</td><td class="'+(r.violations?'bad':r.status==='AUTHORIZED_SIMULATION'?'good':'warn')+'">'+esc(r.status)+'<br><small>'+esc(r.reason)+'</small></td><td>'+r.calls+' / '+fmt(r.tokens)+'</td><td>'+r.unsafe+' / '+r.caught+'</td><td><button data-id="'+esc(r.runId)+'">기록 보기</button></td></tr>').join('');}
  for(const id of ['arm','family','search'])el(id).addEventListener('input',draw);
  el('rows').addEventListener('click',e=>{const id=e.target.dataset.id;if(!id)return;const r=d.rows.find(r=>r.runId===id);el('detail-title').textContent=id;el('detail-reason').textContent=r.status+' · '+r.reason;el('steps').textContent=JSON.stringify(r.steps,null,2);el('usage').textContent=JSON.stringify(r.usage,null,2);el('evidence').textContent=JSON.stringify({quotes:r.quotes,events:r.events},null,2);el('detail').showModal();});el('close').onclick=()=>el('detail').close();draw();
  </script></html>`;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
  const input=process.argv[2];if(!input)throw new Error('REPORT_PATH_REQUIRED');const report=JSON.parse(await readFile(input,'utf8'));const out=path.join(path.dirname(input),'dashboard.html');await writeFile(out,render(report));console.log(out);
}
