import {parseSource,csv,normalizeRows} from './workspace-model.mjs';
import {renderWorkspace,briefForm,esc as e,amount,button} from './workspace-view.mjs';
import {request,executionMode} from './workspace-client.mjs';
const $=s=>document.querySelector(s),empty={title:'',brief:'',budget:40,perDeal:30,deliveryMinutes:10};
let proof=null;
let token='',network=null,tasks=[],job=null,busy=false,present=false,route='workspace',sourceText='',sourceName='',lastFocus=null,draft={...empty};
window.addEventListener('accord-operation-progress',event=>{if(busy&&$('#operation'))$('#operation').textContent=event.detail;});
async function api(url,body){return request(url,body,token);}
function announce(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>{$('#toast').hidden=true;},5500);}
function showError(message){const box=$('#error');if(box){box.textContent=message;box.hidden=false;box.scrollIntoView({block:'nearest'});}else announce(message);}
async function refreshList(){const state=await api('/api/workspace');token=state.token;network=state.network;tasks=state.tasks;}
async function operate(label,fn){if(busy)return;busy=true;const bar=$('#operation');bar.textContent=label;bar.hidden=false;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();await refreshList();render();}catch(err){if(job){try{job=await api('/api/tasks/'+job.id);}catch{}}render();showError(err.message);}finally{busy=false;}}
async function mutate(action,fields={}){job=await api(`/api/tasks/${job.id}/${action}`,{revision:job.revision,...fields});}
function captureDraft(form=$('#brief-form')){if(form){const d=new FormData(form);draft={demoMode:draft.demoMode===true,title:d.get('title'),brief:d.get('brief'),budget:Number(d.get('budget')),perDeal:Number(d.get('perDeal')),deliveryMinutes:Number(d.get('deliveryMinutes'))};}}
function render(){document.body.classList.toggle('presentation-mode',present);$('#app').innerHTML=renderWorkspace({job,tasks,route,present,network,proof,draft,sourceText,sourceName});if(!job&&route==='workspace')bindForm();$('#counter-form')?.addEventListener('submit',ev=>{ev.preventDefault();operate('Sending your counteroffer…',()=>mutate('counter',{price:Number(new FormData(ev.currentTarget).get('price'))}));});$('#invoice-form')?.addEventListener('submit',ev=>{ev.preventDefault();const n=Number(new FormData(ev.currentTarget).get('amount'));operate('Checking the invoice against the agreement…',()=>mutate('invoice',{amount:n}));});}
function bindFile(scope=document){scope.querySelector('#source-file')?.addEventListener('change',async ev=>{const form=scope.querySelector('#brief-form');captureDraft(form);try{const file=ev.target.files[0];if(!file)return;if(file.size>1_000_000)throw Error('Choose a file smaller than 1 MB.');const raw=await file.text();parseSource(raw);draft.demoMode=false;sourceText=raw;sourceName=file.name;scope.querySelector('#source-name').textContent=sourceName;scope.querySelector('#source-count').textContent=`${parseSource(raw).length} rows · stored on this computer`;}catch(err){announce(err.message);}});}
function bindForm(){bindFile();$('#brief-form').addEventListener('submit',ev=>{ev.preventDefault();captureDraft();if(!sourceText){showError('Choose a source file, or use the sample task.');return;}const spec={...draft,sourceText,sourceName};operate('Saving your task and source table…',async()=>{job=await api('/api/tasks',spec);history.replaceState(null,'',`#task/${job.id}`);});});}
function modal(html){lastFocus=document.activeElement;$('#dialog-content').innerHTML=`<button class="dialog-close" data-close aria-label="Close dialog">×</button>${html}`;$('#detail').showModal();}
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function newTask(sample=false){job=null;draft={...empty};sourceText='';sourceName='';route='workspace';if(sample){present=true;const s=await api('/api/sample');draft=s;sourceText=s.sourceText;sourceName=s.sourceName;}history.replaceState(null,'','#workspace');}
function showEdit(){draft={...job};sourceText=JSON.stringify(job.source,null,2);sourceName=job.sourceName;modal(briefForm({draft,sourceText,sourceName},true));bindFile($('#detail'));$('#detail #brief-form').addEventListener('submit',ev=>{ev.preventDefault();captureDraft(ev.currentTarget);const fields={...draft,sourceText,sourceName};$('#detail').close();operate('Updating your brief…',()=>mutate('edit',fields));});}
document.addEventListener('click',async ev=>{
 if(ev.target.closest('[data-close]')){$('#detail').close();return;}
 const selected=ev.target.closest('[data-select]');if(selected&&!busy){await operate('Selecting this offer…',()=>mutate('select',{seller:selected.dataset.select}));return;}
 const task=ev.target.closest('[data-job]');if(task&&!busy){$('#detail').close();await operate('Opening task…',async()=>{job=await api('/api/tasks/'+task.dataset.job);route='workspace';history.replaceState(null,'',`#task/${job.id}`);});return;}
 const source=ev.target.closest('[data-source]');if(source&&job){const row=(job.output??job.source)[Number(source.dataset.source)]??{};const original=job.source[normalizeRows(job.source).findIndex(r=>r.quarter===row.quarter&&r.company===row.company)]??{};let url;try{const p=new URL(row.source_url);if(['http:','https:'].includes(p.protocol)&&!p.username&&!p.password)url=p.href;}catch{}modal(`<span class="eyebrow">ROW EVIDENCE</span><h2>${e(row.company)} · ${e(row.quarter)}</h2><div class="source-comparison"><div><span>Source value</span><strong>${e(original.capex)} ${e(original.unit)} ${e(original.currency)}</strong></div><div><span>Delivered value</span><strong>${e(row.capex)} ${e(row.unit)} ${e(row.currency)}</strong></div></div><p class="hash">${e(row.source_url||'No source URL provided.')}</p>${url?`<a class="button primary" target="_blank" rel="noopener noreferrer" href="${e(url)}">Open original source ↗</a>`:''}<p class="trust-note">A preserved citation is not an independent certification of the source's accuracy.</p>`);return;}
 const tx=ev.target.closest('[data-tx]');if(tx){const item=job.transactions.find(x=>x.kind===tx.dataset.tx);modal(`<span class="eyebrow">LOCAL EVM RECEIPT</span><h2>${item.kind==='fund'?'Escrow funding':item.kind==='release'?'Seller payment':'Buyer refund'}</h2><dl><dt>Amount</dt><dd>${amount(item.amount)}</dd><dt>Status</dt><dd>${e(item.status)}</dd><dt>Transaction</dt><dd class="hash">${e(item.hash)}</dd><dt>Block</dt><dd>${item.block??'Pending'}</dd><dt>Contract</dt><dd class="hash">${e(network.contract)}</dd></dl><p>Chain ${network.chainId}. Local transactions have no public explorer URL.</p>`);return;}
 const name=ev.target.closest('[data-action]')?.dataset.action;if(!name||busy)return;
 if(name==='tasks'){modal(`<span class="eyebrow">SAVED ON THIS COMPUTER</span><h2>Your tasks</h2>${tasks.length?tasks.map(t=>`<button class="task-item" data-job="${t.id}"><span>${e(t.title)}<small>${e(t.status)}</small></span></button>`).join(''):'<p>Create a task to start your work history.</p>'}`);return;}
 if(name==='new'||name==='sample'){await operate('Preparing your task…',()=>newTask(name==='sample'));return;}
 if(name==='correct-invoice'){await operate('Checking the corrected invoice…',()=>mutate('invoice',{amount:job.agreedPrice}));return;}
 if(name==='present'){captureDraft();present=!present;route='workspace';render();return;}
 if(name==='template'){download('accord-source-template.csv',csv([{company:'Example company',quarter:'2025-Q1',capex:100,currency:'USD',source_url:'https://example.com/source'}]),'text/csv');return;}
 if(name==='edit'){showEdit();return;}
 if(name==='delivery'){modal(`<span class="eyebrow">SELLER DELIVERY</span><h2>Inspect or replace the result</h2><p>Changing a value or removing a citation runs the same acceptance checks again.</p><form id="delivery-form"><label for="delivery-json">Delivery JSON</label><textarea id="delivery-json" rows="13">${e(JSON.stringify(job.output,null,2))}</textarea><button class="button primary" type="submit">Validate replacement</button></form>`);$('#delivery-form').onsubmit=ev=>{ev.preventDefault();const raw=$('#delivery-json').value;$('#detail').close();operate('Validating the replacement delivery…',()=>mutate('delivery',{raw}));};return;}
 if(name==='download-json'||name==='download-csv'){download(`${job.id}.${name.endsWith('csv')?'csv':'json'}`,name.endsWith('csv')?csv(job.output):job.output,name.endsWith('csv')?'text/csv':'application/json');return;}
 if(name==='receipt'){await operate('Preparing the task receipt…',async()=>download(`accord-${job.id}.receipt.json`,await api(`/api/tasks/${job.id}/receipt`)));return;}
 if(name==='verify'){await operate('Verifying the receipt against the local chain…',async()=>{const result=await api(`/api/tasks/${job.id}/verify`);modal(`<span class="eyebrow">RECEIPT VERIFICATION</span><h2>${e(result.verdict)}</h2><p>Checked the receipt against the current local chain.</p><pre>${e(JSON.stringify(result,null,2))}</pre>`);});return;}
 const labels={quotes:'Reading your brief and calculating offers…',fund:'Checking authority, then confirming the local escrow transaction…',run:'Reading source rows, normalizing the table and checking each output…',settle:'Rechecking the delivery and invoice, then confirming the local payment…',refund:'Submitting and confirming your local refund…'};
 if(Object.hasOwn(labels,name))await operate(labels[name],()=>mutate(name));
});
$('#detail').addEventListener('close',()=>lastFocus?.isConnected&&lastFocus.focus());
async function loadRoute(){const hash=location.hash.slice(1);if(hash.startsWith('task/')){job=await api('/api/tasks/'+hash.slice(5));route='workspace';}else{route=['agents','evidence'].includes(hash)?hash:'workspace';if(hash==='demo'){present=true;history.replaceState(null,'','#workspace');}}render();}
window.addEventListener('hashchange',()=>loadRoute().catch(err=>showError(err.message)));
async function init(){try{const clean=new URL(location.href);if(clean.searchParams.has('shem')){clean.searchParams.delete('shem');history.replaceState(null,'',clean.pathname+clean.search+clean.hash);}try{const r=await fetch('/evidence/dealtrace-summary.json');if(r.ok)proof=await r.json();}catch{}await refreshList();await loadRoute();}catch(err){$('#app').innerHTML=`<div class="boot"><span class="brand-symbol">a</span><h1>${executionMode==='browser'?'Open your browser workspace':'Start your Accord Lock workspace'}</h1>${executionMode==='browser'?'<p>Use a recent browser with site storage enabled. No local server is required.</p>':'<p>This workspace needs its local task and escrow service.</p><code>pnpm ade:spending:view</code>'}<p>${e(err.message)}</p><button class="button primary" id="retry">Retry connection</button></div>`;$('#retry').onclick=init;}}
init();
