import {workerNames,statusLabel} from './workspace-model.mjs';

const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const action=(name,label,primary=false,disabled=false)=>'<button type="button" class="button '+(primary?'primary':'')+'" data-action="'+name+'" '+(disabled?'disabled':'')+'>'+label+'</button>';
const bot=kind=>'<span class="agent-orb '+kind+'" aria-hidden="true"><i></i><b><em></em><em></em></b></span>';
const icon=kind=>({overview:'◈',workspace:'⇄',deals:'▤',evidence:'◇'}[kind]);
const titles={overview:'Overview',workspace:'Deal Room',deals:'Deals',evidence:'Proof',live:'Live Agents',agents:'Agents & roles'};
const sellerName=job=>job.offers?.find(o=>o.seller===job.selected)?.name??workerNames[job.selected]??'No seller selected';
const number=n=>Number(n??0).toLocaleString('en-US');
const unit=n=>'<strong>'+number(n)+'</strong><span>test units</span>';
const time=at=>new Date(at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});

export function protection(job,kind='authority'){
 const offer=job.offers?.find(o=>o.seller===job.selected),authority=kind==='authority';
 const requested=authority?offer?.price??0:job.invoice,allowed=authority?Math.min(job.perDeal,job.budget):job.agreedPrice;
 return '<section class="interception" role="status" aria-label="'+(authority?'Authority Gate':'Agreement Gate')+' protection"><div class="intercept-heading"><span class="shield-symbol">◇</span><span>ACCORD INTERCEPTED<small>'+ (authority?'Authority Gate':'Agreement Gate')+'</small></span><span class="protection-badge">Protection worked</span></div><h2>'+ (authority?'This offer exceeds your authority.':'Allowed to spend it. Never agreed to it.')+'</h2><div class="gate-equation"><div><strong class="violation-value">'+number(requested)+'</strong><span>'+ (authority?'REQUEST':'INVOICE')+'</span></div><b>'+(authority?'&gt;':'≠')+'</b><div><strong>'+number(allowed)+'</strong><span>'+(authority?'LIMIT':'AGREEMENT')+'</span></div></div><div class="gate-outcome"><strong>'+ (authority?'TRANSACTION PREVENTED':'PAYMENT BLOCKED')+'</strong><p>'+(authority?'Stopped before signing. Your spending authority stays intact.':'The invoice fits your budget. It does not match the agreed price.')+'</p></div><div class="protection-facts">'+(authority?'<span>✓ No signature</span><span>✓ No escrow</span><span>✓ No funds moved</span>':'<span>✓ No payment signed</span><span>✓ Escrow stays locked</span><span>✓ Seller paid 0</span>')+'</div>'+ (authority?action('negotiate','Negotiate with Atlas →',true):action('correct-invoice','Request the agreed invoice · '+job.agreedPrice+' →',true))+'</section>';
}

function overview(){
 return '<div class="overview-page"><div class="overview-hero"><section class="hero-copy"><span class="eyebrow">AGREEMENT ENFORCEMENT FOR AGENTS</span><h1>The agreement decides<br>what gets paid.</h1><p>Give agents room to negotiate.<br>Keep every payment inside the deal.</p><div class="hero-actions">'+action('launch-demo','Run the demo →',true)+'<a class="button" href="#evidence">See public proof ↗</a></div><span class="quiet-label">3 minutes · You make the decisions · No real funds</span><div class="hero-principle"><span>01</span><div><strong>Authority sets the boundary.</strong><small>Can this agent spend 35 when its limit is 30?</small></div></div><div class="hero-principle"><span>02</span><div><strong>Agreement sets the payment.</strong><small>Can it bill 25 when both sides agreed to 20?</small></div></div></section><section class="hero-scene" aria-label="Illustrated example: agents agree 20 and a 25 invoice is blocked"><div class="scene-heading"><span class="scene-dot"></span> A DEAL, PROTECTED <span class="scene-example">Illustrative example</span></div><div class="scene-actors"><div>'+bot('buyer')+'<strong>Buyer</strong><small>Your authority</small></div><div class="scene-connector"><span>⇄</span><small>Negotiating</small></div><div>'+bot('seller')+'<strong>Atlas</strong><small>Research agent</small></div></div><div class="scene-messages"><div class="scene-message buyer-message"><span>Buyer</span>Four CAPEX records. Sources included.</div><div class="scene-message seller-message"><span>Atlas</span>I can do that for <strong>22.</strong></div><div class="scene-message buyer-message"><span>Buyer</span>Same scope. Can we agree on <strong>20?</strong></div></div><div class="scene-agreement"><span>AGREED PRICE</span><strong>20 <small>test units</small></strong><span>✓ Terms accepted</span></div><div class="scene-intercept"><span>◇ AGREEMENT GATE</span><strong>25 <i>≠</i> 20</strong><b>Payment blocked</b><small>The budget allowed it. The agreement did not.</small></div><div class="scene-progress"><span></span></div><button class="scene-pause" data-action="pause-scene" aria-pressed="false">Pause illustration</button></section></div><div class="value-strip"><div><span>01 / HUMAN</span><strong>Set the authority</strong><p>Choose the budget and the limit per deal.</p></div><div><span>02 / AGENTS</span><strong>Negotiate the terms</strong><p>Watch offers, counteroffers and acceptance.</p></div><div><span>03 / ACCORD</span><strong>Enforce the agreement</strong><p>Lock the deal. Stop any payment that differs.</p></div></div></div>';
}

function roster(job){
 const offers=job?.offers??[],items=[['seller-a','Atlas','Source-first research','Reliable coverage'],['seller-b','Nexus','Fast delivery','Speed & margin'],['seller-c','Orbit','Premium research','Quality & depth']];
 return '<aside class="room-roster"><span class="eyebrow">PARTICIPANTS</span><div class="roster-person buyer-roster">'+bot('buyer')+'<div><strong>Buyer agent</strong><small>Your mandate</small></div><span class="presence-dot"></span></div><p class="roster-objective">Best price. Referenced sources. Within your authority.</p><div class="roster-divider"></div>'+items.map(([id,name,role,goal])=>{const offer=offers.find(o=>o.seller===id);return '<button class="roster-person '+(job?.selected===id?'active':'')+'" data-select="'+id+'" '+(!offer||!['QUOTED','BLOCKED'].includes(job?.status)?'disabled':'')+'>'+bot('seller')+'<span><strong>'+name+'</strong><small>'+role+'</small><em>'+goal+'</em></span>'+(offer?'<b>'+offer.price+'</b>':'')+'</button>';}).join('')+'<div class="roster-note"><span>◇</span><p>Private goals.<br>Public proposals.<br>One enforceable deal.</p></div></aside>';
}

function conversation(job){
 const messages=job.events.filter(ev=>['buyer','seller-a','seller-b','seller-c'].includes(ev.actor));
 return '<div class="negotiation-stream" aria-label="Agent negotiation">'+messages.map(ev=>'<article class="negotiation-message '+(ev.actor==='buyer'?'from-buyer':'from-seller')+'"><div class="message-author"><span class="message-avatar '+(ev.actor==='buyer'?'buyer':'seller')+'">'+(ev.actor==='buyer'?'B':e(workerNames[ev.actor]?.[0]))+'</span><strong>'+e(ev.actor==='buyer'?'Buyer':workerNames[ev.actor])+'</strong><time>'+time(ev.at)+'</time></div><div class="message-bubble"><strong>'+e(ev.title)+'</strong><p>'+e(ev.detail)+'</p></div></article>').join('')+'</div>';
}

function control(job){
 const offer=job.offers?.find(o=>o.seller===job.selected),price=job.agreedPrice??offer?.price,locked=job.dealId&&!['REFUNDED','COMPLETED'].includes(job.status),mismatch=job.invoice!=null&&job.invoice!==job.agreedPrice;
 const allowed=price!=null&&price<=job.perDeal&&price<=job.budget;
 return '<aside class="accord-control"><div class="control-heading"><span class="shield-symbol">◇</span><strong>Accord Control</strong></div><section><span class="eyebrow">HUMAN MANDATE</span><dl><div><dt>Total budget</dt><dd>'+number(job.budget)+'</dd></div><div><dt>Max per deal</dt><dd>'+number(job.perDeal)+'</dd></div><div><dt>Delivery window</dt><dd>'+job.deliveryMinutes+' min</dd></div></dl><small>Test units · no cash value</small></section><section class="control-gate"><div><span>01</span><strong>Authority Gate</strong><b class="'+(job.status==='BLOCKED'?'red':'green')+'">'+(job.authorityRevoked?'Stopped':job.status==='BLOCKED'?'Protected':allowed?'Passed':'Pending')+'</b></div><p>Is this agent allowed to spend it?</p>'+(price!=null?'<div class="control-equation">'+price+' '+(allowed?'≤':'&gt;')+' '+Math.min(job.perDeal,job.budget)+'</div>':'')+'</section><section><span class="eyebrow">'+(job.dealId?'CURRENT AGREEMENT':'PROPOSED TERMS')+'</span><div class="control-seller">'+bot('seller')+'<strong>'+e(sellerName(job))+'</strong></div><div class="agreed-price">'+(price==null?'—':number(price))+'<small>test units</small></div><p>'+job.source.length+' CAPEX records · Sources required</p><span class="term-status">'+(job.agreementSignatures?'✓ Buyer signed · ✓ Seller signed':job.dealId?'✓ Agreement locked':'Terms awaiting approval')+'</span></section><section class="control-gate"><div><span>02</span><strong>Agreement Gate</strong><b class="'+(mismatch?'red':'green')+'">'+(mismatch?'Protected':job.invoice!=null?'Matched':'Pending')+'</b></div><p>Is this the payment both sides agreed?</p>'+(job.invoice!=null?'<div class="control-equation '+(mismatch?'red':'')+'">'+job.invoice+' '+(mismatch?'≠':'=')+' '+job.agreedPrice+'</div>':'')+'</section><section class="control-money"><div><span>In escrow</span><strong>'+number(locked?job.agreedPrice:0)+'</strong></div><div><span>Paid to seller</span><strong>'+number(job.status==='COMPLETED'?job.agreedPrice:0)+'</strong></div></section><div class="control-actions">'+action('proof','Inspect proof ↗')+action('stop',job.authorityRevoked?'AGENT STOPPED':'Stop agent',false,job.authorityRevoked||['COMPLETED','REFUNDED','CANCELLED'].includes(job.status))+'</div>'+(job.authorityRevoked?'<p class="stop-note" role="status">New commitments disabled. Existing funded terms preserved.</p>':'')+'</aside>';
}

function mobileControl(job){return '<div class="mobile-control-summary" aria-label="Deal control summary"><div><span>Budget</span><strong>'+job.budget+'</strong></div><div><span>Max / deal</span><strong>'+job.perDeal+'</strong></div><div><span>Agreed</span><strong>'+(job.agreedPrice??'—')+'</strong></div><div><span>Invoice</span><strong class="'+(job.invoice!=null&&job.invoice!==job.agreedPrice?'red':'')+'">'+(job.invoice??'—')+'</strong></div></div>';}

function timeline(job){return '<section class="transaction-timeline"><div><span class="eyebrow">TRANSACTION TIMELINE</span><span>'+job.events.length+' recorded events</span></div><ol>'+job.events.slice().reverse().map(ev=>'<li><time>'+time(ev.at)+'</time><span class="timeline-dot '+e(ev.actor)+'"></span><strong>'+e(ev.title)+'</strong><span>'+e(ev.actor==='policy'?'Accord':ev.actor==='chain'?'Settlement':ev.actor==='human'?'You':workerNames[ev.actor]??'Buyer')+'</span></li>').join('')+'</ol></section>';}

function review(job,c){
 const valid=job.validation?.verified,match=job.invoice===job.agreedPrice;
 return (match?'<div class="accord-event"><span>◇ ACCORD · AGREEMENT MATCHED</span><strong>'+job.invoice+' = '+job.agreedPrice+'</strong><p>The corrected invoice matches the locked agreement.</p></div>':protection(job,'agreement'))+'<section class="delivery-section"><div class="delivery-heading"><div><span class="eyebrow">DELIVERED BY '+e(sellerName(job)).toUpperCase()+'</span><h2>Work you can inspect.</h2></div><span class="'+(valid?'green':'red')+'">'+(valid?'✓ Checks passed':'Review required')+'</span></div>'+c.table(job.output)+'<details class="validation"><summary>Inspect '+job.validation.checks.length+' acceptance checks</summary><div class="checks">'+job.validation.checks.map(v=>'<div><span class="'+(v.pass?'pass':'fail')+'">'+(v.pass?'✓':'×')+'</span><strong>'+e(v.name.replaceAll('_',' ').toLowerCase())+'</strong><span>'+ (v.pass?'Passed':'Failed')+'</span></div>').join('')+'</div><p>Compared with the supplied input; citations are not independent fact certification.</p></details><div class="review-tools">'+action('download-json','Download JSON ↓')+action('download-csv','Download CSV ↓')+action('delivery','Replace delivery')+'</div><form id="invoice-form" class="invoice-editor"><label for="invoice-amount">Invoice <span>test units</span></label><input id="invoice-amount" name="amount" type="number" min="1" max="1000000" step="1" value="'+job.invoice+'"><button class="button" type="submit">Check invoice</button></form><div class="action-bar">'+action('refund','Reject & refund')+action('settle','Approve & pay '+job.agreedPrice,true,!valid||!match)+'</div></section>';
}

function stage(job,c){
 if(['FUNDING','SETTLING','REFUNDING'].includes(job.status))return c.pending(job);
 if(job.status==='REVIEW')return review(job,c);
 if(job.status==='LOCKED')return '<div class="accord-event"><span>◇ ACCORD · AGREEMENT LOCKED</span><strong>'+job.agreedPrice+' <small>test units</small></strong><p>'+e(sellerName(job))+' · '+job.source.length+' records · Source references required</p><span>Funds secured. Your agreed terms stay fixed.</span></div>'+c.workView(job);
 if(['COMPLETED','REFUNDED','CANCELLED'].includes(job.status))return '<section class="panel completion"><div class="completion-mark">'+(job.status==='COMPLETED'?'✓':'↶')+'</div><span class="eyebrow">'+(job.status==='COMPLETED'?'PAID AS AGREED':e(statusLabel(job.status)).toUpperCase())+'</span><h2>'+ (job.status==='COMPLETED'?'The agreement became the payment.':job.status==='REFUNDED'?'Your locked funds came back.':'This deal is closed.')+'</h2><p>'+ (job.status==='COMPLETED'?number(job.agreedPrice)+' test units paid once to '+e(sellerName(job))+'.':job.status==='REFUNDED'?number(job.agreedPrice)+' test units returned to the buyer.':'No funds moved.')+'</p><div class="completion-actions">'+(job.output?action('download-json','Download result ↓',true):'')+action('proof','Inspect proof ↗')+'</div>'+(job.output?c.table(job.output):'')+action('launch-demo','Start another guided deal →')+'</section>';
 if(job.status==='DRAFT')return '<section class="mandate-ready"><div class="room-team">'+bot('buyer')+'<span>⇄</span>'+bot('seller')+'</div><span class="eyebrow">YOUR MANDATE IS READY</span><h2>Let the agents make their case.</h2><p>'+e(job.brief)+'</p><div class="brief-chips"><span>'+job.source.length+' CAPEX records</span><span>Sources required</span><span>'+job.deliveryMinutes+' min delivery</span></div>'+action('quotes','Send request to all agents →',true)+action('edit','Edit mandate')+'</section>';
 const offer=job.offers.find(o=>o.seller===job.selected);
 return (job.status==='BLOCKED'?protection(job):'')+conversation(job)+(offer&&job.status!=='BLOCKED'?'<div class="negotiation-composer"><form id="counter-form"><label for="counter-price">Your counteroffer <span>test units</span></label><div><input id="counter-price" name="price" type="number" min="1" max="1000000" value="'+(job.demoMode?18:Math.min(offer.price,job.perDeal))+'" aria-label="Counteroffer in test units"><button class="button" type="submit">Send counteroffer →</button></div></form>'+ (offer.counterPrice? action('accept-counter','Accept '+offer.counterPrice+' →',true):action('fund','Approve agreement & lock '+offer.price+' →',true))+'</div>':'');
}

function emptyRoom(c,s){return '<section class="empty-room"><div class="room-team">'+bot('buyer')+'<span>⇄</span>'+bot('seller')+'</div><span class="eyebrow">A SEAT FOR EVERY SIDE OF THE DEAL</span><h1>Your next agreement starts here.</h1><p>Set the work and the spending authority.<br>Then follow the proposals, protection and payment in one room.</p><div>'+action('launch-demo','Start the guided deal →',true)+action('create-custom','Use my own source table')+'</div><span class="quiet-label">Guided Demo · Deterministic agent simulation · No real money</span></section>'+(s.creating?c.briefForm(s):'');}
function deals(tasks){return '<div class="page-intro"><span class="eyebrow">AGREEMENT HISTORY</span><h1>Every deal has a record.</h1><p>Reopen a deal to inspect its decisions, output and proof.</p></div><section class="deals-table">'+(tasks.length?'<div class="deals-table-head"><span>Deal</span><span>Status</span><span>Agreed</span></div>'+tasks.map(t=>'<button data-job="'+e(t.id)+'"><span><strong>'+e(t.title)+'</strong><small>'+e(t.id.slice(0,8))+' · '+t.rows+' rows</small></span><span class="deal-status '+e(t.status.toLowerCase())+'">'+e(statusLabel(t.status))+'</span><span>'+ (t.price??'—')+'</span></button>').join(''):'<p>No agreements yet.</p>'+action('launch-demo','Make your first deal →',true))+'</section>';}

export function renderDealRoom(s,c){
 const {job,tasks,network}=s,route=s.route??'overview',live=route==='live';
 const body=route==='overview'?overview():route==='evidence'?c.evidence(s.proof):route==='agents'?c.agents():route==='deals'?deals(tasks):live?liveRoom(s):!job?emptyRoom(c,s):'<div class="room-heading"><div><span class="eyebrow">AGENT DEAL ROOM / '+e(job.id.slice(0,6)).toUpperCase()+'</span><h1>'+e(job.title)+'</h1></div><span class="deal-status '+e(job.status.toLowerCase())+'">'+e(statusLabel(job.status))+'</span></div>'+(s.present?'<div class="demo-guidance"><span>GUIDED DEMO · DEMO ASSIST</span><p>'+({DRAFT:'Send the request. Compare three agents with different priorities.',BLOCKED:'Protection worked. Negotiate with Atlas inside your authority.',QUOTED:'Try 18. Atlas can propose 20. Accept the terms before funding.',LOCKED:'Run the worker to inspect the delivered data and its invoice.',REVIEW:job.invoice===job.agreedPrice?'The corrected bill matches. Approve it or reject the work.':'25 is within the budget, but differs from the agreed 20. The Agreement Gate stops payment.',COMPLETED:'The exact agreement was paid. Open the proof to inspect the receipt.'}[job.status]??'Inspect the deal state and choose the next action.')+'</p></div>':'')+mobileControl(job)+'<div class="deal-room">'+roster(job)+'<section class="room-main"><div class="room-tabs"><strong>'+(['REVIEW','COMPLETED','REFUNDED'].includes(job.status)?'Delivery & payment':'Negotiation')+'</strong><span>DEMO · Deterministic simulation</span></div>'+stage(job,c)+'</section>'+control(job)+'</div>'+timeline(job);
 return '<aside class="sidebar deal-sidebar"><a class="brand" href="#overview"><span class="brand-symbol">a</span>accord lock</a><div class="workspace-switch"><span>A</span><div>Agent transactions<small>Agreement enforcement</small></div></div><nav aria-label="Main navigation">'+['overview','workspace','deals','evidence'].map(r=>'<a href="#'+r+'" '+(route===r?'aria-current="page"':'')+'><span class="nav-icon">'+icon(r)+'</span>'+titles[r]+'</a>').join('')+'</nav><div class="sidebar-divider"></div><span class="eyebrow">WORKSPACE</span>'+action('create-custom','＋ New deal')+'<div class="recent-deals">'+tasks.slice(0,5).map(t=>'<button data-job="'+e(t.id)+'"><span class="status-dot '+e(t.status.toLowerCase())+'"></span><span>'+e(t.title)+'</span></button>').join('')+'</div><div class="sidebar-bottom"><span class="shield-symbol">◇</span><div>Money follows the agreement.<small>Always.</small></div></div></aside><div class="app-shell deal-shell"><header class="topbar"><div class="breadcrumb">Workspace <span>/</span><strong>'+e(titles[route]??'Deal Room')+'</strong></div><div class="mode-switch" aria-label="Execution mode"><a href="#workspace" '+(!live?'aria-current="page"':'')+'>Guided Demo</a><a href="#live" '+(live?'aria-current="page"':'')+'>Live Agents</a></div><div class="top-actions">'+action('tasks','Deals')+(job?action('proof','Inspect proof ↗'):'<a class="button" href="#evidence">Inspect proof ↗</a>')+'<span class="user-avatar">Y</span></div></header><div class="environment-strip"><span class="env-dot"></span><strong>'+ (live?'LIVE AGENTS':'GUIDED DEMO')+'</strong><span>'+ (live?'Actual model negotiation requires a connected Kiln service.':'Deterministic agent simulation · Test units · '+(network?.mode==='BROWSER_EVM'?'Saved in this browser':'Saved on this computer'))+'</span></div><main id="main"><div id="error" class="notice danger" role="alert" hidden></div><div id="operation" class="notice processing" role="status" hidden></div><div id="page-content">'+body+'</div><footer class="workspace-footer"><span>accord lock</span><a href="#agents">Execution & trust boundaries ↗</a></footer></main></div>';
}

function liveRoom(s){return '<div class="page-intro"><span class="eyebrow">REAL NEGOTIATION, VISIBLE EVIDENCE</span><h1>Live Agents</h1><p>Kiln · qwen3-32b. Agent proposals are model outputs; payment authority remains enforced by code.</p></div><section class="panel live-connection"><span class="status-chip">'+(s.live?.available?'Connected':'Service not connected')+'</span><h2>'+ (s.live?.available?'Ready to negotiate.':'Connect the live agent service.')+'</h2><p>Guided Demo uses deterministic rules. Live Agents uses private seller policies and actual model calls. No replay is presented as a live response.</p>'+action('connect-live','Check live connection',true)+'<a class="button" href="#evidence">Inspect a recorded Kiln run ↗</a><div id="live-content"></div></section>';}
