const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sellers={atlas:['Atlas','Honest'],nexus:['Nexus','Agreement violator'],orbit:['Orbit','Risky / manipulative']};
export const money=(amount,currency='USD')=>amount==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency}).format(amount/(currency==='KRW'?1:100));
export function parseMoney(text,currency){
 const value=String(text).trim(),digits=currency==='KRW'?0:2;
 if(!(digits?/^\d+(?:\.\d{1,2})?$/:/^\d+$/).test(value))throw Error('Enter a valid amount in '+currency+'.');
 const [whole,fraction='']=value.split('.'),n=Number(whole)*(digits?100:1)+Number(fraction.padEnd(digits,'0'));
 if(!Number.isSafeInteger(n)||n<1||n>100000000)throw Error('Amount must be positive and within the supported limit.');return n;
}
export function nextNegotiationStep(session){
 if(session.stopped||session.agreement||session.selectedSeller)return null;
 const ids=session.request.allowedSellers;
 for(const seller of ids)if(!session.messages.some(m=>m.actor===seller))return {action:'offer',seller};
 for(const seller of ids){
  const turns=session.messages.filter(m=>m.seller===seller),last=turns.at(-1);
  if(last.quote.action==='decline'||last.quote.action==='accept'||turns.filter(m=>m.actor===seller).length>=2)continue;
  return {action:last.actor==='buyer'?'respond':'counter',seller};
 }
 if(session.messages.at(-1)?.step==='select'&&session.messages.at(-1)?.quote.action==='decline')return null;
 return {action:'select'};
}
export function rejectedTerms(q,m){
 if(q.action==='invoice')return null;
 if(q.action==='decline')return 'DECLINED';
 if(q.currency!==m.currency)return 'CURRENCY_CHANGED';
 if(q.scope!==m.task)return 'SCOPE_CHANGED';
 if(q.deliveryMinutes>m.maxDeliveryMinutes)return 'DELIVERY_LIMIT';
 if(q.amountMinor+q.feeMinor>Math.min(m.budgetMinor,m.perDealMinor))return 'OUTSIDE_AUTHORITY';
 return null;
}
const button=(action,label,disabled=false,secondary=false)=>`<button type="button" data-pg="${action}" class="pg-button ${secondary?'secondary':''}" ${disabled?'disabled':''}>${label}</button>`;
const field=(label,name,value,type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`;
export function renderPlayground({current,info,error,pending,running,evidence=false,draft={}}){
 const s=current?.session,m=s?.request,a=s?.agreement?.body,i=s?.invoices.at(-1)?.body,d=s?.decisions.at(-1),paid=s?.settlement;
 const expired=s&&Date.now()>=s.expiresAt,locked=!!a,busy=!!pending||!!current?.pending;
 const amount=n=>money(n,m?.currency),latest=id=>s?.messages.filter(x=>x.actor===id&&x.quote.action!=='invoice').at(-1);
 return `<div class="pg-app"><header class="pg-header"><a class="pg-brand" href="#home"><span>⛨</span> Accord Lock</a><nav><a href="#presentation">Guided Demo</a><a href="#playground" aria-current="page">Live Playground</a></nav><span class="pg-live">● LIVE · Kiln / qwen3-32b</span></header>
 <main id="main" class="pg-main ${s?'has-session':''}"><div class="pg-intro"><div><span class="pg-eyebrow">AUTONOMOUS AGENTS. ENFORCED AGREEMENTS.</span><h1>Let agents negotiate. <br>Let the agreement decide.</h1><p>Three independent seller behaviors. Real model responses. Accord Lock stands between the invoice and payment.</p></div><aside><b>External agent test environment</b><p>Buyer and sellers are test clients of Accord Lock’s enforcement API.</p><small>Settlement: test ledger · No real funds · No on-chain transaction</small></aside></div>
 ${error?`<div class="pg-alert" role="alert"><b>Request could not complete</b><p>${esc(error)}</p><small>No fabricated response or automatic retry. Refresh saved state before continuing.</small></div>`:''}
 ${!s?`<form id="pg-start" class="pg-setup"><div><span class="pg-eyebrow">01 / HUMAN AUTHORITY</span><h2>What should your Buyer purchase?</h2><label>Purchase task<textarea name="task" rows="3" maxlength="2000" required>${esc(draft.task??'Buy a market research report on battery recycling opportunities')}</textarea></label><div class="pg-form-grid">${field('Maximum budget','budget',draft.budget??'100')}<label>Currency<select name="currency">${['USD','EUR','GBP','KRW'].map(c=>`<option ${c===(draft.currency??'USD')?'selected':''}>${c}</option>`).join('')}</select></label>${field('Maximum per deal','perDeal',draft.perDeal??'100')}${field('Delivery limit · minutes','delivery',draft.delivery??'60','number')}</div><label>Optional service preferences<textarea name="constraints" rows="2" maxlength="1000" placeholder="Include competitors, source links, and market size estimates.">${esc(draft.constraints??'')}</textarea></label><small>Preferences guide the agents. Budget, per-deal limit, currency, allowed sellers, expiry and delivery time are mechanically enforced.</small></div><aside><h3>Your live test agents</h3><div class="pg-buyer-mini">Buyer agent <span>Find the best eligible deal</span></div>${Object.entries(sellers).map(([id,[name,behavior]])=>`<label class="pg-persona"><input type="checkbox" name="seller" value="${id}" ${(draft.sellers??Object.keys(sellers)).includes(id)?'checked':''}><div><b>${name}</b><span>${behavior}</span></div></label>`).join('')}<p>Prices, seller selection and invoices come from actual inference. A violation is possible, never scripted.</p><button class="pg-button" ${busy||!info?.available?'disabled':''}>${busy?'Creating mandate…':'Start live negotiation →'}</button><small>${info?`${info.remainingCalls} model calls available · Up to ${info.sessionLimit} per session`:'Connecting to Kiln service…'}</small></aside></form>`:`
 <div class="pg-toolbar"><div><b translate="no">${esc(m.task)}</b><span>${s.stopped?'Authority revoked':expired?'Session expired':running?'Agents are negotiating':paid?'Settlement recorded':locked?'Agreement locked':'Ready for your next action'} · ${current.attempts} / 24 calls</span></div><div>${button('evidence',evidence?'Back to transaction':'Inspect DealTrace',false,true)}${button('export','Export evidence',false,true)}${button('refresh','Refresh',!!pending,true)}${button('new','New session',busy,true)}</div></div>
 ${expired?'<div class="pg-alert">This 20-minute mandate expired. Evidence remains available. Start a new session to delegate again.</div>':''}
 ${evidence?`<section class="pg-evidence"><h2>DealTrace · Live transaction history</h2><p>Signed agent messages, bilateral agreement, invoices, policy decisions, and the test settlement. Identities are controlled by this test environment.</p><p>${esc(current.verification?.verdict??'Saved evidence')} · ${esc(current.verification?.scope??'Export and inspect hashes below.')}</p>${s.events.map(e=>`<details><summary><time>${new Date(e.at).toLocaleTimeString('en-US')}</time><b>${esc(e.type.replaceAll('_',' '))}</b><code>${esc(e.hash.slice(0,16))}…</code></summary><pre>${esc(JSON.stringify(e,null,2))}</pre></details>`).join('')}<details><summary>Model attempts, rejected responses and usage</summary><pre>${esc(JSON.stringify(current.attemptLog,null,2))}</pre></details><details><summary>Full signed messages and receipt</summary><pre>${esc(JSON.stringify({messages:s.messages,agreement:s.agreement,invoices:s.invoices,receipt:s.receipt},null,2))}</pre></details></section>`:`
 <section class="pg-money" aria-label="Transaction amounts"><div><span>Human budget</span><strong>${amount(m.budgetMinor)}</strong></div><div><span>Signed agreement</span><strong>${amount(a?.amountMinor)}</strong></div><div class="${d?.verdict==='PAYMENT_BLOCKED'?'out':''}"><span>Requested payment</span><strong>${amount(i?.amountMinor)}</strong></div><div class="in"><span>Seller received · test ledger</span><strong>${amount(paid?.sellerReceivedMinor??0)}</strong></div></section>
 <div class="pg-workspace"><section class="pg-network" aria-label="Live agent transaction"><div class="pg-human"><span>YOU · SPENDING AUTHORITY</span><strong>${amount(m.budgetMinor)}</strong><small>Max / deal ${amount(m.perDealMinor)} · ${m.currency}</small></div><div class="pg-connector">↓ mandate delegated</div><div class="pg-buyer ${pending?.actor==='buyer'?'thinking':''}"><span class="pg-avatar buyer">B</span><div><b>Buyer agent</b><span>${pending?.actor==='buyer'?'Thinking through actual Kiln inference…':s.selectedSeller?'Selected '+sellers[s.selectedSeller][0]:'Compare offers · Negotiate · Select'}</span></div></div><div class="pg-fan" aria-hidden="true"><svg viewBox="0 0 600 45" preserveAspectRatio="none"><path d="M300 0 V16 H100 V45 M300 16 V45 M300 16 H500 V45"/></svg></div><div class="pg-sellers">${Object.entries(sellers).map(([id,[name,behavior]])=>{const q=latest(id)?.quote;return `<div class="pg-seller ${s.selectedSeller===id?'selected':''} ${pending?.actor===id?'thinking':''} ${!m.allowedSellers.includes(id)?'excluded':''}"><span class="pg-avatar">${name[0]}</span><b>${name}</b><small>${behavior}</small><strong>${q?amount(q.amountMinor+q.feeMinor):'—'}</strong><span>${pending?.actor===id?'Thinking…':!m.allowedSellers.includes(id)?'Outside allowlist':s.selectedSeller===id?'Selected seller':q?q.action:'Awaiting offer'}</span></div>`;}).join('')}</div><div class="pg-connector">↓ ${locked?'Bilateral terms locked':'Offers and counters determine the deal'}</div><div class="pg-lock ${d?.verdict==='PAYMENT_BLOCKED'?'blocked':''}"><span>⛨ ACCORD LOCK</span><b>${paid?'Settlement recorded':d?.verdict.replaceAll('_',' ')??(locked?'Awaiting invoice':'Agreement before payment')}</b><small>Authority Gate → Agreement Gate</small></div><div class="pg-stage">${['Mandate','Negotiation','Agreement','Invoice','Enforcement','Settlement'].map((t,n)=>`<span class="${[true,s.messages.length,locked,i,d,paid][n]?'done':''}">${n+1}. ${t}</span>`).join('')}</div></section>
 <section class="pg-conversation"><div class="pg-chat-title"><h2>Agents at work</h2><span>${s.messages.length} actual messages</span></div><div class="pg-messages" role="log" aria-label="Live negotiation messages" aria-live="polite">${s.messages.length?s.messages.map(msg=>`<article class="${msg.actor==='buyer'?'buyer-message':'seller-message'}"><div><b>${msg.actor==='buyer'?'Buyer':sellers[msg.actor][0]} → ${msg.to==='buyer'?'Buyer':sellers[msg.to][0]}</b><time>${new Date(msg.at).toLocaleTimeString('en-US')}</time></div>${rejectedTerms(msg.quote,m)?`<span class="pg-term-rejected">TERMS REJECTED · ${rejectedTerms(msg.quote,m)}</span>`:''}<strong>${esc(msg.quote.action.toUpperCase())} · ${amount(msg.quote.amountMinor+msg.quote.feeMinor)}</strong>${msg.quote.feeMinor?`<small>Includes ${amount(msg.quote.feeMinor)} extra fees</small>`:''}<p translate="no">${esc(msg.quote.message)}</p><small>${msg.quote.deliveryMinutes} min · ${esc(msg.quote.currency)}</small><details><summary>Inspect structured terms & model evidence</summary><pre>${esc(JSON.stringify(msg,null,2))}</pre></details></article>`).join(''):'<div class="pg-empty">Your mandate is saved.<br>Agents will request and exchange real offers here.</div>'}</div>${pending||current?.pending?`<div class="pg-pending" role="status"><i></i>${esc(pending?.label??'A saved model request is running. Use Refresh to load its result.')}<small>A real API call is in progress. You can pause after this response or stop the session.</small></div>`:''}${current.error?`<div class="pg-alert"><b>PROPOSAL REJECTED</b><p>${esc(current.error)}</p><span>No accepted terms were invented. Retry the step or start with another seller allowlist.</span></div>`:''}</section></div>
 ${d?`<section class="pg-decision ${d.verdict==='PAYMENT_BLOCKED'?'blocked':'allowed'}" role="status"><div><span class="pg-eyebrow">${d.verdict==='PAYMENT_BLOCKED'?'PAYMENT STOPPED AT THE AGREEMENT GATE':'AGREEMENT VERIFIED'}</span><h2>${d.verdict.replaceAll('_',' ')}</h2><code>${esc(d.reason)}</code><p>${d.verdict==='PAYMENT_BLOCKED'?'Budget headroom does not authorize a different invoice. No test funds moved.':'The requested payment matches the signed agreement. Settlement is a separate action.'}</p></div><div class="pg-equations"><div>${amount(i?.amountMinor)} ≤ ${amount(m.budgetMinor)} <b>${d.checks.find(c=>c.name==='BUDGET')?.pass?'PASS':'FAIL'} · Budget</b></div><div>${amount(i?.amountMinor)} ${i?.amountMinor===a?.amountMinor?'=':'≠'} ${amount(a?.amountMinor)} <b>${d.checks.find(c=>c.name==='AGREEMENT_PRICE_MISMATCH')?.pass?'PASS':'FAIL'} · Agreement</b></div></div><details><summary>Inspect every policy check</summary>${d.checks.map(c=>`<p>${c.pass?'✓':'✕'} ${esc(c.name)} <code>${esc(JSON.stringify(c.actual))}</code></p>`).join('')}</details></section>`:''}
 ${paid?`<section class="pg-settled"><h2>✓ ${amount(paid.amountMinor)} paid to ${sellers[s.selectedSeller][0]}</h2><p>Test ledger settlement confirmed once. Remaining authority: ${amount(paid.buyerRemainingMinor)}. Signed receipt created.</p>${button('evidence','Inspect receipt & evidence',false,true)}</section>`:''}
 `}
 <section class="pg-controls" aria-label="Live controls">${!expired&&!s.stopped&&!paid?running?button('pause','Pause after current response',false,true):!locked?button('run',s.selectedSeller?'Selection complete':'Continue negotiation',busy||!!s.selectedSeller):'':''}${!expired&&!s.stopped&&!paid&&s.selectedSeller&&!locked?button('approve','Approve agreement & request invoice',busy):''}${!expired&&!s.stopped&&!paid&&locked&&!i?button('invoice','Request seller invoice',busy):''}${!expired&&!s.stopped&&!paid&&i&&(!d||s.events.at(-1)?.type==='INVOICE_PROPOSED')?button('enforce','Check payment request',busy):''}${!expired&&!s.stopped&&!paid&&d?.verdict==='PAYMENT_BLOCKED'?button('correct','Ask seller to correct invoice',busy):''}${!expired&&!s.stopped&&!paid&&d?.verdict==='PAYMENT_AUTHORIZED'?button('settle','Settle authorized test payment',busy):''}${!s.stopped&&!expired&&!paid?button('stop','Stop agents',false,true):''}<small>No replayed model output. Requests, failures, invoices and decisions are saved.</small></section>`}
 <footer>AI negotiates. Code authorizes. Evidence explains. <a href="#evidence">Historical Sepolia proof ↗</a><span>Historical public-chain evidence is separate from this Live Playground’s test ledger.</span></footer></main></div>`;
}

export function mountPlayground(root){
 let current=null,info=null,error=null,pending=null,running=false,evidence=false,csrf,disposed=false,draft={};
 const render=()=>{if(disposed)return;root.innerHTML=renderPlayground({current,info,error,pending,running,evidence,draft});const log=root.querySelector('.pg-messages');if(log)log.scrollTop=log.scrollHeight;};
 const reveal=selector=>root.querySelector(selector)?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 async function request(body,id){
  if(body&&!csrf)await request();
  const r=await fetch('/api/live?playground=1'+(id?'&id='+encodeURIComponent(id):''),{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Accord-Live-Token':csrf},body:JSON.stringify(body)}:{})});
  const data=await r.json();if(!r.ok)throw Error(data.error??'LIVE_SERVICE_UNAVAILABLE');csrf=data.csrf??csrf;return data;
 }
 function save(){if(current)localStorage.setItem('accord-playground-current',current.session.id);}
 async function act(action,seller){
  const actor=['counter','select'].includes(action)?'buyer':action==='invoice'?current.session.selectedSeller:seller;
  pending={actor,label:action==='enforce'?'Accord Lock is checking the signed agreement…':action==='settle'?'Committing test-ledger settlement…':`${actor==='buyer'?'Buyer':sellers[actor]?.[0]??'Accord Lock'} · ${action.replaceAll('-',' ')}`};error=null;render();
  try{const result=await request({action,seller,id:current.session.id,revision:current.revision,operationId:crypto.randomUUID()});current=result;save();if(result.error)throw Error(result.error);}
  finally{pending=null;render();}
 }
 async function run(){running=true;error=null;render();try{while(running&&!disposed){const next=nextNegotiationStep(current.session);if(!next)break;await act(next.action,next.seller);}}finally{running=false;render();}}
 const handleError=e=>{error=e.message==='LIVE_SESSION_EXPIRED'?'This mandate expired. Start a new session; existing evidence is still inspectable.':e.message;running=false;render();};
 async function click(ev){const action=ev.target.closest('[data-pg]')?.dataset.pg;if(!action)return;
  try{
   if(action==='pause'){running=false;render();return;}
   if(action==='stop'){running=false;const result=await request({action:'stop',id:current.session.id,revision:current.revision,operationId:crypto.randomUUID()});current=result;save();render();return;}
   if(pending&&!['evidence','export'].includes(action))return;
   if(action==='run')await run();
   else if(action==='evidence'){evidence=!evidence;render();reveal(evidence?'.pg-evidence':'.pg-money');}
   else if(action==='export'){const a=document.createElement('a');a.href='/api/live?playground=1&id='+encodeURIComponent(current.session.id)+'&download=1';a.download='accord-live-evidence.json';document.body.append(a);a.click();a.remove();}
   else if(action==='refresh'){current=await request(undefined,current.session.id);info=await request();render();}
   else if(action==='new'){if(current&&!current.session.stopped&&!current.session.settlement&&Date.now()<current.session.expiresAt)await act('stop');current=null;evidence=false;error=null;localStorage.removeItem('accord-playground-current');info=await request();render();}
   else if(action==='approve'){await act('agree');await act('invoice');await act('enforce');reveal('.pg-decision');}
   else if(action==='invoice'||action==='correct'){await act('invoice');await act('enforce');reveal('.pg-decision');}
   else if(action==='settle'||action==='enforce'){await act(action);reveal(action==='settle'?'.pg-settled':'.pg-decision');}
  }catch(e){handleError(e);}
 }
 async function submit(ev){if(ev.target.id!=='pg-start')return;ev.preventDefault();const form=new FormData(ev.target);draft={...Object.fromEntries(form),sellers:form.getAll('seller')};
  try{const currency=form.get('currency'),input={task:form.get('task'),currency,budgetMinor:parseMoney(form.get('budget'),currency),perDealMinor:parseMoney(form.get('perDeal'),currency),maxDeliveryMinutes:Number(form.get('delivery')),constraints:form.get('constraints'),allowedSellers:form.getAll('seller')};pending={label:'Creating your spending mandate…'};render();current=await request({action:'start',request:input,operationId:crypto.randomUUID()});pending=null;save();render();reveal('.pg-money');await run();}catch(e){pending=null;handleError(e);}
 }
 const captureDraft=ev=>{if(ev.target.closest('#pg-start')){const form=new FormData(ev.target.closest('form'));draft={...Object.fromEntries(form),sellers:form.getAll('seller')};}};
 root.addEventListener('input',captureDraft);root.addEventListener('click',click);root.addEventListener('submit',submit);render();
 (async()=>{try{info=await request();const id=localStorage.getItem('accord-playground-current');if(id){try{current=await request(undefined,id);}catch(e){error='Saved session could not be loaded: '+e.message;localStorage.removeItem('accord-playground-current');}}render();}catch(e){handleError(e);}})();
 return ()=>{disposed=true;running=false;root.removeEventListener('input',captureDraft);root.removeEventListener('click',click);root.removeEventListener('submit',submit);};
}
