import {presentationModel,sellerNames} from './presentation-model.mjs';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=(action,label,primary=false,disabled=false)=>`<button type="button" class="button ${primary?'primary':''}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const orb=kind=>`<span class="story-agent ${kind}" aria-hidden="true"><i></i><i></i></span>`;
const positions={human:[80,110],mandate:[255,110],buyer:[430,110],discovery:[600,110],atlas:[815,45],nexus:[815,135],orbit:[815,225],authority:[1060,135],negotiation:[1060,350],deal:[805,350],escrow:[550,350],delivery:[300,350],invoice:[100,490],agreement:[365,490],settlement:[710,490],receipt:[1060,490]};
const edges=[['human','mandate','M145 110 H190'],['mandate','buyer','M320 110 H365'],['buyer','discovery','M495 110 H535'],['discovery','atlas','M665 110 H700 Q725 110 725 85 V65 Q725 45 745 45 H750'],['discovery','nexus','M665 110 H715 V135 H750'],['discovery','orbit','M665 110 H690 V200 Q690 225 715 225 H750'],['atlas','authority','M880 45 H928 Q950 45 950 65 V110 Q950 135 973 135'],['nexus','authority','M880 135 H973'],['orbit','authority','M880 225 H930 Q950 225 950 205 V160 Q950 135 973 135'],['authority','negotiation','M1060 194 V306'],['negotiation','deal','M990 350 H882'],['deal','escrow','M730 350 H620'],['escrow','delivery','M480 350 H370'],['delivery','invoice','M230 350 H100 V449'],['invoice','agreement','M170 490 H273'],['agreement','settlement','M456 490 H635'],['settlement','receipt','M785 490 H980']];
function headline(m){
 if(m.busy)return {tag:'IN PROGRESS',title:m.pending?.label??'Waiting for the actual response.',detail:'Only confirmed results light up the graph. You can inspect the current state.'};
 const copy={ready:['01 / MANDATE','You set the limits. Agents make the deal.','Delegate four source-linked CAPEX records. Follow one transaction from authority to receipt.'],mandate:['01 / MANDATE','Your authority is delegated.','The Buyer can request terms. No deal has been signed.'],quotes:['01 / DISCOVERY',m.isLive?'Actual offers. Your next choice.':'Three agents. Three proposals.','A proposal must pass your authority before it can become a commitment.'],authority:['AUTHORITY GATE · PROTECTION WORKED',`${m.proposed} is more than you authorized.`,`${m.proposed} > ${Math.min(m.budget,m.limit)}. No signature. No escrow. No funds moved.`],negotiation:['02 / DEAL',m.isLive?'Buyer and '+m.activeSeller+' are negotiating.':'The agents found common ground.',`${m.activeSeller} proposes ${m.isLive?m.proposed:m.revision}. A proposal becomes binding only when both sides sign.`],deal:['02 / DEAL','Two signatures. One locked agreement.',`${m.price} test units. The agreed terms are the payment boundary.`],escrow:['03 / EXECUTION',`${m.price} is secured in escrow.`,'The source-table worker can now deliver the agreed work.'],delivery:['03 / DELIVERY','Delivery needs review.','Inspect the acceptance checks. Payment stays blocked until every requirement is met.'],blocked:['AGREEMENT GATE · PROTECTION WORKED','Allowed by the budget. Blocked by the deal.',`The budget is ${m.budget}. The invoice is ${m.invoice}. But both sides agreed to ${m.price}.`],matched:['AGREEMENT GATE · MATCHED','The invoice now matches the deal.',`${m.invoice} = ${m.price}. The delivery checks pass. Payment still needs your approval.`],settled:['04 / SETTLEMENT',`${m.price} paid. Exactly as agreed.`,'Settlement is confirmed. Preparing the evidence of what actually happened.'],receipt:['04 / RECEIPT',`${m.price} paid. Nothing more.`,m.verified?`${m.historicalInvoice?m.historicalInvoice+' was blocked. ':''}Agreement verified. Payment matched. Settled once.`: 'Receipt created. Inspect its verification result before trusting the claims.'],rejected:['PROPOSAL REJECTED',m.failureReason,'No invalid proposal was accepted. Retry the current turn or choose another seller.'],stopped:['AUTHORITY STOPPED','New commitments are disabled.','The recorded proposals remain inspectable. No new signature can be created.'],refunded:['REFUNDED','Escrow returned to the buyer.','No seller payment is shown. Inspect the actual refund receipt.'],cancelled:['CANCELLED','This transaction is closed.','Start another story when you are ready to delegate.']};
 const [tag,title,detail]=copy[m.phase];return {tag,title,detail};
}
function graph(m,motion=[]){
 const n=m.nodes;
 const quote=id=>m.quotes.find(q=>q.name.toLowerCase()===id)?.price;
 const selected=m.activeSeller.toLowerCase();
 const edgeMarkup=edges.map(([from,to,path])=>{
  const branch=['atlas','nexus','orbit'].includes(from)&&to==='authority';
  const branchBlocked=branch&&quote(from)>Math.min(m.budget,m.limit);
  const done=branch?n[from]:n[from]&&n[to]&&!(from==='authority'&&m.authorityBlocked)&&!(from==='agreement'&&!m.paid);
  const active=done&&(!branch||from===selected||branchBlocked);
  const blocked=(branchBlocked||to==='agreement'&&m.mismatch)&&done;
  return `<g class="story-edge ${active?'done':''} ${blocked?'blocked':''} ${motion.includes(to)&&active?'edge-arrive':''}" data-edge="${from}-${to}" data-confirmed="${!!active}"><path d="${path}" marker-end="url(#story-arrow)"/><path class="edge-packet" d="${path}"/></g>`;
 }).join('');
 const status=id=>n[id]?'confirmed':'pending';
 const node=(id,label,value,sub='',extra='')=>{const [x,y]=positions[id];return `<button type="button" data-story-inspect="${id}" class="graph-node node-${id} ${status(id)} ${extra} ${motion.includes(id)&&n[id]?'node-arrive':''}" style="--x:${x/12.4}%;--y:${y/5.7}%" aria-label="Inspect ${e(label)}: ${e(String(value).replace(/<[^>]*>/g,' ').replaceAll('&gt;','>').replaceAll('&lt;','<').trim()||'Agent')}"><span class="node-label">${label}</span><strong>${value}</strong>${sub?`<small>${sub}</small>`:''}</button>`;};
 const terms=m.packets.map(p=>`<span><small>${e(p.actor)}</small><b>${e(p.price)}</b></span>`).join('<i>→</i>');
 return `<div class="transaction-graph" aria-label="Transaction graph: Human mandate, agent negotiation, two gates, settlement and receipt">
 <svg class="graph-connections" viewBox="0 0 1240 570" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="story-arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="#a4b7d8"/></marker></defs>${edgeMarkup}<text x="760" y="275">AI NEGOTIATES</text><text x="472" y="418">CODE AUTHORIZES</text><text x="994" y="555">EVIDENCE EXPLAINS</text></svg>
 ${node('human','HUMAN','You','Spending authority','human-node')}
 ${node('mandate','01 · MANDATE',n.mandate?'Delegated':'40 / 30',n.mandate?'Budget '+m.budget+' · max '+m.limit:'Draft · not delegated')}
 ${node('buyer','BUYER AGENT',orb('buyer'),'Acts within your mandate')}
 ${node('discovery','SELLER DISCOVERY',m.hasQuotes?'Offers received':'Request for quotes',m.hasQuotes?m.quotes.filter(q=>q.price!=null).length+' agent'+(m.quotes.filter(q=>q.price!=null).length===1?'':'s'):m.nodes.mandate?'Awaiting offers':'Awaiting delegation')}
 ${['atlas','nexus','orbit'].map(id=>node(id,id.toUpperCase(),`${orb('seller')}<span>${quote(id)??'—'}</span>`,m.isLive&&m.busy&&['live-offer','live-respond'].includes(m.pending?.action)&&m.seller===id&&!m.job?.dealId?'Thinking…':quote(id)!=null?'Offer · test units':'Awaiting offer',quote(id)>Math.min(m.budget,m.limit)?'violation':'' )).join('')}
 ${node('authority','GATE 1 · AUTHORITY',m.authorityBlocked?`${m.proposed} &gt; ${Math.min(m.budget,m.limit)}`:m.historicalAuthority?`${m.historicalAuthority} &gt; ${Math.min(m.budget,m.limit)}`:m.hasQuotes?m.negotiated||m.price!=null?'Within authority':'Check commitment':'Can it commit?',m.authorityBlocked?'BLOCKED · No funds moved':m.stopped?'Authority revoked':m.historicalAuthority?m.price!=null||m.proposed!=null?`Rejected · ${m.price??m.proposed} within limit`:'Earlier offer rejected':'Budget · limit · seller · expiry',m.authorityBlocked||m.historicalAuthority?'gate-node violation':'gate-node')}
 ${node('negotiation','NEGOTIATION',terms?`<span class="term-packets">${terms}</span>`:'Buyer ↔ '+m.activeSeller,m.rejected?'PROPOSAL REJECTED':m.negotiated?'Actual recorded terms':'Awaiting proposals',m.rejected?'violation':'')}
 ${node('deal','02 · '+(m.signatures?'SIGNED DEAL':'DEAL'),m.price??'—',m.signatures?'<span class="signature-pair"><span>✓ Buyer</span><span>✓ Seller</span></span>':m.price!=null?'Committed terms':'Two signatures required','deal-node')}
 ${node('escrow','ESCROW',m.funded?m.paid||m.phase==='refunded'?'Released':m.price:'—',m.funded?m.paid?'Paid as agreed':'Confirmed · test units':'Awaiting signed deal',m.funded&&!m.paid?'escrow-node':'')}
 ${node('delivery','DELIVERY',m.delivery?m.job.output.length+' records':'—',m.delivery?m.valid?'✓ Acceptance checks passed':'Checks failed':'Source-table worker',m.delivery&&!m.valid?'violation':'')}
 ${node('invoice','SELLER INVOICE',m.invoice??'—',m.historicalInvoice&&!m.mismatch?`${m.historicalInvoice} rejected → ${m.invoice} corrected`:m.invoice!=null?'Claim · test units':'Awaiting delivery',m.mismatch?'violation':'')}
 ${node('agreement','GATE 2 · AGREEMENT',m.invoice!=null?`${m.invoice} ${m.mismatch?'≠':'='} ${m.price}`:'Does it match?',m.mismatch?'PAYMENT BLOCKED':m.matched?m.historicalInvoice?`${m.historicalInvoice} ≠ ${m.price} was blocked`:'Amount + delivery matched':'Amount · recipient · signed terms','gate-node '+(m.mismatch?'violation':m.matched?'success':''))}
 ${node('settlement','SETTLEMENT',m.paid?m.price:'—',m.paid?m.activeSeller+' paid · test units':'No payment confirmed',m.paid?'success':'')}
 ${node('receipt','03 · RECEIPT',m.verified?'Verified ✓':m.receiptReady?'Created':'—',m.verified?'Payment matched · settled once':'What actually happened',m.verified?'success':'')}
 </div>`;
}
export function renderPresentation(state){
 const m=presentationModel(state),h=headline(m),s=state.story??{};
 const step=m.receiptReady?4:m.delivery||m.funded||m.price!=null?3:m.negotiated?2:m.hasQuotes?1:0;
 const liveDisabled=m.isLive&&(!m.session&&!m.liveAvailable||m.attempts>=8&&['live-offer','live-counter','live-respond'].includes(m.action)||m.liveRemaining===0&&!m.session);
 const detail=m.isLive&&!m.job?.dealId?'#live':m.job?'#task/'+m.job.id:'#workspace';
 return `<div class="story-shell ${s.reduceMotion?'motion-reduced':''}"><header class="story-nav"><a class="brand" href="#overview"><span class="brand-symbol">a</span>accord lock</a><nav aria-label="Product views"><a href="${m.isLive?'#presentation-live':'#presentation'}" aria-current="page">Presentation</a><a href="${detail}">Detailed Deal Room ↗</a><a href="#evidence">Proof</a></nav><div class="story-mode" aria-label="Execution mode"><a href="#presentation" ${!m.isLive?'aria-current="page"':''}>Guided Demo</a><a href="#presentation-live" ${m.isLive?'aria-current="page"':''}>Live Agents</a></div></header>
 <main id="main" class="story-main"><div class="story-mode-label ${m.isLive?'live-label':''}"><b>${m.isLive?'LIVE · Kiln · qwen3-32b':'GUIDED DEMO'}</b><span>${m.isLive?'Actual model calls · No replayed answers':'Deterministic demonstration · Four decisions'}</span><span>${m.isLive&&!m.session?(m.liveAvailable?'Kiln connected · ':'Live service unavailable · '):''}No real funds · Private EVM</span></div>
 <section class="story-heading" aria-live="polite"><div><span class="eyebrow">${e(h.tag)}</span><h1>${e(h.title)}</h1><p>${e(h.detail)}</p></div><button class="story-inspect" data-story-inspect="all">Inspect transaction ↗</button></section>
 <section class="story-finances" aria-label="Fixed financial summary">${[['Human authority',m.budget],['Max / deal',m.limit],['Signed deal',m.price??'—'],['Invoice',m.invoice??'—']].map(([label,value],i)=>`<div class="${i===3&&m.mismatch?'violation':''}"><span>${label.toUpperCase()}</span><strong>${value}</strong>${i===0?'<small>Set by you</small>':i===2?'<small>Both sides commit</small>':''}</div>`).join('')}
 <div class="story-comparisons">${m.invoice!=null?`<span class="${m.invoice<=m.budget?'success':'violation'}"><b>${m.invoice} ${m.invoice<m.budget?'&lt;':m.invoice===m.budget?'=':'&gt;'} ${m.budget}</b> ${m.invoice<=m.budget?'ALLOWED BY BUDGET':'OVER BUDGET'}</span><span class="${m.mismatch?'violation':m.matched?'success':''}"><b>${m.invoice} ${m.mismatch?'≠':'='} ${m.price}</b> ${m.mismatch?'BLOCKED BY AGREEMENT':'MATCHED TO AGREEMENT'}</span>`:`<span>AI negotiates.</span><span><b>Code authorizes.</b> Evidence explains.</span>`}</div></section>
 <div id="error" class="notice danger" role="alert" hidden></div><div id="operation" class="story-operation" role="status" ${m.busy?'':'hidden'}>${e(m.pending?.label??'Waiting for response…')}</div>
 ${graph(m,s.motionNodes)}
 <section class="story-decision"><div class="story-step"><span>${m.isLive?'LIVE':String(Math.min(step+1,4)).padStart(2,'0')}</span><div><strong>${m.isLive?'You control the next commitment':step===4?'The transaction is explained':'Four decisions. One protected transaction.'}</strong><small>${m.isLive?`${m.attempts} / 8 model calls · proposals cannot move funds`:step===4?'Inspect the verified receipt':['Delegate task','Let Buyer negotiate','Approve signed Deal','Pay corrected invoice'][Math.min(step,3)]}</small></div></div><div class="story-actions">
 ${m.isLive&&!m.job?.dealId&&m.session&&!m.session.agreement&&!m.stopped?`<label class="story-seller">Seller <select id="story-seller" aria-label="Seller" ${m.busy?'disabled':''}>${['atlas','nexus','orbit'].map(id=>`<option value="${id}" ${id===m.seller?'selected':''}>${sellerNames[id]}</option>`).join('')}</select></label>`:''}
 ${m.canSign?b('story-live-agree','Accept & sign terms',false,m.busy):''}
 ${m.isLive&&!m.session?b('connect-live','Refresh connection',false,m.busy):''}${m.isLive&&m.session&&!m.job?.dealId?b('live-refresh','Refresh state',false,m.busy):''}
 ${m.action?b('story-'+m.action,(m.busy?'Working…':e(m.actionLabel))+' →',true,m.busy||liveDisabled):b('story-inspect-proof','Inspect technical proof ↗',true)}
 ${m.session&&!m.job?.dealId&&!m.session.stopped?b('live-stop','Stop agents',false,!!state.live?.current?.authorization):''}
 ${step===4||m.stopped||m.attempts>=8||['refunded','cancelled'].includes(m.phase)?b('story-new','New story'):''}
 </div></section><footer class="story-footer"><label class="motion-preference"><input id="story-motion" type="checkbox" ${s.reduceMotion?'checked':''}> Reduce motion</label><span>MANDATE <i>→</i> DEAL <i>→</i> RECEIPT</span><span>${m.isLive?'Source-table delivery · Actual Kiln negotiation':'Deterministic agents · Real private-EVM execution'} · <a href="#evidence">Historical Sepolia proof is separate ↗</a></span></footer></main></div>`;
}

export function presentationInspect(node,state){
 const m=presentationModel(state),job=m.job;
 const turns=m.session?.messages??job?.liveSession?.messages;
 const label={human:'Human authority',mandate:'Mandate',authority:'Authority Gate',agreement:'Agreement Gate',receipt:'Receipt',delivery:'Delivery evidence'}[node]??'Buyer ↔ '+m.activeSeller;
 const conversation=turns?turns.map(t=>`<article><b>${e(sellerNames[t.actor])} · ${e(t.quote.action)}</b><strong>${t.quote.price} test units</strong><p>${t.quote.rows} records · ${t.quote.sources} sources · ${t.quote.deliveryMinutes} min</p><p translate="no">${e(t.quote.message)}</p><small class="original-message-label" data-original-label>Original message · preserved as received</small><details><summary>Inspect model evidence</summary><p>Model: ${e(t.model)}</p><p class="hash">Request ID: ${e(t.requestId)}</p><pre>${e(JSON.stringify({publicInput:t.input,output:t.quote,usage:t.usage},null,2))}</pre></details></article>`).join(''):(job?.events??[]).filter(ev=>['buyer','seller-a','seller-b','seller-c'].includes(ev.actor)).map(ev=>`<article><b>${e(sellerNames[ev.actor])}</b><strong>${e(ev.title)}</strong><p>${e(ev.detail)}</p></article>`).join('');
 return `<section class="story-detail"><span class="eyebrow">INSPECT TRANSACTION · ${m.isLive?'LIVE':'GUIDED'}</span><h2>${label}</h2><p>${job?e(job.title):'Delegate a task to create a transaction.'}</p>
 ${['human','mandate','authority','all'].includes(node)?`<dl><dt>Human budget</dt><dd>${m.budget}</dd><dt>Maximum per deal</dt><dd>${m.limit}</dd><dt>Authority Gate</dt><dd>Budget · per-deal limit · permitted seller · expiry · revocation</dd></dl><p>Is the agent allowed to make this commitment?</p>`:''}
 ${['agreement','deal','receipt','all'].includes(node)?`<dl><dt>Signed deal</dt><dd>${m.price??'Not signed'}</dd><dt>Invoice</dt><dd>${m.invoice??'Not received'}</dd><dt>Agreement Gate</dt><dd>Amount · recipient · deal hash · signed terms · supported delivery conditions</dd></dl><p>Is this payment what both sides committed to?</p>`:''}
 ${node==='delivery'&&job?.output?`<pre>${e(JSON.stringify(job.output,null,2))}</pre>`:''}
 <div class="story-detail-conversation">${conversation||'<p>No recorded negotiation yet.</p>'}</div>
 ${m.isLive?`<details><summary>Inspect rejected attempts & usage</summary><pre>${e(JSON.stringify(state.live?.current?.attemptLog??[],null,2))}</pre></details>`:''}
 <div class="review-tools">${b('story-inspect-proof','Inspect technical proof ↗')}${job?.output?b('download-json','Download result'):''}${job?.dealId?b('receipt','Download receipt ↓')+b('verify','Verify receipt'):''}</div>
 ${job?.events?.length?`<details><summary>Inspect full event timeline</summary><ol>${job.events.map(ev=>`<li><strong>${e(ev.title)}</strong><p>${e(ev.detail)}</p></li>`).join('')}</ol></details>`:''}
 <p class="trust-note">Current execution: private EVM test units. Historical public Sepolia evidence is separate.</p><a href="${m.isLive&&!job?.dealId?'#live':job?'#task/'+job.id:'#workspace'}">Open Detailed Deal Room ↗</a></section>`;
}
