import {presentationModel,sellerNames} from './presentation-model.mjs';
import {translate} from './i18n.mjs';
import {liveSessionExpired,expiredSessionNotice} from './live-session.mjs';

const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eventMoney=text=>String(text).replace(/(\d+) test units/g,'$$$1 test USD').replace(/(the |your )(\d+)( per-deal)/g,'$1$$$2$3').replace(/(negotiate |accept |can do |agreement: )(\d+)/g,'$1$$$2');
export const money=v=>v==null?'—':'$'+Number(v).toLocaleString('en-US');
export const defaultPolicy={title:'Quarterly CAPEX research',brief:'Normalize quarterly facility-investment data into a clean table. Preserve company, quarter, value, currency and source URL for every row.',budget:40,perDeal:30,deliveryMinutes:10};
export function preparedDemoPrompt(policy=defaultPolicy,language='en') {
 return translate('Find four source-linked CAPEX records. My total budget is {0} test USD, with a maximum of {1} test USD per deal. Deliver within {2} minutes. Negotiate with the sellers and ask me before committing funds.',language)
  .replace('{0}',money(policy.budget)).replace('{1}',money(policy.perDeal)).replace('{2}',policy.deliveryMinutes);
}
// Narration is derived only from persisted events. It never creates agent turns.
export function guidedDialogue(ev,job) {
 if(ev.title==='Requested offers'){const terms=ev.detail.match(/(\d+) source rows; (\d+) test units/);if(terms)return `I need ${terms[1]} source-linked records. My limit is ${money(terms[2])} test USD per deal. Sellers, what can you offer?`;}
 if(/ offered /.test(ev.title)){
  const price=ev.title.match(/offered (\d+)/)?.[1];
  const priority={'seller-a':'I prioritize source coverage and consistent data.','seller-b':'I prioritize fast delivery.','seller-c':'I prioritize research quality and source detail.'}[ev.actor];
  if(price&&priority)return `${priority} My offer is ${money(price)} test USD for the complete task.`;
 }
 if(ev.title.startsWith('Counteroffer:'))return `Can you do the same scope for ${money(ev.title.match(/: (\d+)/)?.[1])} test USD? Keep all required sources.`;
 return eventMoney(ev.detail);
}
const eventRecord=ev=>`<details class="event-record"><summary>View original record</summary><dl><dt>Recorded at</dt><dd>${e(ev.at)}</dd><dt>Event ID</dt><dd class="hash">${e(ev.id)}</dd></dl><pre>${e(JSON.stringify(ev,null,2))}</pre></details>`;
export function purchaseInspection(state,section='all') {
 const m=presentationModel(state),j=m.job,events=j?.events??[],detail=section==='details';
 const incidents=events.filter(ev=>/blocked/i.test(ev.title));
 const list=section==='authority'?incidents.filter(ev=>/offer|authority/i.test(ev.title)):section==='agreement'?incidents.filter(ev=>/invoice|overcharge/i.test(ev.title)):events;
 return `<section class="purchase-inspection" tabindex="-1"><div class="inspection-header"><div><span class="eyebrow">${m.isLive?'LIVE':'GUIDED DEMO'} · TEST USD</span><h2>${section==='details'?'Detailed Deal Room':'Saved evidence'}</h2></div><button class="button" data-purchase-view="chat">Back to conversation</button></div><p>${detail?'Current terms, delivery and available transaction actions.':'Recorded history: conversations, gate incidents and original evidence.'}</p>${detail?`<div class="inspection-finances"><span>Human budget <b>${money(m.budget)}</b></span><span>Signed deal <b>${money(m.price)}</b></span><span>Seller invoice <b>${money(m.invoice)}</b></span><span>Seller received <b class="money-in">${money(m.paid?m.price:0)}</b></span></div>`:''}${!detail?'<p class="record-boundary">Conversation and incident records are stored in this browser. They are not independently signed receipts. Technical proof separately verifies the agreement and settlement.</p>':''}
 ${detail?`<div class="current-terms"><h3>Current terms</h3><p translate="no">${e(j?.brief??m.session?.request?.brief??state.story?.policy?.brief??defaultPolicy.brief)}</p><dl><dt>Seller</dt><dd>${e(m.activeSeller)}</dd><dt>Delivery deadline</dt><dd>${j?.deliveryMinutes??m.session?.request?.deliveryMinutes??state.story?.policy?.deliveryMinutes??10} min</dd><dt>Signed terms</dt><dd>${m.signatures?'Buyer + seller signed':'No bilateral signature confirmed'}</dd></dl>${button('purchase-policy','Edit your policy',false,m.busy)}</div>`+executionFlow(m):''}
 ${!j&&!m.session?'<p>No recorded negotiation yet.</p>':''}
 ${!detail&&list.length?`<div class="record-list">${list.map(ev=>`<article class="record-card ${/blocked/i.test(ev.title)?'record-blocked':''}"><span>${e(sellerNames[ev.actor]??(ev.actor==='human'?'You':'Accord'))}</span><h3>${e(eventMoney(ev.title))}</h3><p>${e(eventMoney(ev.detail))}</p>${eventRecord(ev)}</article>`).join('')}</div>`:''}
 ${!detail&&m.isLive?`<details><summary>Inspect model evidence</summary><p>Original model messages and request evidence are preserved as received.</p><pre>${e(JSON.stringify({messages:m.session?.messages??j?.liveSession?.messages??[],attempts:state.live?.current?.attemptLog??[]},null,2))}</pre></details>`:''}
 ${j?.output?`<details><summary>Delivery evidence</summary><pre>${e(JSON.stringify({output:j.output,validation:j.validation},null,2))}</pre></details>`:''}
 <div class="review-tools">${j||m.session?button('story-inspect-proof','Inspect technical proof ↗'):''}${j?.output?button('download-json','Download result'):''}${j?.dealId?button('receipt','Download receipt ↓')+button('verify','Verify receipt'):''}${button('purchase-export','Export conversation & incidents',false,!j&&!m.session)}</div><p>Current execution: private EVM. Historical Sepolia evidence is separate.</p></section>`;
}
const bot=(kind='seller')=>`<span class="purchase-avatar ${kind}" aria-hidden="true"><i></i><i></i></span>`;
const button=(action,text,primary=false,disabled=false)=>`<button type="button" class="button ${primary?'primary':''}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
const brand='<a class="product-brand" href="#home"><span class="lock-logo" aria-hidden="true"></span>Accord Lock</a>';

export function renderHome(){
 return `<div class="product-home"><header class="home-nav">${brand}<nav aria-label="Main navigation"><a href="#home" data-home-section="solution">Product</a><a href="#home" data-home-section="technology">Technology</a><a href="#home" data-home-section="roadmap">Roadmap</a><a href="#evidence">Proof ↗</a></nav><a class="button primary" href="#presentation">Get started →</a></header>
 <main id="main"><section class="home-hero"><div class="home-copy"><span class="eyebrow">THE AGREEMENT DECIDES WHAT GETS PAID.</span><h1>AI agents negotiate.<br><em>You stay in control.</em></h1><p>Give your buyer a task and a budget. Watch agents negotiate. Accord Lock makes sure the payment matches the deal they signed.</p><div class="home-ctas"><a href="#presentation" class="button primary"><span>▷</span><div>Try Demo<small>Set your rules. Explore safely.</small></div></a><a href="#playground" class="button"><span>◉</span><div>Go Live<small>Talk to real Kiln agents.</small></div></a></div><p class="home-note">No real funds. Prices such as $40, $25 and $15 are examples in test USD.</p></div>
 <div class="home-preview" aria-label="Illustrative transaction, not a live session"><div class="preview-title"><span><i class="status-dot"></i> A transaction you can trust</span><b>ILLUSTRATION</b></div><div class="preview-body"><div class="preview-chat"><div class="preview-line">${bot('buyer')}<div><strong>Your buyer</strong><p>Find a sourced dataset.<br>Stay within my $30 limit.</p></div></div><div class="preview-line">${bot()}<div><strong>Atlas · Seller</strong><p>I can deliver it for <b>$20.</b></p></div></div><div class="preview-deal"><span>01 MANDATE</span><i>→</i><span>02 DEAL</span><i>→</i><span>03 RECEIPT</span></div><div class="preview-incident"><b>Invoice $25 · Payment paused</b><p>$25 fits the $40 budget.<br>It does not match the $20 deal.</p><span>Agreement Gate protected your payment.</span></div><div class="preview-caption">AI negotiates. Code authorizes. Evidence explains.</div></div><aside><span>YOUR POLICY</span><dl><dt>Total budget</dt><dd>$40</dd><dt>Max / deal</dt><dd>$30</dd><dt>Signed deal</dt><dd>$20</dd></dl><div class="preview-receipt"><span>AFTER CORRECTION</span><strong>✓ $20 paid</strong><p>Agreement verified.<br>Receipt saved.</p></div><small>Test USD · No cash value</small></aside></div></div></section>
 <section class="home-pillars" aria-label="Product overview"><article id="pain"><span class="pillar-icon red">!</span><h2>The pain point</h2><p>A budget is not an agreement.</p><ul><li>An affordable invoice can still be an overcharge.</li><li>Agents can change terms between negotiation and payment.</li><li>A chat log alone does not explain what was authorized.</li></ul></article><article id="solution"><span class="pillar-icon blue">✓</span><h2>The solution</h2><p>Two gates. One accountable payment.</p><ul><li>Authority Gate checks the human mandate.</li><li>Agreement Gate checks the signed deal.</li><li>A receipt connects the terms, delivery and payment.</li></ul></article><article id="technology"><span class="pillar-icon blue">⌘</span><h2>The technology</h2><p>Inference proposes. Code decides.</p><ul><li>Actual Kiln inference with qwen3-32b.</li><li>Bilateral signatures and exact-amount escrow checks.</li><li>Inspectable receipts; separate historical Sepolia evidence.</li></ul></article><article id="roadmap"><span class="pillar-icon green">↗</span><h2>Future expansion</h2><p>Furiosa × Bricksum</p><ul><li>Explore Furiosa NPU inference for efficient agent commerce.</li><li>Extend assurance into Bricksum payment infrastructure.</li><li>Grow from sourced data to broader digital services.</li></ul><small>Roadmap direction · not a claim of deployed integrations.</small></article></section>
 <footer class="home-footer"><span>Transaction assurance for agent-to-agent commerce.</span><strong>FURIOSA <i>×</i> bricksum</strong></footer></main></div>`;
}

export function policyForm(state){
 const p=state.job??state.story?.policy??defaultPolicy;
 const locked=!!state.job?.liveSessionId||!!state.job?.dealId||state.job?.authorityRevoked;
 return `<section class="policy-editor"><span class="eyebrow">YOUR AUTHORITY</span><h2>${locked?'Policy for a new purchase':'Edit your policy'}</h2><p>${locked?'The existing mandate stays unchanged. These settings start a separate purchase.':'Your limits control the real validation, including in Demo.'}</p><form id="purchase-policy-form"><label>Task title<input name="title" required minlength="3" maxlength="100" value="${e(p.title)}"></label><label>Task brief<textarea name="brief" required minlength="10" maxlength="4000" rows="3">${e(p.brief)}</textarea></label><div class="policy-fields"><label>Total budget · test USD<input name="budget" type="number" min="1" max="1000000" step="1" required value="${p.budget}"></label><label>Max / deal · test USD<input name="perDeal" type="number" min="1" max="1000000" step="1" required value="${p.perDeal}"></label></div><label>Delivery deadline · minutes<input name="deliveryMinutes" type="number" min="8" max="60" step="1" required value="${p.deliveryMinutes}"></label><p>Test USD has no cash value. The sample includes four source-linked records. Use Detailed Deal Room for your own source file.</p><button class="button primary" type="submit">${locked?'Use for a new purchase':'Save policy'}</button><p id="policy-error" role="alert"></p></form></section>`;
}

function talk(actor,text,{label='',at='',kind='',id=''}={}){
 return `<article class="purchase-message ${kind}" ${id?`data-message-id="${e(id)}"`:''}>${actor==='You'?'<span class="human-avatar">H</span>':bot(actor==='Buyer'?'buyer':actor==='Accord'?'system':'seller')}<div><div class="message-by"><strong>${e(actor)}</strong><span>${e(label)}</span>${at?`<time>${new Date(at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</time>`:''}</div><div class="purchase-bubble">${text}</div></div></article>`;
}
export function purchaseMessages(m,s){
 const j=m.job,notes=s.messages??[],out=[];
 if(!j&&!m.session)return `<div class="purchase-welcome"><span class="welcome-mark">↗</span><h2>${m.isLive?'What should your buyer find?':s.demoStarted?'Your request is ready.':'A buyer. Three sellers. Your rules.'}</h2><p>${m.isLive?'Your message goes to real Kiln agents.':s.demoStarted?'Review the prepared prompt below, then send it to your buyer.':'Start the demo, send a prepared request, and follow the agents. You decide what happens when a gate blocks the transaction.'}</p><div class="participant-key"><span>${bot('buyer')} Buyer agent</span><span>${bot()} Seller agents 1 · 2 · 3</span></div>${!m.isLive&&!s.demoStarted?button('purchase-start-demo','Start demo →',true):''}<small>${m.isLive?'Actual Kiln calls · No replayed answers':'Demo uses deterministic agents; no LLM call or real money.'}</small></div>`;
 const request=m.session?.request??j;
 out.push({at:j?.createdAt??m.session?.createdAt,html:talk('You',`<span translate="no">${e(request.brief)}</span>`,{label:'Task delegated',at:j?.createdAt??m.session?.createdAt,kind:'human-message'})});
 for(const note of notes)out.push({at:note.at,html:talk('You',`<span translate="no">${e(note.text)}</span>`,{label:note.label??'Instruction',at:note.at,kind:'human-message',id:note.id})});
 if(m.isLive){
  for(const t of m.session?.messages??j?.liveSession?.messages??[]){out.push({at:t.at,html:talk(sellerNames[t.actor],`<b>${e(t.quote.action)} · ${money(t.quote.price)} <small>test USD</small></b><p translate="no">${e(t.quote.message)}</p><small class="original-message-label" data-original-label>Original message · preserved as received</small><span>${t.quote.rows} records · ${t.quote.sources} sources · ${t.quote.deliveryMinutes} min</span>`,{label:'Kiln agent',at:t.at,id:'live-'+t.sequence})});}
 }
 for(const ev of j?.events??[]){
  if(['Task created','Live negotiation started'].includes(ev.title))continue;
  if(m.isLive&&/^(atlas|nexus|orbit|buyer) (offer|accept|decline):/.test(ev.title))continue;
  const actor=ev.actor==='human'?'You':sellerNames[ev.actor]??'Accord';
  const incident=/blocked/i.test(ev.title);
  out.push({at:ev.at,html:talk(actor,`<b>${e(eventMoney(ev.title))}</b><p>${e(m.isLive?eventMoney(ev.detail):guidedDialogue(ev,j))}</p>${incident?'<span class="saved-tag">◈ Gate incident saved</span>':''}${eventRecord(ev)}`,{label:incident?'Protection event':m.isLive?'Execution event':'Guided narration · recorded event',at:ev.at,kind:incident?'incident-message':'',id:ev.id})});
 }
 out.sort((a,b)=>new Date(a.at)-new Date(b.at));
 if(m.busy)out.push({html:talk(m.isLive?m.pending?.action==='live-counter'?'Buyer':m.activeSeller:'Accord',`<span class="thinking-dots" aria-hidden="true">•••</span> ${e(m.pending?.label??'Processing the current request…')}`,{label:m.isLive?'Actual request in progress':'Applying your decision'})});
 return out.map(x=>x.html).join('');
}

function incident(m){
 if(m.authorityBlocked)return `<section class="purchase-incident" role="status"><span>Ⅱ PAUSED · AUTHORITY GATE</span><h2>${money(m.proposed)} exceeds your ${money(Math.min(m.budget,m.limit))} limit.</h2><p>No signature. No escrow. No funds moved. Negotiate a lower price or edit your policy.</p><p class="incident-next">Next: ask the buyer to negotiate within your limit.</p><button data-story-inspect="authority">Why blocked & what was saved ↗</button></section>`;
 if(m.mismatch)return `<section class="purchase-incident" role="status"><span>Ⅱ PAUSED · AGREEMENT GATE</span><h2>The invoice changed. Your agreement did not.</h2><div class="gate-comparison"><b class="money-in">${money(m.invoice)} ${m.invoice<=m.budget?'≤':'>'} ${money(m.budget)} <small>${m.invoice<=m.budget?'Within budget':'Over budget'}</small></b><b>${money(m.invoice)} ≠ ${money(m.price)} <small>Payment blocked</small></b></div><p>Escrow stays locked. Review this saved incident before approving anything.</p><p class="incident-next">Next: correct the invoice to the signed amount before payment.</p><button data-story-inspect="agreement">Why blocked & what was saved ↗</button></section>`;
 if(m.rejected)return `<section class="purchase-incident" role="alert"><span>PROPOSAL REJECTED</span><h2>${e(m.failureReason)}</h2><p>The failed attempt is recorded. Retry or switch seller; no success has been invented.</p><button data-story-inspect="all">Inspect rejected attempt ↗</button></section>`;
 if(m.verified)return `<section class="purchase-success"><span>✓ RECEIPT VERIFIED</span><h2>${money(m.price)} paid. Exactly as agreed.</h2><p>Agreement verified · Payment matched · Settled once</p><button data-story-inspect="receipt">Inspect receipt ↗</button></section>`;
 return '';
}

function executionFlow(m){
 const cards=[['mandate','01 · MANDATE',m.nodes.mandate?'Delegated':'Not delegated',`${money(m.budget)} budget · ${money(m.limit)} max`],['authority','02 · AUTHORITY GATE',m.authorityBlocked?'Blocked':m.hasQuotes?'Quotes checked':'Awaiting offers',m.historicalAuthority?`${money(m.historicalAuthority)} exceeded authority`:'Budget · seller · expiry'],['negotiation','03 · NEGOTIATION',m.packets.map(p=>money(p.price)).join(' → ')||'Awaiting terms','Buyer ↔ '+m.activeSeller],['deal','04 · DEAL',money(m.price),m.signatures?'Buyer + seller signed':'No bilateral signature confirmed'],['escrow','05 · ESCROW',m.funded?m.paid?'Released':money(m.price):'Not funded','Confirmed transactions only'],['delivery','06 · DELIVERY',m.delivery?m.job.output.length+' records':'Awaiting work',m.valid?'Acceptance checks passed':'Source-linked evidence'],['agreement','07 · AGREEMENT GATE',m.invoice==null?'Awaiting invoice':money(m.invoice)+(m.mismatch?' ≠ ':' = ')+money(m.price),m.mismatch?'Payment blocked':m.matched?'Invoice matched':'Signed terms decide payment'],['settlement','08 · SETTLEMENT',m.paid?money(m.price)+' paid':'No payment',m.activeSeller+' receives confirmed payment'],['receipt','09 · RECEIPT',m.verified?'Verified':m.receiptReady?'Created':'Awaiting settlement','Evidence explains what happened']];
 return `<section class="execution-view"><div class="execution-intro"><span class="eyebrow">TRANSACTION PATH · TEST USD</span><h2>Every step follows the actual transaction.</h2><p>Click a step to inspect the recorded evidence. Future steps stay pending.</p></div><div class="execution-grid">${cards.map(([id,title,value,sub])=>`<button class="execution-card ${m.nodes[id]?'confirmed':'pending'} ${id==='authority'&&m.authorityBlocked||id==='agreement'&&m.mismatch?'violated':''}" data-story-inspect="${id}" data-confirmed="${!!m.nodes[id]}"><span>${title}</span><strong>${e(value)}</strong><small>${e(sub)}</small></button>`).join('')}</div></section>`;
}

export function renderPurchase(state){
 const s=state.story??{},m=presentationModel(state),p=m.job??m.session?.request??s.policy??defaultPolicy;
 const budget=p.budget,limit=p.perDeal,spent=m.paid?m.price:0,escrow=m.funded&&!m.paid&&m.phase!=='refunded'?m.price:0,remaining=Math.max(0,budget-spent-escrow);
 const detail=m.isLive&&!m.job?.dealId?'#live':m.job?'#task/'+m.job.id:'#workspace';
 const expired=m.isLive&&!m.job?.dealId&&liveSessionExpired(state.live?.current);
 const disabled=expired||m.busy||m.stopped||m.isLive&&(m.attempts>=8||!m.session&&!m.liveAvailable);
 const canChat=!expired&&!m.price&&!m.funded&&!m.stopped;
 const view=s.view??'chat';
 const notes=s.messages??[];
 return `<div class="purchase-app ${s.showPolicy?'policy-visible':''} ${s.chatExpanded?'chat-expanded':''} ${s.reduceMotion?'motion-reduced':''}"><aside class="purchase-sidebar">${brand}<p>The agreement decides<br>what gets paid.</p>${button('purchase-new','＋ New purchase',true,m.busy)}<nav aria-label="Workspace views"><button data-purchase-view="chat" class="${view==='chat'?'active':''}">◌ Conversation</button><button data-purchase-view="flow" class="${view==='flow'?'active':''}">⌘ Execution flow</button><button data-story-inspect="all" class="${view==='evidence'?'active':''}">◇ Saved evidence</button><button data-purchase-view="details" class="${view==='details'?'active':''}">↗ Detailed Deal Room</button><a href="#evidence">◈ Historical proof</a></nav><div class="sidebar-money"><span>THIS PURCHASE · TEST USD</span><strong class="money-out">−${money(spent)} <small>spent</small></strong><div class="spend-track"><i style="width:${Math.min(100,spent/budget*100)}%"></i></div><p>${money(remaining)} uncommitted authority</p></div><a class="back-home" href="#home">← Back to product</a></aside>
 <div class="purchase-center"><header class="purchase-top"><button class="policy-toggle" data-action="purchase-toggle-policy" aria-expanded="${!!s.showPolicy}">${s.showPolicy?'Hide policy & balances':'Policy & balances'}</button><button class="chat-expand" data-action="purchase-expand" aria-pressed="${!!s.chatExpanded}">${s.chatExpanded?'↙ Show policy panels':'⤢ Expand conversation'}</button><div class="purchase-mode"><a href="#presentation" ${!m.isLive?'aria-current="page"':''}>Guided Demo</a><a href="#playground" ${m.isLive?'aria-current="page"':''}>Live Playground</a></div><span>${m.isLive?'LIVE · Kiln / qwen3-32b':'DEMO · Deterministic agents'}</span></header><main id="main"><div class="purchase-heading"><span class="eyebrow">${m.isLive?'TALK TO YOUR AGENTS':'EXPLORE AGENT COMMERCE'}</span><h1>Find it. Negotiate it.<br class="mobile-break"> We’ll lock it.</h1><p>${m.isLive?'Send your instructions. The agents respond through actual Kiln inference.':'Watch the conversation. Step in when the agreement needs you.'}</p><div class="purchase-unit">$ = test USD · No real funds <span>● ${m.job||m.session?'Progress saved':'Your policy is editable'}</span></div></div>
 <div id="error" class="notice danger" role="alert" hidden></div><div id="operation" class="purchase-operation" role="status" ${m.busy?'':'hidden'}>${e(m.pending?.label??'Processing…')}</div>
 ${['evidence','details'].includes(view)?purchaseInspection(state,view==='details'?'details':s.inspectSection??'all'):view==='flow'?executionFlow(m):`<section class="purchase-transcript" aria-label="Agent conversation">${purchaseMessages(m,s)}</section>`}
 ${m.hasQuotes&&!m.price&&view==='chat'?`<div class="purchase-quotes" aria-label="Seller offers">${m.quotes.map(q=>`<button data-purchase-seller="${q.id}" class="${q.name===m.activeSeller?'selected':''}" ${m.busy?'disabled':''}>${bot()}<b>${e(q.name)}</b><strong>${money(q.price)}</strong><small>${q.price==null?'Request an offer':q.price>Math.min(budget,limit)?'Over your limit':'Within spending limit'}</small></button>`).join('')}</div>`:''}
 ${expired?expiredSessionNotice('purchase-new'):''}${incident(m)}${m.stopped?'<div class="purchase-incident"><b>Agents stopped</b><p>New commitments are disabled. Recorded work remains inspectable.</p></div>':''}
 <section class="purchase-next story-actions" aria-label="Next transaction action">${!expired&&m.action&&(m.job||m.session)?button('story-'+m.action,e(m.actionLabel)+' →',true,m.busy||m.isLive&&!m.session&&!m.liveAvailable):m.job?button('story-inspect-proof','Inspect technical proof ↗',true):''}${!expired&&m.canSign?button('story-live-agree','Accept & sign terms',false,m.busy):''}${!expired&&m.session&&!m.session.stopped&&!m.job?.dealId?button('live-stop','Stop agents',false,!!state.live?.current?.authorization):''}${!m.isLive&&m.job&&!m.funded&&!m.stopped?button('stop','Stop buyer',false,m.busy):''}${m.isLive?button('connect-live','Refresh connection',false,m.busy):''}</section>
 ${view==='chat'&&canChat?`<form id="purchase-message-form" class="purchase-composer"><label for="purchase-message">${m.isLive?'Message the agents':'Your task / negotiation instruction'}</label><textarea id="purchase-message" name="message" rows="2" maxlength="${m.job?1200:4000}" placeholder="${m.job?m.isLive?'Ask for a lower price while preserving all source coverage…':'Add a note and choose your counteroffer below…':'Describe what your buyer should do…'}" ${disabled||!m.isLive&&!m.job&&!s.demoStarted?'disabled':''}>${e(s.composer??'')}</textarea><div>${!m.isLive&&m.job?`<label class="counter-input">Counteroffer · test USD <input name="counter" type="number" min="1" max="1000000" step="1" value="${Math.min(18,budget,limit)}" required></label>`:`<small>${m.isLive?'Sent to Kiln. Messages cannot override your policy.':'Demo runs the existing sample source-table worker.'}</small>`}<button class="button primary" type="submit" ${disabled||!m.isLive&&!m.job&&!s.demoStarted?'disabled':''}>${m.job?'Send →':'Send to Buyer agent →'}</button></div></form>`:''}
 <footer class="purchase-foot"><label><input id="story-motion" type="checkbox" ${s.reduceMotion?'checked':''}> Reduce motion</label><span>${notes.length+(m.job?.events?.length??0)+(m.session?.messages?.length??0)} saved entries</span>${button('purchase-export','Export conversation & incidents',false,!m.job&&!m.session)}</footer></main></div>
 <aside class="purchase-policy"><section><div class="card-heading"><h2>Your policy</h2>${button('purchase-policy','Edit',false,m.busy)}</div><dl><dt>Total budget</dt><dd>${money(budget)}</dd><dt>Max per transaction</dt><dd>${money(limit)}</dd><dt>Currency</dt><dd>Test USD</dd><dt>Approved sellers</dt><dd>Atlas · Nexus · Orbit</dd><dt>Delivery deadline</dt><dd>≤ ${p.deliveryMinutes} min</dd></dl><p>${m.price?'Signed terms stay immutable.':'You define the limits, including in Demo.'}</p></section><section><div class="card-heading"><h2>Current deal</h2><span class="small-status">${m.paid?'Paid':m.price?'Locked':'Not signed'}</span></div><div class="current-seller">${bot()}<div><b>${e(m.activeSeller)}</b><small translate="no">${e(p.title)}</small></div></div><dl><dt>Signed amount</dt><dd>${money(m.price)}</dd><dt>Seller invoice</dt><dd class="${m.mismatch?'money-out':''}">${money(m.invoice)}</dd><dt>In escrow</dt><dd class="money-escrow">${money(escrow)}</dd></dl><button class="view-execution" data-purchase-view="${view==='flow'?'chat':'flow'}">${view==='flow'?'Back to conversation':'View execution flow'} →</button></section><section class="money-ledger"><h2>Where the money is</h2><dl><dt>↗ Buyer spent</dt><dd class="money-out">−${money(spent)}</dd><dt>↙ Seller received</dt><dd class="money-in">+${money(spent)}</dd><dt>○ Remaining authority</dt><dd class="money-remaining">${money(remaining)}</dd></dl><p>Remaining = budget − escrow − paid.<br>Authority is a limit, not a wallet deposit.</p></section><div class="policy-trust"><b>AI negotiates.<br>Code authorizes.<br>Evidence explains.</b><p>Current execution: private EVM.<br><a href="#evidence">Historical Sepolia evidence ↗</a></p></div></aside></div>`;
}
