import {useEffect,useRef,useState} from 'react';
import './Replay.css';
import {SourceEvidence,sourceCopy,EnergyAssumptions} from './SourceEvidence';
import {RecoveryEvidence} from './RecoveryEvidence';

const legacyStages=[
 {at:0,label:'의뢰',title:'AI에게 일을 맡겼다.\n돈은 언제 보내야 할까?',line:'리서치팀의 AI가 외부 AI에게 배터리 투자 데이터 제작을 의뢰합니다.'},
 {at:15,label:'협상',title:'AI는 조건을 협상합니다.',line:'실제 Kiln 응답이 가격·행 수·출처 비율·납기를 결정합니다. 대화 자체로는 돈이 움직이지 않습니다.'},
 {at:45,label:'예치',title:'돈은 잠깐, 금고에.',line:'승인 범위를 코드로 확인한 뒤 예치합니다. 판매자는 아직 돈을 받지 않았습니다.'},
 {at:70,label:'지급',title:'약속을 지켰다. 지급한다.',line:'제출된 JSON이 계약의 구조적 조건을 통과했습니다. 예치금이 판매자에게 전달됩니다.'},
 {at:90,label:'환불',title:'40행을 약속했는데, 7행?',line:'다른 판매자의 납품 실패입니다. 별도로 승인된 두 번째 의뢰의 돈은 구매자에게 돌아옵니다.'},
 {at:115,label:'다음 거래',title:'이 실패가, 다음 거래를 바꿉니다.',line:'문제 판매자에게만 사전 샘플 검사를 추가합니다. 샘플 없이 다시 돈을 보내려 하면 코드가 막습니다.'},
 {at:135,label:'증명',title:'보지 못한 사람도,\n왜 돈이 움직였는지 알 수 있게.',line:'사람의 승인부터 계약·검수·체인 거래까지, 같은 거래의 기록으로 연결합니다.'},
 {at:155,label:'효율',title:'협상에는 AI. 검증에는 코드.',line:'이 실행에 사용한 실제 API 호출과 토큰입니다. 검사·지급 판단에는 추론이 필요하지 않습니다.'},
 {at:170,label:'완성',title:'돈을 맡겨도,\n통제까지 맡기지는 않습니다.',line:'한 번의 실패가 다음 거래를 더 엄격하게 만드는, 디지털 작업 거래의 작은 통제 장치.'},
];
const amount=(v:number)=>(v/100).toFixed(2),short=(v:string)=>v.slice(0,8);
const labels:Record<string,string>={VALID_JSON_ARRAY:'JSON 배열 형식',SOURCE_URL_COVERAGE:'출처 URL 비율',DELIVERY_DEADLINE:'납기',CAPEX_VALUE_TYPES:'금액·문자 타입',CAPEX_QUARTER_RANGE:'대상 분기',CURRENCY_FORMAT:'통화 코드 형식',UNIQUE_ECONOMIC_ROWS:'중복 없는 행',JSON_VALID:'JSON 형식',MINIMUM_ROWS:'최소 행 수',REQUIRED_COLUMNS:'필수 컬럼',SOURCE_COVERAGE:'출처 URL 비율',DEADLINE:'납기',MANDATE_ACTIVE:'사람의 승인 유효',MANDATE_NOT_EXPIRED:'승인 기한',DEAL_NOT_EXPIRED:'계약 기한',MAX_SINGLE:'건별 지출 상한',TASK_BUDGET:'작업 전체 예산',DEAL_HASH:'계약 변경 없음',SELLER_ALLOWED:'허용 판매자',PREVIEW_REQUIRED:'사전 샘플 검사'};
function MoneyPath({mode,value}:{mode:'lock'|'release'|'refund';value:number}){return <div className={`money-path ${mode}`} aria-label={mode==='lock'?'구매자에서 에스크로로 예치':mode==='release'?'에스크로에서 판매자로 지급':'에스크로에서 구매자로 환불'}><div className={mode==='refund'?'destination':''}><span className="party-icon">B</span><strong>구매자</strong><small>{mode==='refund'?'환불 완료':'Research Buyer'}</small></div><span className="money-arrow">{mode==='refund'?'←':'→'}</span><div className={mode==='lock'?'destination':'vault'}><span className="party-icon">◇</span><strong>에스크로</strong><small>{mode==='lock'?`${amount(value)} 잠금`:'조건부 보관'}</small></div><span className="money-arrow">{mode==='release'?'→':'· · ·'}</span><div className={mode==='release'?'destination':''}><span className="party-icon">S</span><strong>판매자</strong><small>{mode==='release'?'지급 완료':mode==='refund'?'지급 없음':'아직 지급 없음'}</small></div></div>;}
function TxLink({hash,network,label}:{hash:string;network:string;label:string}){return network==='sepolia'?<a className="demo-link" href={`https://sepolia.etherscan.io/tx/${hash}`} target="_blank" rel="noreferrer">{label} ↗ <span>{short(hash)}…</span></a>:<code>{label} · {hash}</code>;}
function CheckList({checks}:{checks:any[]}){return <ul className="demo-checks">{checks.map(c=><li key={c.name}><span>{labels[c.name]??c.name.replaceAll('_',' ')}</span><strong className={c.pass?'ok':'bad'}>{c.pass?'✓ 통과':'× 미달'}</strong></li>)}</ul>;}

export function Replay(){
 const [records,setRecords]=useState<any>(null),[seconds,setSeconds]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[auditChoice,setAuditChoice]=useState('a');
 const position=useRef(0);position.current=seconds;
 useEffect(()=>{const controller=new AbortController();void fetch('/api/replay',{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error??'증거를 불러오지 못했습니다.');setRecords(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{if(!playing)return;const start=performance.now()-position.current*1000;const timer=setInterval(()=>{const next=Math.min(180,(performance.now()-start)/1000);setSeconds(next);if(next>=180)setPlaying(false);},150);return()=>clearInterval(timer);},[playing]);
 const sourceMode=!!records?.a.deal.requirements.reference_dataset_id;
 const stages=sourceMode?legacyStages.map((stage,i)=>({...stage,...sourceCopy[i],...(records?.recovery?{at:[0,12,35,50,70,95,115,135,150][i]}:{}),...(records?.recovery&&i===8?{label:'직접 회수',title:'앱이 꺼져도,\n회수할 길은 남습니다.',line:'별도 미정산 의뢰에서 운영 앱을 종료했습니다. 기한이 지나자 구매자가 공개 체인에서 직접 원금을 회수했습니다.'}:{})})):legacyStages;
 const jump=(time:number)=>{setPlaying(false);setSeconds(time);},index=stages.reduce((match,x,i)=>seconds>=x.at?i:match,0),stage=stages[index];
 if(!records)return <main className="demo-loading"><p className="eyebrow">AGENT DEAL ESCROW</p><h1>{error?'검증 가능한 기록이 필요합니다.':'거래 기록을 불러오는 중…'}</h1><p role={error?'alert':'status'}>{error||'같은 실행의 지급·환불·차단 증거를 확인합니다.'}</p></main>;
 const {a,b,denied}=records,network=records.network.network,audit=records[auditChoice],independent=records.independent_verification;
 const tokens=records.efficiency.flows.reduce((n:number,f:any)=>n+f.total_tokens,0);
 return <div className="deal-demo"><header className="demo-header"><a href="/?replay=1" className="demo-brand"><span>A</span>Agent Deal <b>Escrow</b></a><div className="demo-meta"><span className="recorded-label">기록 재생 · 송금하지 않음</span><span>{network==='sepolia'?'SEPOLIA TESTNET':'LOCAL DEVNET'}</span></div></header>
 <nav className="demo-chapters" aria-label="데모 단계">{stages.map((s,i)=><button key={s.at} className={i===index?'current':i<index?'past':''} aria-current={i===index?'step':undefined} onClick={()=>jump(s.at)}><span>{String(i+1).padStart(2,'0')}</span>{s.label}</button>)}</nav>
 <main className="demo-main"><div className="demo-title"><p className="eyebrow">RESEARCH BUYER × EXTERNAL DATA AGENT / {String(index+1).padStart(2,'0')}</p><h1>{stage.title}</h1><p>{stage.line}</p></div>
 {!sourceMode&&index===0&&<div className="demo-two"><section className="demo-card task-brief"><span className="demo-kicker">이번 의뢰</span><h2>한국 EV 배터리 기업의<br/>2025–2026 CAPEX 데이터</h2><p>리서치팀은 검토할 JSON을 받고, 외부 판매자는 조건을 지킨 뒤 대금을 받습니다.</p><div className="brief-tags"><span>최소 {a.mandate.task_requirements.minimum_rows}행</span><span>출처 URL ≥{a.mandate.task_requirements.minimum_source_coverage*100}%</span><span>JSON</span></div><div className="demo-note">이 데모의 데이터 값은 합성입니다. 사실성·투자 판단을 검증하는 제품은 아닙니다.</div></section><section className="demo-card"><span className="demo-kicker">사람이 그은 선</span><div className="big-budget">{amount(a.mandate.task_budget_minor)}<small>작업 예산</small></div><dl><dt>한 번에 쓸 수 있는 금액</dt><dd>{amount(a.mandate.max_single_minor)} units</dd><dt>허용 대상</dt><dd>Seller A · Seller B</dd><dt>거래 당시 승인</dt><dd><span className="demo-pill">ACTIVE</span></dd></dl><p className="demo-note">단위는 테스트 자산이며 달러가 아닙니다. 네트워크 수수료는 별도 데모 운영 예산이 부담합니다.</p></section></div>}
 {!sourceMode&&index===1&&<div className="demo-two"><section className="demo-card"><span className="demo-kicker">실제 Kiln 협상 · {a.kiln[0]?.model}</span><div className="negotiation-messages">{a.evidence.negotiation.map((m:any,i:number)=><article key={i} className={m.actor==='Buyer Agent'?'from-buyer':''}><strong>{m.actor==='Buyer Agent'?'구매 AI':'판매 AI'}<small>{m.tool}</small></strong><p>{m.args.reason??'제안된 계약을 수락합니다. 예치 여부는 정책 검사가 결정합니다.'}</p>{m.args.price_minor&&<div className="offer-strip">{amount(m.args.price_minor)} units · {m.args.minimum_rows}행 · ≥{m.args.minimum_source_coverage*100}% · {m.args.deadline}초</div>}</article>)}</div></section><section className="demo-card contract-brief"><span className="demo-kicker">협상의 결과 → 변경 불가 계약</span><h2>{amount(a.deal.price_minor)} <small>demo units</small></h2><dl><dt>최소 행 수</dt><dd>{a.deal.requirements.minimum_rows}</dd><dt>출처 URL 비율</dt><dd>≥{a.deal.requirements.minimum_source_coverage*100}%</dd><dt>납품 형식</dt><dd>JSON</dd><dt>납기</dt><dd>예치 후 {a.deal.deadline}초</dd></dl><div className="demo-callout">AI의 수락 ≠ 결제 허가<br/><small>다음 단계에서 코드가 사람의 승인과 대조합니다.</small></div></section></div>}
 {sourceMode&&[0,1,3,4].includes(index)&&<>{(index===3||index===4)&&<MoneyPath mode={index===3?'release':'refund'} value={index===3?a.deal.price_minor:b.deal.price_minor}/>}<SourceEvidence stage={index} records={records}/></>}
 {index===2&&<><MoneyPath mode="lock" value={a.deal.price_minor}/><div className="demo-two"><section className="demo-card"><span className="demo-kicker">돈을 보내기 직전, 다시 확인</span><CheckList checks={a.evidence.policy.filter((c:any)=>['MANDATE_ACTIVE','MANDATE_NOT_EXPIRED','DEAL_NOT_EXPIRED','MAX_SINGLE','TASK_BUDGET','DEAL_HASH','SELLER_ALLOWED'].includes(c.name))}/></section><section className="demo-card outcome-lock"><span className="demo-kicker">판매자에게 지급된 금액</span><div className="demo-number">0</div><h2>{amount(a.deal.price_minor)} units는 에스크로에</h2><p>검수 전에는 판매자가 가져갈 수 없습니다.</p><TxLink hash={a.transactions.fund.tx_hash} network={network} label="실제 예치 거래"/></section></div></>}
 {!sourceMode&&index===3&&<><MoneyPath mode="release" value={a.deal.price_minor}/><div className="demo-two"><section className="demo-card"><span className="demo-kicker">SELLER A의 납품</span><div className="data-score"><strong>{a.evidence.validation.row_count}<small> / {a.deal.requirements.minimum_rows}행</small></strong><span>출처 URL {(a.evidence.validation.source_coverage*100).toFixed(1)}%</span></div><CheckList checks={a.evidence.validation.checks.slice(0,5)}/><details><summary>추가 품질 검사 4개 보기</summary><CheckList checks={a.evidence.validation.checks.slice(5)}/></details></section><section className="demo-card outcome-good"><span className="demo-kicker">DELIVERY VERIFIED</span><div className="outcome-symbol">✓</div><h2>{amount(a.deal.price_minor)} units 지급 완료</h2><p>계약한 구조와 납기 조건을 통과했습니다.</p><TxLink hash={a.transactions.release.tx_hash} network={network} label="실제 지급 거래"/><p className="demo-note">URL 형식·비율을 검사했습니다. 해당 자료가 사실이라는 증명은 아닙니다.</p></section></div></>}
 {!sourceMode&&index===4&&<><MoneyPath mode="refund" value={b.deal.price_minor}/><div className="demo-two"><section className="demo-card"><span className="demo-kicker">SELLER B의 납품</span><div className="data-score bad"><strong>{b.evidence.validation.row_count}<small> / {b.deal.requirements.minimum_rows}행</small></strong><span>약속보다 {b.deal.requirements.minimum_rows-b.evidence.validation.row_count}행 부족</span></div><CheckList checks={b.evidence.validation.checks.filter((c:any)=>!c.pass)}/><p>AI가 납품했다고 말해도, 구조적 기준을 통과하지 못하면 지급하지 않습니다.</p></section><section className="demo-card outcome-bad"><span className="demo-kicker">정상적으로 처리된 실패</span><div className="outcome-symbol">↶</div><h2>{amount(b.deal.price_minor)} units 환불 완료</h2><p>실패 원인과 환불을 같은 거래 기록에 남겼습니다.</p><TxLink hash={b.transactions.refund.tx_hash} network={network} label="실제 환불 거래"/></section></div></>}
 {index===5&&<><div className="memory-thread"><div><small>직전 거래 #{short(b.deal.deal_id)}</small><strong>검수 실패 → 환불</strong></div><b>→</b><div><small>이 회사의 Seller B에만</small><strong>사전 샘플 검사 추가</strong></div><b>→</b><div className="memory-stop"><small>다음 거래 #{short(denied.deal.deal_id)}</small><strong>샘플 없으면 예치 차단</strong></div></div><div className="demo-two"><section className="demo-card"><span className="demo-kicker">기억을 실제 제약으로</span><h2>REQUIRE_PREVIEW</h2><p>고정된 규칙이 검증된 실패 기록을 받아 활성화됩니다. AI가 임의로 정책을 만들거나 해제하지 않습니다.</p><dl><dt>범위</dt><dd>동일 회사 · Seller B</dd><dt>이전 실패</dt><dd>납품 조건 미달</dd><dt>Seller A</dt><dd>기본 검사 유지</dd></dl></section><section className="demo-card outcome-bad"><span className="demo-kicker">실제로 시도한 다음 거래</span><div className="demo-number">차단</div><h2>샘플 먼저. 돈은 그 다음.</h2><p>PREVIEW_REQUIRED</p><span className="demo-pill">서명된 예치 거래 {Object.keys(denied.transactions).length}건</span><a className="demo-link" href={`/api/audit/${denied.deal.deal_id}`}>차단 기록 내려받기 ↓</a></section></div></>}
 {index===6&&<section className="demo-card audit-story"><div className="audit-story-head"><span className="demo-kicker">독립 검토를 위한 한 묶음의 증거</span><div className="audit-switch">{[['a','지급'],['b','환불'],['denied','차단']].map(([key,label])=><button key={key} aria-pressed={auditChoice===key} onClick={()=>setAuditChoice(key)}>{label}</button>)}</div></div><div className="audit-steps"><div><span>01 사람의 승인</span><strong>≤{amount(audit.mandate.max_single_minor)} units</strong><small>예산·판매자·최소 품질</small></div><div><span>02 AI의 계약</span><strong>{amount(audit.deal.price_minor)} units</strong><small>≥{audit.deal.requirements.minimum_rows}행 · JSON</small></div><div><span>03 코드의 판정</span><strong>{auditChoice==='denied'?'샘플 필요':`${audit.evidence.validation.row_count}행 · ${audit.evidence.validation.verified?'통과':'실패'}`}</strong><small>원문과 검증 결과 재계산</small></div><div><span>04 실제 결과</span><strong>{auditChoice==='a'?'판매자 지급':auditChoice==='b'?'구매자 환불':'예치 차단'}</strong><small>{auditChoice==='denied'?'서명된 거래 없음':'체인 영수증과 대조'}</small></div></div><div className="audit-verdict"><span>{independent?'✓ 별도 RPC로 최종 확정 블록까지 대조 완료':'로컬 증거 구조 확인 · 별도 체인 대조 기록 없음'}</span><small>{independent?`${new Date(independent.checked_at).toLocaleString('ko-KR')} 검증 시점 기준`:'온체인 사실성에 대한 독립 판정을 대신하지 않습니다.'}</small></div><div className="audit-actions"><a className="demo-link" href={`/api/audit/${audit.deal.deal_id}`}>전체 영수증 JSON ↓</a>{audit.transactions.release?.tx_hash&&<TxLink hash={audit.transactions.release.tx_hash} network={network} label="블록 탐색기"/>}{audit.transactions.refund?.tx_hash&&<TxLink hash={audit.transactions.refund.tx_hash} network={network} label="블록 탐색기"/>}</div><details><summary>기술 증거와 신뢰 범위 보기</summary><p>계약 해시</p><code>{audit.deal_hash}</code><p>체인은 금액·정산·증거 해시를 확인합니다. 오프체인 승인 및 납품 검사의 실행과 전체 기록 수집은 controller를 신뢰합니다. 데이터의 사실성, 사건 누락 부재, 운영 지갑의 생산 환경 보안은 증명하지 않습니다.</p></details></section>}
 {index===7&&<section className="demo-card"><div className="efficiency-head"><div><span className="demo-kicker">이 실행만 집계 · {a.kiln[0]?.model}</span><h2>Kiln 호출 {records.efficiency.calls}회</h2></div><div className="token-total">{tokens.toLocaleString()}<small>실제 사용 tokens</small></div></div><div className="table-wrap"><table><thead><tr><th>흐름</th><th>호출</th><th>입력 토큰</th><th>출력 토큰</th><th>합계</th></tr></thead><tbody>{records.efficiency.flows.map((f:any)=><tr key={f.flow_name}><td>{f.flow_name}</td><td>{f.calls}</td><td>{f.prompt_tokens.toLocaleString()}</td><td>{f.completion_tokens.toLocaleString()}</td><td>{f.total_tokens.toLocaleString()}</td></tr>)}</tbody></table></div><div className="code-zero">{['승인·예산 검사','JSON 납품 검증','지급·환불 결정','실패 통제 적용'].map(x=><div key={x}>{x}<strong>0 LLM calls</strong></div>)}</div><p className="demo-note">측정: API가 반환한 토큰·호출 지연. 미측정: 장비 전력·TTFT·다른 설계 대비 절감률. Kiln의 NPU 제공 경로를 사용하며, 이 앱이 물리 장비 경로를 직접 검증하지는 않습니다.</p><EnergyAssumptions estimate={records.energy_estimate}/></section>}
 {index===8&&records.recovery&&<RecoveryEvidence recovery={records.recovery}/>}
 {index===8&&!records.recovery&&<section className="demo-card closing-card"><div className="closing-path"><div><span>01</span><strong>AI가 협상</strong><small>Kiln · 구조화 계약</small></div><b>→</b><div><span>02</span><strong>돈을 예치</strong><small>{network} escrow</small></div><b>→</b><div><span>03</span><strong>코드가 검수</strong><small>지급 또는 환불</small></div></div><div className="closing-memory">실패 → 그 판매자의 다음 거래에 사전 검사</div><p>실제 API 호출 · 실제 테스트넷 정산 · 재구성 가능한 증거</p><button className="demo-primary" onClick={()=>jump(0)}>다시 살펴보기 ↗</button><span className="demo-note">좁은 디지털 작업 거래 프로토타입. 실제 돈·생산 환경 자산 수탁·데이터 사실 검증은 범위 밖입니다.</span></section>}
 <div className="demo-footnote"><span>RUN {short(index===8&&records.recovery?records.recovery.run:records.run)} · {new Date(index===8&&records.recovery?records.recovery.report.completed_at:records.created_at).toLocaleDateString('ko-KR')}</span><span>기록의 금액·조건·상태를 그대로 재생합니다.</span></div></main>
 <div className="demo-playbar"><button className="demo-primary" onClick={()=>{if(seconds>=180)setSeconds(0);setPlaying(!playing);}} aria-label={playing?'일시정지':'3분 데모 재생'}>{playing?'Ⅱ 일시정지':'▶ 3분 데모 재생'}</button><button className="demo-reset" onClick={()=>jump(0)}>처음</button><input aria-label="데모 재생 위치" type="range" min="0" max="180" step="1" value={seconds} onChange={e=>jump(Number(e.target.value))}/><time>{Math.floor(seconds/60)}:{String(Math.floor(seconds%60)).padStart(2,'0')} <span>/ 3:00</span></time></div></div>;
}
