const amount=(value:number)=>(value/100).toFixed(2);
export const sourceCopy:Record<number,{title:string;line:string}>={
  0:{title:'필요한 건, 정확한 네 개의 값.',line:'외부 AI에게 공시 수치 추출을 맡겼습니다. 결과를 확인하기 전에는 대금을 지급하지 않습니다.'},
  1:{title:'싼 견적보다, 맞는 작업을.',line:'Kiln이 실제 분기 실적·전망치·납기의 차이를 비교합니다. 가격 변경은 판매자가 공개한 범위 안에서만 제안합니다.'},
  3:{title:'원문과 맞는 결과. 이제 지급.',line:'실제 Kiln이 추출한 네 값과 출처를 고정된 참조 자료에 대조하고 Sepolia에서 지급했습니다.'},
  4:{title:'네 행도, 출처도 있다.\n그런데 지표가 다르다.',line:'의도적인 공격 실험입니다. 시설투자 대신 다른 현금흐름 값을 넣자 코드가 불일치를 찾아 환불했습니다.'},
  7:{title:'조건 해석과 추출에는 AI.',line:'이 원문 납품 실행의 실제 토큰입니다. 예산·참조표 대조·정산 판단은 코드가 수행합니다.'},
};
function TransactionLink({record,kind}:{record:any;kind:'release'|'refund'}){
  const tx=record.transactions[kind].tx_hash;
  return <a className="demo-link" href={`https://sepolia.etherscan.io/tx/${tx}`} target="_blank" rel="noreferrer">{kind==='release'?'실제 지급 거래':'실제 환불 거래'} ↗ <span>{tx.slice(0,10)}…</span></a>;
}
export function SourceEvidence({stage,records}:{stage:number;records:any}){
  const {a,b}=records,rows=JSON.parse(a.evidence.delivery),badRows=JSON.parse(b.evidence.delivery);
  if(stage===0)return <div className="demo-two"><section className="demo-card task-brief"><span className="demo-kicker">리서치 자동화 개발자의 의뢰</span><h2>LG에너지솔루션<br/>2025년 분기별 시설투자</h2><p>Q1부터 Q4까지, 실적 발표 자료의 현금유출을 십억 원 단위로 추출합니다. 연간 전망이나 다른 현금흐름으로 대체할 수 없습니다.</p><div className="quarter-slots" aria-label="납품받아야 할 네 분기">{['Q1','Q2','Q3','Q4'].map(q=><div key={q}><small>2025 {q}</small><strong>—</strong></div>)}</div><p className="demo-note">공개 자료의 추출·정규화 작업입니다. 고정 참조표 검증이며 새로운 문서의 사실을 자동 판정하는 제품은 아닙니다.</p></section><section className="demo-card"><span className="demo-kicker">사람이 승인한 범위 · 기록된 데모 의뢰</span><div className="big-budget">{amount(a.mandate.task_budget_minor)}<small>작업 예산</small></div><dl><dt>건별 상한</dt><dd>{amount(a.mandate.max_single_minor)} units</dd><dt>필수 결과</dt><dd>실제 분기 4개</dd><dt>원문 근거</dt><dd>문서·페이지·행·단위</dd><dt>작업 중지</dt><dd>새 예치 전 승인 재확인</dd></dl><p className="demo-note">테스트 자산입니다. 원금·가스는 데모 운영자가 공급하며 실제 달러나 고객의 예금이 아닙니다.</p></section></div>;
  if(stage===1)return <div className="demo-two"><section className="demo-card"><span className="demo-kicker">실제 Kiln의 선택 · {a.kiln[0]?.model}</span><div className="negotiation-messages">{a.evidence.negotiation.map((message:any,index:number)=><article className="from-buyer" key={index}><strong>구매 AI <small>{message.tool}</small></strong><p>{message.args.reason}</p><div className="offer-strip">선택: {message.args.offer_id} · {message.args.decision==='counter'?'가격 변경 제안':'수락 제안'}</div></article>)}</div><p>비교 대상: 분기별 실제 지출 / 연간 전망을 나눈 추정치 / 마감이 늦는 추출.</p><p className="demo-note">판매자의 가격 응답은 공개된 최저가 규칙으로 처리했습니다. 별도 판매자 LLM 협상을 수행했다고 표시하지 않습니다.</p></section><section className="demo-card contract-brief"><span className="demo-kicker">확정된 작업 조건</span><h2>{amount(a.deal.price_minor)} <small>test units</small></h2><dl><dt>결과</dt><dd>2025년 네 분기</dd><dt>지표</dt><dd>시설투자 현금유출</dd><dt>정규화</dt><dd>십억 원 · 지출액 양수</dd><dt>원문값</dt><dd>원래 음수 부호 보존</dd><dt>납기</dt><dd>예치 후 {a.deal.deadline}초</dd></dl><div className="demo-callout">선택은 AI가, 지급 허가는 코드가.</div></section></div>;
  if(stage===3)return <div className="demo-two"><section className="demo-card"><span className="demo-kicker">실제 모델 납품 · 고정 원문과 비교</span><div className="table-wrap"><table className="source-values"><thead><tr><th>분기</th><th>시설투자</th><th>원문</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.quarter}><td>{row.quarter}</td><td>{row.capex.toLocaleString()}<small>십억 원</small></td><td><a href={`${row.source_url}#page=${row.source_page}`} target="_blank" rel="noreferrer">{row.source_page}쪽 ↗</a></td></tr>)}</tbody></table></div><p className="demo-note">발행사 실적 발표 자료의 Investment in Facilities 행과 일치합니다. 감사보고서의 표준 현금흐름이나 임의 문서의 진실성을 인증하지 않습니다.</p></section><section className="demo-card outcome-good"><span className="demo-kicker">검수한 납품에 실제 지급</span><div className="outcome-symbol">✓</div><h2>{amount(a.deal.price_minor)} units 지급 완료</h2><p>분기·값·단위·원 부호·출처 위치를 대조했습니다.</p><TransactionLink record={a} kind="release"/><p className="demo-note">원문 문서 해시를 실행 시 다시 확인했습니다. 모델은 PDF가 아닌 전사된 표를 입력받았습니다. 참조표의 사람 검토는 대기입니다.</p></section></div>;
  if(stage===4){const different=badRows.filter((row:any)=>rows.find((good:any)=>good.quarter===row.quarter)?.capex!==row.capex);return <div className="demo-two"><section className="demo-card"><span className="demo-kicker">통제된 오류 주입 · 자연 발생 모델 오류 아님</span><div className="brief-tags"><span>4행 ✓</span><span>JSON ✓</span><span>공식 출처 링크 ✓</span></div>{different.map((row:any)=>{const good=rows.find((item:any)=>item.quarter===row.quarter);return <div className="metric-mismatch" key={row.quarter}><span>{row.quarter} · 십억 원</span><div><p>약속한 시설투자<strong>{good.capex.toLocaleString()}</strong></p><b>≠</b><p>납품된 다른 현금흐름<strong>{row.capex.toLocaleString()}</strong></p></div></div>;})}<p>형식이 맞아도, 승인한 지표의 값이 아니면 검수를 통과하지 못합니다.</p></section><section className="demo-card outcome-bad"><span className="demo-kicker">지급 조건 미달 → 구매자에게 반환</span><div className="outcome-symbol">↶</div><h2>{amount(b.deal.price_minor)} units 환불 완료</h2><p>판매자 수령 0 · 원금은 별도 구매자 주소로 회수</p><TransactionLink record={b} kind="refund"/><p className="demo-note">기준은 저장된 참조표입니다. 범용 의미 검증으로 소개하지 않습니다.</p></section></div>;}
  return null;
}

export function EnergyAssumptions({estimate}:{estimate:any}){
  if(!estimate)return null;
  return <details className="energy-assumptions"><summary>가정 기반 에너지 계산 보기 · 전력 실측 아님</summary><p>4개 카드 × 카드당 150W를 기준으로 활성 시간과 전력 비율을 달리한 계산입니다. TDP는 실제 소비전력이 아니며 Kiln의 물리 배치는 확인하지 못했습니다.</p><div className="table-wrap"><table><thead><tr><th>가정</th><th>API 지연 중 활성 시간</th><th>가정 전력</th><th>계산 결과</th></tr></thead><tbody>{estimate.scenarios.map((s:any)=><tr key={s.id}><td>{s.label}</td><td>{s.active_fraction*100}%</td><td>{s.assumed_accelerator_watts} W</td><td>{(s.joules/1000).toFixed(2)} kJ</td></tr>)}</tbody></table></div><p>관측한 전력 범위나 GPU 대비 절감률이 아닙니다. 배치 공유, 호스트 CPU·저장장치·체인·냉각 전력은 미측정이며 합계에 포함하지 않았습니다.</p></details>;
}
