import {useEffect,useRef,useState} from 'react';
import './Study.css';
type Context={token:string;evidence_version:string;source_run:string;recovery_run:string|null;source_url:string;questions:{id:string;label:string}[];counts:{self_reported_humans:number;automated_qa:number;reviewed_humans:number}};
const errors:Record<string,string>={STUDY_VERSION_CHANGED:'시청한 데모 버전이 변경되었습니다. 답변을 복사해 보관한 뒤 새로고침하고, 새 데모를 확인해 주세요.',INVALID_STUDY_RESPONSE:'참가 구분, 확인 항목과 모든 답변을 확인해 주세요.',LOCAL_SESSION_REQUIRED:'로컬 연결이 갱신되었습니다. 답변을 보관한 뒤 새로고침해 주세요.',SUBMISSION_ID_REUSED:'이미 저장된 응답과 내용이 다릅니다. 새 응답으로 시작해 주세요.'};
export function Study(){
  const [context,setContext]=useState<Context|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState('');
  const [participant,setParticipant]=useState(''),[kind,setKind]=useState(''),[newcomer,setNewcomer]=useState(false),[practitioner,setPractitioner]=useState(false),[consent,setConsent]=useState(false),[viewed,setViewed]=useState(false),[answers,setAnswers]=useState<Record<string,string>>({});
  const submission=useRef(crypto.randomUUID()),busy=useRef(false),status=useRef<HTMLDivElement>(null);
  useEffect(()=>{const controller=new AbortController();fetch('/api/study',{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('질문지를 불러오지 못했습니다. 로컬 참여자 서비스가 실행 중인지 확인해 주세요.');setContext(await response.json());}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
  async function submit(event:React.FormEvent){
    event.preventDefault();if(!context||busy.current)return;busy.current=true;setSaving(true);setError('');
    try{
      const response=await fetch('/api/study',{method:'POST',headers:{'Content-Type':'application/json','X-ADE-Token':context.token},body:JSON.stringify({submission_id:submission.current,evidence_version:context.evidence_version,participant_id:participant,participant_kind:kind,newcomer,practitioner,consent,viewed,answers})});
      const result=await response.json();if(!response.ok)throw new Error(errors[result.error]??'저장하지 못했습니다. 답변은 유지됩니다. 연결을 확인하고 다시 시도해 주세요.');setContext(previous=>previous?{...previous,counts:result.counts}:previous);setSaved(result.response_id);
    }catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.');}finally{setSaving(false);busy.current=false;status.current?.focus();}
  }
  return <div className="study-page"><header className="study-header"><a href="/?study=1">A <span>Agent Deal Escrow</span></a><span>로컬 참여자 검증</span></header><main className="study-main">
    <section className="study-intro"><p className="eyebrow">YOUR FIRST IMPRESSION</p><h1>이해한 그대로,<br/>들려주세요.</h1><p>데모가 전달한 내용과 실제 업무에 필요한 점을 확인합니다. 정답을 맞힐 필요는 없습니다. 모르거나 경험이 없는 항목은 그대로 적어주세요.</p><div className="study-tags"><span>약 5–10분</span><span>익명 코드</span><span>이 PC에만 저장</span></div></section>
    {!context?<p role="status">{error||'시청할 데모와 질문지를 준비하고 있습니다…'}</p>:<div className="study-layout"><aside className="study-guide"><h2>먼저 데모를 봐주세요.</h2><p>설명 없이 한 번 본 뒤, 본인 말로 답해주세요. 링크는 새 탭에서 열립니다.</p><a className="study-demo-link" href="/?replay=1&studyDemo=1" target="_blank" rel="noreferrer">3분 데모 보기 ↗</a><dl><dt>원문 실행</dt><dd>{context.source_run.slice(0,8)}</dd><dt>직접 회수 실행</dt><dd>{context.recovery_run?.slice(0,8)??'없음'}</dd><dt>시청 버전</dt><dd>{context.evidence_version.slice(0,12)}</dd></dl><p className="study-note">답변은 이 버전의 화면과 증거에 연결됩니다. 응답 수만으로 사용성이나 실수요 검증을 완료하지 않습니다.</p><div className="study-counts"><strong>{context.counts.self_reported_humans}</strong><span>이 버전의 사람 응답<br/>자동 QA {context.counts.automated_qa}건은 별도</span></div></aside>
    <form className="study-form" onSubmit={submit}><div ref={status} tabIndex={-1} aria-live="polite">{saved?<div className="study-success" role="status"><h2>응답을 저장했습니다.</h2><p>감사합니다. 실제 참여 여부와 답변 내용은 별도로 검토합니다.</p><code>응답 {saved}</code><p>이 페이지를 닫아도 저장한 답변은 이 PC에 남습니다.</p></div>:error?<p className="study-error" role="alert">{error}</p>:null}</div>
    {!saved?<><fieldset disabled={saving}><legend>01 · 참여 정보</legend><label>익명 참가 코드<input required pattern="[A-Za-z0-9_-]{1,40}" maxLength={40} value={participant} onChange={e=>setParticipant(e.target.value)} placeholder="예: P1" autoComplete="off" aria-describedby="participant-help"/></label><small id="participant-help">영문·숫자·밑줄·하이픈만 사용하세요. 이름이나 연락처는 입력하지 않습니다.</small><label>참가 구분<select required value={kind} onChange={e=>setKind(e.target.value)}><option value="">선택해 주세요</option><option value="human">사람이 직접 응답</option><option value="automated_qa">자동 QA 검사</option></select></label><label className="study-check"><input type="checkbox" checked={newcomer} onChange={e=>setNewcomer(e.target.checked)}/>이 프로젝트를 처음 보는 참여자입니다.</label><label className="study-check"><input type="checkbox" checked={practitioner} onChange={e=>setPractitioner(e.target.checked)}/>리서치·유료 데이터·에이전트 관련 업무 경험이 있습니다.</label><label className="study-check"><input type="checkbox" required checked={viewed} onChange={e=>setViewed(e.target.checked)}/>위 버전의 데모를 확인했습니다.</label></fieldset>
    <fieldset disabled={saving}><legend>02 · 이해한 내용과 실제 경험</legend>{context.questions.map((question,index)=><label className="study-answer" key={question.id}><span><b>{String(index+1).padStart(2,'0')}</b>{question.label}</span>{question.id==='reference_review'?<small>선택적으로 <a href={context.source_url} target="_blank" rel="noreferrer">공식 보고서 16쪽 ↗</a>을 열어 대조하세요. 검토하지 않았다면 그렇게 적어주세요.</small>:null}<textarea required maxLength={4000} rows={question.id==='recent_incident'?5:3} value={answers[question.id]??''} onChange={e=>setAnswers(previous=>({...previous,[question.id]:e.target.value}))}/></label>)}</fieldset>
    <fieldset disabled={saving}><legend>03 · 저장 동의</legend><p className="study-note">회사 비밀·개인 연락처·계좌 정보는 적지 마세요. 응답은 프로젝트 개선을 위해 이 PC의 비공개 폴더에 저장됩니다. GitHub로 자동 전송되지 않습니다.</p><label className="study-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>위 내용을 확인했고 익명 응답 저장에 동의합니다.</label><button type="submit" className="study-submit">{saving?'저장 중…':'응답 저장하기 →'}</button></fieldset></>:null}</form></div>}
  </main><footer className="study-footer">Agent Deal Escrow · 원문과 지급 조건을 연결하는 실험</footer></div>;
}
