import {randomUUID,generateKeyPairSync,createPublicKey,sign,verify} from 'node:crypto';
import {ensure,exact,hash,integer,identifier,validateDeal} from '../deal-escrow/domain.ts';

export const fields=['price_minor','metric','periods','source_required','deadline_seconds','deadline_anchor','refund_policy'];
export const expectedTerms={metric:'ACTUAL_QUARTERLY_FACILITY_INVESTMENT',periods:['2025-Q1','2025-Q2','2025-Q3','2025-Q4'],source_required:true,deadline_anchor:'ESCROW_FUNDING_BLOCK',refund_policy:'MISMATCH_OR_EXPIRY_REFUND_BUYER'};
export function identity(id){const pair=generateKeyPairSync('ed25519');return {id,public_key:pair.publicKey.export({type:'spki',format:'der'}).toString('base64'),private_key:pair.privateKey};}
const signObject=(actor,body)=>sign(null,Buffer.from(hash(body)),actor.private_key).toString('base64');
export function signedMessage(session,actor,recipient,content,time){const events=session.events??[];const body={event_id:randomUUID(),session_id:session.session_id,sender_agent:actor.id,recipient_agent:recipient,timestamp:time,protocol:'DEALTRACE_INTERNAL_V1',payload_type:'message',sequence:events.length+1,previous_hash:events.at(-1)?.message_hash??null,content};return {...body,message_hash:hash(body),signature:signObject(actor,body)};}
export function signedConfirmation(session,revision,actor){const body={type:'DEALTRACE_CONFIRM_V1',session_id:session.session_id,agent_id:actor.id,revision_hash:revision.revision_hash,deal_hash:hash(revision.deal),mandate_hash:session.mandate_hash};return {...body,signature:signObject(actor,body)};}
function signatureOK(body,signature,key){try{return verify(null,Buffer.from(hash(body)),createPublicKey({key:Buffer.from(key,'base64'),type:'spki',format:'der'}),Buffer.from(signature,'base64'));}catch{return false;}}
function immutable(db,name){db.exec(`CREATE TRIGGER IF NOT EXISTS ${name}_immutable_update BEFORE UPDATE ON ${name} BEGIN SELECT RAISE(ABORT,'IMMUTABLE_NEGOTIATION');END;CREATE TRIGGER IF NOT EXISTS ${name}_immutable_delete BEFORE DELETE ON ${name} BEGIN SELECT RAISE(ABORT,'IMMUTABLE_NEGOTIATION');END;`);}

export class NegotiationLedger{
 constructor(engine){this.engine=engine;this.store=engine.store;this.db=this.store.db;this.db.exec(`
 CREATE TABLE IF NOT EXISTS trace_mandates(id TEXT PRIMARY KEY REFERENCES mandates(id));
 CREATE TABLE IF NOT EXISTS trace_sessions(id TEXT PRIMARY KEY,mandate_id TEXT NOT NULL REFERENCES mandates(id),body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS trace_messages(id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES trace_sessions(id),sequence INTEGER NOT NULL,body TEXT NOT NULL,UNIQUE(session_id,sequence));
 CREATE TABLE IF NOT EXISTS trace_revisions(session_id TEXT NOT NULL REFERENCES trace_sessions(id),revision INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(session_id,revision));
 CREATE TABLE IF NOT EXISTS trace_confirmations(session_id TEXT NOT NULL,revision_hash TEXT NOT NULL,agent TEXT NOT NULL,body TEXT NOT NULL,PRIMARY KEY(session_id,revision_hash,agent));
 CREATE TABLE IF NOT EXISTS trace_commits(session_id TEXT PRIMARY KEY,deal_id TEXT UNIQUE NOT NULL,body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS trace_audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,body TEXT NOT NULL);
 `);for(const name of ['trace_mandates','trace_sessions','trace_messages','trace_revisions','trace_confirmations','trace_commits','trace_audit'])immutable(this.db,name);}
 note(id,type,payload){const last=this.audit(id).at(-1);const body={id:randomUUID(),session_id:id,type,payload,timestamp:this.engine.clock(),previous_hash:last?.hash??null};this.db.prepare('INSERT INTO trace_audit(session_id,body) VALUES(?,?)').run(id,JSON.stringify({...body,hash:hash(body)}));}
 audit(id){return this.db.prepare('SELECT body FROM trace_audit WHERE session_id=? ORDER BY seq').all(id).map(r=>JSON.parse(r.body));}
 create(mandateId,buyer,seller){const m=this.store.mandate(mandateId);ensure(m.buyer_id===buyer.id,'BUYER_IDENTITY_MISMATCH');ensure(this.engine.chain.sellers[seller.id],'UNKNOWN_SELLER');const intent=this.store.getOrCreateIntent(mandateId,seller.id,'new-'+randomUUID());const body={session_id:randomUUID(),mandate_id:mandateId,mandate_hash:hash(m),mandate_snapshot:m,buyer:buyer.id,seller:seller.id,identities:{[buyer.id]:buyer.public_key,[seller.id]:seller.public_key},intent_id:intent.id,deal_id:intent.deal_id,created_at:this.engine.clock()};this.store.transaction(()=>{this.db.prepare('INSERT OR IGNORE INTO trace_mandates VALUES(?)').run(mandateId);this.db.prepare('INSERT INTO trace_sessions VALUES(?,?,?)').run(body.session_id,mandateId,JSON.stringify(body));this.note(body.session_id,'SESSION_CREATED',{mandate_hash:body.mandate_hash,scope:'Pinned local demo identities, not external organizational identity verification.'});});return this.session(body.session_id);}
 session(id){const row=this.db.prepare('SELECT body FROM trace_sessions WHERE id=?').get(id);ensure(row,'SESSION_NOT_FOUND');const body=JSON.parse(row.body);return {...body,events:this.db.prepare('SELECT body FROM trace_messages WHERE session_id=? ORDER BY sequence').all(id).map(r=>JSON.parse(r.body)),revisions:this.db.prepare('SELECT body FROM trace_revisions WHERE session_id=? ORDER BY revision').all(id).map(r=>JSON.parse(r.body)),confirmations:this.db.prepare('SELECT body FROM trace_confirmations WHERE session_id=? ORDER BY rowid').all(id).map(r=>JSON.parse(r.body)),commit:this.commitRecord(id),audit:this.audit(id)};}
 commitRecord(id){const r=this.db.prepare('SELECT body FROM trace_commits WHERE session_id=?').get(id);return r?JSON.parse(r.body):null;}
 append(id,input){return this.store.transaction(()=>{const s=this.session(id);exact(input,['event_id','session_id','sender_agent','recipient_agent','timestamp','protocol','payload_type','sequence','previous_hash','content','message_hash','signature']);const {message_hash,signature,...body}=input;identifier(body.event_id);ensure(body.session_id===id,'MESSAGE_SESSION_MISMATCH');ensure(body.protocol==='DEALTRACE_INTERNAL_V1'&&body.payload_type==='message','MESSAGE_PROTOCOL');ensure([s.buyer,s.seller].includes(body.sender_agent)&&body.recipient_agent===(body.sender_agent===s.buyer?s.seller:s.buyer),'MESSAGE_PARTICIPANTS');ensure(typeof body.content==='string'&&body.content.length>0&&body.content.length<=6000,'MESSAGE_SIZE');integer(body.timestamp,s.created_at,this.engine.clock()+5);ensure(body.sequence===s.events.length+1&&body.previous_hash===(s.events.at(-1)?.message_hash??null),'MESSAGE_ORDER');ensure(message_hash===hash(body)&&signatureOK(body,signature,s.identities[body.sender_agent]),'MESSAGE_SIGNATURE');this.db.prepare('INSERT INTO trace_messages VALUES(?,?,?,?)').run(body.event_id,id,body.sequence,JSON.stringify(input));this.note(id,s.commit?'POST_COMMIT_MESSAGE':'MESSAGE_CAPTURED',{event_id:body.event_id,message_hash});return input;});}
 interpret(id,input){return this.store.transaction(()=>{const s=this.session(id);ensure(!s.commit,'DEAL_ALREADY_COMMITTED');exact(input,['event_id','kind','patch']);const event=s.events.find(e=>e.event_id===input.event_id);ensure(event,'UNKNOWN_EVIDENCE_EVENT');const prior=s.revisions.at(-1),processed=prior?.event_count??0;ensure(event.sequence===processed+1,'EXTRACTION_ORDER');ensure(['propose','accept','other'].includes(input.kind),'INTERPRETATION_KIND');ensure(Array.isArray(input.patch)&&input.patch.length<=fields.length,'PATCH_SIZE');ensure(input.kind==='propose'||input.patch.length===0,'ACCEPT_CANNOT_CHANGE_TERMS');const terms=structuredClone(prior?.terms??{}),provenance=structuredClone(prior?.provenance??{}),seen=new Set(),diff=[];
 for(const item of input.patch){exact(item,['field','value','quote']);ensure(fields.includes(item.field)&&!seen.has(item.field),'TERM_FIELD');seen.add(item.field);ensure(!(event.sequence===1&&event.sender_agent===s.buyer&&item.field==='price_minor'),'OPENING_BUDGET_IS_NOT_PRICE');ensure(typeof item.quote==='string'&&item.quote.length>0&&event.content.includes(item.quote),'EVIDENCE_QUOTE_MISMATCH');validateTerm(item.field,item.value,item.quote);const before=terms[item.field]??null;terms[item.field]=structuredClone(item.value);provenance[item.field]={event_id:event.event_id,message_hash:event.message_hash,quote:item.quote,proposed_by:event.sender_agent};if(hash(before)!==hash(item.value))diff.push({field:item.field,before,after:item.value,evidence:provenance[item.field]});}
 const conflicts=Object.entries(expectedTerms).filter(([k,v])=>Object.hasOwn(terms,k)&&hash(terms[k])!==hash(v)).map(([field,expected])=>({field,actual:terms[field],expected,reason:'TASK_SEMANTIC_CONFLICT'}));
 const missing=fields.filter(f=>!Object.hasOwn(terms,f));const m=this.store.mandate(s.mandate_id);let deal=null;if(!missing.length){const {version,max_delivery_seconds,...requirements}=m.task_requirements;deal=validateDeal({deal_id:s.deal_id,buyer_id:s.buyer,seller_id:s.seller,price_minor:terms.price_minor,currency_or_demo_asset:'DEMO',deliverable_type:'CAPEX_DATASET',requirements,deadline:terms.deadline_seconds,created_at:s.created_at,expires_at:m.expires_at,supersedes_deal_id:null});}
 const revision={session_id:id,revision:s.revisions.length+1,previous_hash:prior?.revision_hash??null,event_count:event.sequence,message_head_hash:event.message_hash,terms,provenance,diff,conflicts,missing,conversation_assent:input.kind==='accept'?{event_id:event.event_id,agent:event.sender_agent,previous_revision:prior?.revision_hash??null}:null,deal,mandate_hash:s.mandate_hash};const row={...revision,revision_hash:hash(revision)};this.db.prepare('INSERT INTO trace_revisions VALUES(?,?,?)').run(id,row.revision,JSON.stringify(row));this.note(id,'DEAL_REVISION',{revision:row.revision,revision_hash:row.revision_hash,conflicts,missing});return row;});}
 confirm(id,input){try{return this.store.transaction(()=>{const s=this.session(id),r=s.revisions.at(-1);ensure(!s.commit,'DEAL_ALREADY_COMMITTED');ensure(r?.deal&&r.event_count===s.events.length,'UNPROCESSED_OR_MISSING_TERMS');ensure(r.conflicts.length===0,'UNRESOLVED_CONFLICT');exact(input,['type','session_id','agent_id','revision_hash','deal_hash','mandate_hash','signature']);const {signature,...body}=input;ensure(body.type==='DEALTRACE_CONFIRM_V1'&&body.session_id===id&&body.mandate_hash===s.mandate_hash,'CONFIRMATION_SCOPE');ensure(body.revision_hash===r.revision_hash&&body.deal_hash===hash(r.deal),'DEAL_DIVERGENCE');ensure([s.buyer,s.seller].includes(body.agent_id)&&signatureOK(body,signature,s.identities[body.agent_id]),'CONFIRMATION_SIGNATURE');this.db.prepare('INSERT OR IGNORE INTO trace_confirmations VALUES(?,?,?,?)').run(id,r.revision_hash,body.agent_id,JSON.stringify(input));this.note(id,'HASH_CONFIRMED',{agent:body.agent_id,revision_hash:r.revision_hash,deal_hash:body.deal_hash});return input;});}catch(e){this.note(id,'CONFIRMATION_BLOCKED',{reason:e.message});throw e;}}
 commit(id){try{return this.store.transaction(()=>{const s=this.session(id);if(s.commit)return s.commit;const r=s.revisions.at(-1);ensure(r?.deal&&r.event_count===s.events.length,'UNPROCESSED_OR_MISSING_TERMS');ensure(!r.conflicts.length,'UNRESOLVED_CONFLICT');const acks=s.confirmations.filter(a=>a.revision_hash===r.revision_hash);ensure(new Set(acks.map(a=>a.agent_id)).size===2,'BILATERAL_CONFIRMATION_REQUIRED');ensure(this.engine.clock()<r.deal.expires_at,'DEAL_NOT_EXPIRED');const commit={schema_version:1,session_id:id,deal_id:s.deal_id,revision_hash:r.revision_hash,deal_hash:hash(r.deal),mandate_hash:s.mandate_hash,confirmation_hashes:acks.map(hash).sort(),committed_at:this.engine.clock()};this.db.prepare('INSERT INTO trace_commits VALUES(?,?,?)').run(id,s.deal_id,JSON.stringify(commit));this.store.createDeal(r.deal,s.mandate_id);this.store.move(s.deal_id,'DEAL_ACCEPTED');this.store.event(s.deal_id,'DEAL_ACCEPTED',{deal_hash:commit.deal_hash},'agent',s.buyer);this.store.event(s.deal_id,'BILATERAL_DEAL_COMMITTED',commit,'system','dealtrace');this.store.details(s.deal_id,{dealtrace:commit});if(this.store.control(this.store.mandate(s.mandate_id).company_id,s.seller))this.store.move(s.deal_id,'PREVIEW_REQUIRED');this.store.updateIntent(s.intent_id,{status:'COMPLETED'});this.note(id,'DEAL_COMMITTED',commit);return commit;});}catch(e){this.note(id,'COMMIT_BLOCKED',{reason:e.message});throw e;}}
 packet(id){const s=this.session(id);return {...s,mandate:this.store.mandate(s.mandate_id)};}
}

function validateTerm(field,value,quote){
 if(field==='price_minor'){integer(value,1,1000000000);const amounts=[...quote.matchAll(/\b(\d+)(?:\.(\d{1,2}))?\s*DEMO\b/gi)].map(m=>Number(m[1])*100+Number((m[2]??'').padEnd(2,'0')));ensure(amounts.includes(value),'PRICE_EVIDENCE_UNITS');}
 else if(field==='deadline_seconds'){integer(value,1,3600);const durations=[...quote.matchAll(/\b(\d+)[\s-]*(minutes?|mins?|seconds?|secs?)\b/gi)].map(m=>Number(m[1])*(m[2].toLowerCase().startsWith('m')?60:1));ensure(durations.includes(value),'DEADLINE_EVIDENCE_UNITS');}
 else if(field==='metric')ensure(['ACTUAL_QUARTERLY_FACILITY_INVESTMENT','ANNUAL_CAPEX_FORECAST'].includes(value),'METRIC_SCHEMA');
 else if(field==='periods')ensure(Array.isArray(value)&&value.length>0&&value.length<=4&&new Set(value).size===value.length&&value.every(v=>/^2025(?:-Q[1-4])?$/.test(v)),'PERIOD_SCHEMA');
 else if(field==='source_required')ensure(typeof value==='boolean','SOURCE_SCHEMA');
 else if(field==='deadline_anchor')ensure(value==='ESCROW_FUNDING_BLOCK','DEADLINE_ANCHOR');
 else if(field==='refund_policy')ensure(value==='MISMATCH_OR_EXPIRY_REFUND_BUYER','REFUND_POLICY');
}

export function verifyNegotiationPacket(packet){try{
 let auditHash=null;for(const entry of packet.audit??[]){const {hash:entryHash,...body}=entry;ensure(body.session_id===packet.session_id&&body.previous_hash===auditHash&&hash(body)===entryHash,'NEGOTIATION_AUDIT_HASH');auditHash=entryHash;}
 const s=packet;ensure(hash(s.mandate_snapshot)===s.mandate_hash&&s.mandate_snapshot.mandate_id===s.mandate_id&&s.mandate_snapshot.buyer_id===s.buyer,'MANDATE_BINDING');ensure(s.events.length>0,'EMPTY_LEDGER');let previous=null;for(let i=0;i<s.events.length;i++){const {message_hash,signature,...body}=s.events[i];ensure(body.session_id===s.session_id&&body.sequence===i+1&&body.previous_hash===previous,'MESSAGE_ORDER');ensure(message_hash===hash(body)&&signatureOK(body,signature,s.identities[body.sender_agent]),'MESSAGE_SIGNATURE');previous=message_hash;}
 let revisionHash=null;for(const r of s.revisions){const {revision_hash,...body}=r;ensure(body.previous_hash===revisionHash&&revision_hash===hash(body),'REVISION_HASH');const e=s.events[r.event_count-1];ensure(e&&e.message_hash===r.message_head_hash,'REVISION_EVIDENCE_HEAD');for(const [field,p] of Object.entries(r.provenance)){const source=s.events.find(e=>e.event_id===p.event_id);ensure(source&&source.sequence<=r.event_count&&source.message_hash===p.message_hash&&source.sender_agent===p.proposed_by&&source.content.includes(p.quote),'PROVENANCE_MISMATCH');validateTerm(field,r.terms[field],p.quote);}revisionHash=revision_hash;}
 if(s.commit){const r=s.revisions.find(r=>r.revision_hash===s.commit.revision_hash);ensure(r?.deal&&hash(r.deal)===s.commit.deal_hash&&r.mandate_hash===s.commit.mandate_hash,'COMMIT_HASH');ensure(fields.every(f=>Object.hasOwn(r.terms,f))&&r.missing.length===0&&Object.entries(expectedTerms).every(([k,v])=>hash(r.terms[k])===hash(v))&&r.conflicts.length===0,'COMMIT_CONFLICT');ensure(r.deal.price_minor===r.terms.price_minor&&r.deal.deadline===r.terms.deadline_seconds&&r.deal.buyer_id===s.buyer&&r.deal.seller_id===s.seller&&r.deal.deal_id===s.deal_id,'DEAL_TERM_BINDING');const acks=s.confirmations.filter(a=>a.revision_hash===r.revision_hash);ensure(acks.length===2&&new Set(acks.map(a=>a.agent_id)).size===2&&hash(acks.map(hash).sort())===hash(s.commit.confirmation_hashes),'BILATERAL_CONFIRMATION_REQUIRED');for(const ack of acks){const {signature,...body}=ack;ensure(body.type==='DEALTRACE_CONFIRM_V1'&&body.session_id===s.session_id&&body.deal_hash===s.commit.deal_hash&&body.mandate_hash===s.mandate_hash&&[s.buyer,s.seller].includes(body.agent_id)&&signatureOK(body,signature,s.identities[body.agent_id]),'CONFIRMATION_SIGNATURE');}}
 return {verdict:'VALID',committed:!!s.commit,scope:'Message/revision integrity and bilateral assent to normalized terms; not semantic truth or external identity certification.'};
 }catch(e){return {verdict:'INVALID',reason:e.message};}}

// Called by the existing payment engine at policy approval and again before signing.
export function agreementCheck(store,record){
 if(!store.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='trace_mandates'").get()||!store.db.prepare('SELECT id FROM trace_mandates WHERE id=?').get(record.mandateId))return [];
 const row=store.db.prepare('SELECT body FROM trace_commits WHERE deal_id=?').get(record.deal.deal_id);let valid=false,reason='BILATERAL_COMMIT_REQUIRED';
 if(row){const commit=JSON.parse(row.body);const session=store.db.prepare('SELECT body FROM trace_sessions WHERE id=?').get(commit.session_id);const s=JSON.parse(session.body);const read=(table,order)=>store.db.prepare(`SELECT body FROM ${table} WHERE session_id=? ORDER BY ${order}`).all(s.session_id).map(r=>JSON.parse(r.body));const packet={...s,events:read('trace_messages','sequence'),revisions:read('trace_revisions','revision'),confirmations:read('trace_confirmations','rowid'),commit};const verified=verifyNegotiationPacket(packet);valid=verified.verdict==='VALID'&&commit.deal_hash===record.dealHash&&hash(record.deal)===commit.deal_hash&&s.mandate_id===record.mandateId&&hash(JSON.parse(store.db.prepare('SELECT body FROM mandates WHERE id=?').get(record.mandateId).body))===s.mandate_hash;reason=valid?'BILATERAL_COMMIT_VERIFIED':verified.reason??'COMMIT_BINDING_MISMATCH';}
 return [{name:'BILATERAL_AGREEMENT',pass:valid,actual:reason,expected:'BILATERAL_COMMIT_VERIFIED'}];
}

export function exportedNegotiation(store,dealId){
 if(!store.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='trace_commits'").get())return null;
 const row=store.db.prepare('SELECT body FROM trace_commits WHERE deal_id=?').get(dealId);if(!row)return null;const commit=JSON.parse(row.body),s=JSON.parse(store.db.prepare('SELECT body FROM trace_sessions WHERE id=?').get(commit.session_id).body);
 const read=(table,order)=>store.db.prepare(`SELECT body FROM ${table} WHERE session_id=? ORDER BY ${order}`).all(s.session_id).map(r=>JSON.parse(r.body));return {...s,events:read('trace_messages','sequence'),revisions:read('trace_revisions','revision'),confirmations:read('trace_confirmations','rowid'),audit:read('trace_audit','seq'),commit};
}
