import {randomUUID} from 'node:crypto';import {mkdirSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
import {DealStore} from '../deal-escrow/store.ts';import {DealEngine} from '../deal-escrow/engine.ts';import {openChain} from '../deal-escrow/chain.mjs';import {receipt,verifyReceipt} from '../deal-escrow/audit.ts';import {referenceRows} from '../deal-escrow/reference.ts';import {verificationSource} from '../deal-escrow/verification-source.mjs';import {hash,ensure} from '../deal-escrow/domain.ts';
import {NegotiationLedger,verifyNegotiationPacket,signedConfirmation} from './ledger.mjs';import {ConversationModel} from './kiln.mjs';import {newMandate,participants,opening,openingInterpretation,priceInterpretation,send,fixtureSession,confirmBoth} from './scenario.mjs';

export async function runDealTrace({live=false,onProgress=()=>{},onMandate=()=>{},cancelled=()=>false,approvalOrigin='SCRIPTED_DEMO_APPROVAL'}={}){
 const run=randomUUID(),out=`artifacts/dealtrace/runs/${run}`,directory=`data/private/dealtrace/${run}`;mkdirSync(out,{recursive:true});
 const source=verificationSource(),report={product:'DealTrace',version:1,run,mode:live?'LIVE_KILN_LOCAL_EVM':'SCRIPTED_LOCAL_EVM',approval_origin:approvalOrigin,status:'RUNNING',stage:'PREPARING',started_at:new Date().toISOString(),source_fingerprint:source.sha256,source_manifest:source.files,sessions:[],usage:[],checks:[],outcomes:[],limits:['Local demo identities and simulated suppliers, not external business authentication.','Kiln extracts candidate semantics; quote inclusion does not prove semantic interpretation. Bilateral signatures confirm the normalized Deal.','Pinned repository reference values validate delivery; this run is not an independent unseen-PDF benchmark.','No A2A/AP2/ERC-8183 compatibility claim. Signed internal-orchestrator capture envelope only.','No hidden chain-of-thought stored. Only outward message content and extraction tool arguments.','Local test asset transactions; previous Sepolia evidence belongs to the escrow backend, not a new DealTrace public run.','NPU hardware energy and AI superiority are not measured.']};
 const save=(name,data)=>writeFileSync(`${out}/${name}`,JSON.stringify(data,null,2)+'\n');save('plan.json',{run,started_at:report.started_at,source_fingerprint:source.sha256,live,max_calls:live?10:0,expected:['seller B semantic conflict','matching bilateral commitment','normal payout','wrong-value refund','repeat agreement but preview stops funding','over-budget mutual agreement blocked','divergent confirmation blocked','tampered message invalid']});
 let chain,store,engine,ledger,main,other;
 const refresh=stage=>{report.stage=stage;if(ledger)report.sessions=[main,other,...(report.extra_sessions??[])].filter(Boolean).map(s=>ledger.session(s.session_id));report.usage=store?.usage()??[];save('progress.json',report);onProgress(structuredClone(report));};
 const checkpoint=()=>ensure(!cancelled(),'HUMAN_STOPPED');
 try{
  chain=await openChain({directory,devnetRpc:null});store=new DealStore(`${directory}/state.sqlite`);engine=new DealEngine(store,chain);ledger=new NegotiationLedger(engine);const actors=participants(),m=newMandate(engine);report.mandate=m;report.network=chain.deployment;onMandate({engine,mandate:m});const model=live?new ConversationModel(r=>store.telemetry(run,r),10,proposal=>{report.semantic_proposals??=[];report.semantic_proposals.push(proposal);save('semantic-proposals.json',report.semantic_proposals);}):null;
  main=ledger.create(m.mandate_id,actors.buyer,actors.sellerA);const first=send(ledger,main.session_id,actors.buyer,opening);refresh('BUYER_REQUEST');
  // This opening is generated from the already-approved fixed task profile, not arbitrary input.
  // Compile it without another inference or an opportunity to reinterpret spending authority.
  checkpoint();assert.equal(first.content,opening);const firstInterpretation=openingInterpretation(first);ledger.interpret(main.session_id,firstInterpretation);ledger.note(main.session_id,'APPROVED_TASK_COMPILED',{template_hash:hash(opening),source:'Fixed human-approved demo task, not free-text extraction',model_calls:0});refresh('COMPILING_TERMS');
  const speak=async(actor,instruction,scripted,price=null)=>{checkpoint();const s=ledger.session(main.session_id);const content=live?(await model.speak(actor.id,instruction,s.events.map(e=>({sender:e.sender_agent,content:e.content})))).content:scripted;checkpoint();const event=send(ledger,s.session_id,actor,content);refresh('NEGOTIATING');const proposal=live?(await model.extract([event],s.revisions.at(-1)?.terms??{})).args.interpretations[0]:price===null?{event_id:event.event_id,kind:'accept',patch:[]}:priceInterpretation(event,price);ledger.interpret(s.session_id,proposal);refresh('COMPILING_TERMS');};
  await speak(actors.sellerA,'You can supply exactly the requested four actual quarters with official cells. Your initial asking price is 2.20 DEMO. Offer it with a five-minute delivery window and accept the requested refund conditions.','I can deliver those exact four actual quarters with official source cells for 2.20 DEMO in 5 minutes; same refund conditions.',220);
  await speak(actors.buyer,'The seller asks above your 2.00 DEMO limit. Counter with 1.80 DEMO, keep all original source and delivery requirements. Do not claim the seller has accepted.','I counter 1.80 DEMO with the same original source cells and five-minute delivery terms.',180);
  await speak(actors.sellerA,'Your floor price is 1.90 DEMO. Reject any price below it and counter 1.90 DEMO, with 5 minutes from escrow funding and all other buyer-requested terms unchanged.','I counter 1.90 DEMO, 5 minutes from escrow funding, original source cells, same other terms.',190);
  await speak(actors.buyer,'Accept the seller counteroffer only if its price is at most 2.00 DEMO and it keeps the requested actual quarterly data, sources and five-minute deadline. Respond briefly; this is conversational assent, not a signature.','Agreed.');
  // Separate seller session prevents one seller's proposals from altering another's Deal.
  other=ledger.create(m.mandate_id,actors.buyer,actors.sellerB);send(ledger,other.session_id,actors.buyer,opening);checkpoint();const cheap=live?(await model.speak('seller-b','You can only provide annual CAPEX forecasts for 2025, not realized quarterly cash outflows. Offer your different product honestly for 1.50 DEMO. Do not claim it satisfies the original task.',[{sender:actors.buyer.id,content:opening}])).content:'I offer annual CAPEX forecasts for 2025 for 1.50 DEMO.';send(ledger,other.session_id,actors.sellerB,cheap);refresh('OTHER_SELLER');
  checkpoint();const be=ledger.session(other.session_id).events;
  // Identical opening text: reuse its validated semantic proposal with a new event ID.
  assert.equal(be[0].content,first.content);ledger.interpret(other.session_id,{...structuredClone(firstInterpretation),event_id:be[0].event_id});ledger.note(other.session_id,'EXTRACTION_CACHE_REUSED',{content_hash:hash(first.content),source_event:first.event_id,target_event:be[0].event_id});
  const bProposal=live?(await model.extract([be[1]],ledger.session(other.session_id).revisions.at(-1).terms)).args.interpretations[0]:{event_id:be[1].event_id,kind:'propose',patch:[{field:'price_minor',value:150,quote:cheap},{field:'metric',value:'ANNUAL_CAPEX_FORECAST',quote:cheap},{field:'periods',value:['2025'],quote:cheap}]};ledger.interpret(other.session_id,bProposal);
  assert(ledger.session(other.session_id).revisions.at(-1).conflicts.some(c=>c.field==='metric'),'SELLER_B_CONFLICT_NOT_DETECTED');report.checks.push({name:'Annual forecast rejected',pass:true});refresh('CONFLICT_BLOCKED');
  checkpoint();main=ledger.session(main.session_id);const final=main.revisions.at(-1);assert.equal(final.conflicts.length,0);assert.equal(final.terms.price_minor,190,'UNEXPECTED_NEGOTIATED_PRICE');assert(final.conversation_assent?.agent===actors.buyer.id,'BUYER_ASSENT_NOT_EXTRACTED');
  const before=await chain.provider.getTransactionCount(chain.wallet.address);assert.throws(()=>ledger.commit(main.session_id),/BILATERAL_CONFIRMATION_REQUIRED/);report.checks.push({name:'Conversation assent alone cannot fund',pass:true});
  const divergent={...signedConfirmation(main,final,actors.sellerA),deal_hash:'0x'+'f'.repeat(64)};assert.throws(()=>ledger.confirm(main.session_id,divergent),/DEAL_DIVERGENCE/);report.checks.push({name:'Different Deal hashes blocked',pass:true});
  confirmBoth(ledger,main.session_id,actors);refresh('BILATERAL_COMMITTED');
  async function result(id,label){const r=receipt(engine,id),v=await verifyReceipt(r,chain);assert.equal(v.verdict,'VALID',JSON.stringify(v));save(`${id}.receipt.json`,r);save(`${id}.verification.json`,v);report.outcomes.push({label,deal_id:id,state:r.state,deal_hash:r.deal_hash,transactions:r.transactions,policy:r.evidence.policy,validation:r.evidence.validation??null,control:r.control,receipt_file:`${id}.receipt.json`,verification:v});return r;}
  checkpoint();await engine.fund(main.deal_id);assert.equal(store.get(main.deal_id).state,'ESCROW_FUNDED');refresh('ESCROW_FUNDED');
  const bad=referenceRows();bad[0].capex=3441;bad[0].source_value=-3441;await engine.deliver(main.deal_id,JSON.stringify(bad));assert.equal(store.get(main.deal_id).state,'REFUNDED');await result(main.deal_id,'협상한 첫 거래 · 오납품 환불');report.checks.push({name:'Wrong-value refund creates scoped preview requirement',pass:!!store.control(m.company_id,'seller-a')});refresh('REFUNDED_MEMORY_ADDED');
  // A new explicitly scoped fixture purchase reuses the resulting negotiated terms.
  checkpoint();const repeat=fixtureSession(ledger,m,actors);report.extra_sessions=[repeat];confirmBoth(ledger,repeat.session_id,actors);const nonce=await chain.provider.getTransactionCount(chain.wallet.address);await engine.fund(repeat.deal_id);assert.equal(store.get(repeat.deal_id).state,'PREVIEW_REQUIRED');assert.equal(store.operation(repeat.deal_id,'fund'),null);assert.equal(await chain.provider.getTransactionCount(chain.wallet.address),nonce);await result(repeat.deal_id,'다시 합의했지만 샘플 없이는 예치 차단');report.checks.push({name:'Repeat mutual agreement stopped by prior outcome',pass:true});
  checkpoint();const high=fixtureSession(ledger,newMandate(engine,{company_id:'trace-budget-check'}),actors,{price:220});report.extra_sessions.push(high);confirmBoth(ledger,high.session_id,actors);await engine.fund(high.deal_id);assert.equal(store.get(high.deal_id).state,'BLOCKED');assert.equal(store.operation(high.deal_id,'fund'),null);await result(high.deal_id,'합의는 유효하지만 2.20 DEMO는 권한 밖');report.checks.push({name:'Mutual agreement over human budget cannot fund',pass:true});
  checkpoint();const good=fixtureSession(ledger,newMandate(engine,{company_id:'trace-success-check'}),actors);report.extra_sessions.push(good);confirmBoth(ledger,good.session_id,actors);await engine.fund(good.deal_id);await engine.deliver(good.deal_id,JSON.stringify(referenceRows()));assert.equal(store.get(good.deal_id).state,'SETTLED');await result(good.deal_id,'별도 정상 거래 · 네 값 검수 후 지급');report.checks.push({name:'Correct delivery paid under a separate mandate',pass:true});
  const tampered=ledger.packet(main.session_id);tampered.events[3].content='We agreed to 2.10 DEMO.';assert.equal(verifyNegotiationPacket(tampered).verdict,'INVALID');save('tampered-negotiation.json',tampered);report.checks.push({name:'Changed message fails signed provenance verification',pass:true});
  for(const s of [main,other,...report.extra_sessions]){const packet=ledger.packet(s.session_id);save(`${s.session_id}.conversation.json`,packet);assert.equal(verifyNegotiationPacket(packet).verdict,'VALID');}
  report.checks.push({name:'All recorded conversation packets verify',pass:true});const locked=await chain.provider.getBalance(chain.deployment.contract);assert.equal(locked,0n);report.final_locked_wei=locked.toString();report.controller_transactions=(await chain.provider.getTransactionCount(chain.wallet.address))-before;report.status='PASS';refresh('REPEAT_FUNDING_BLOCKED');
 }catch(error){report.status=cancelled()?'STOPPED':'FAIL';report.error=/^[A-Z0-9_: -]+$/.test(error.message)?error.message.slice(0,180):'DEALTRACE_RUN_FAILED';report.diagnostic=String(error.message).slice(0,800);refresh('STOPPED');
  if(engine&&chain){for(const r of store.list())if(r.state==='ESCROW_FUNDED'){try{await chain.provider.send('evm_increaseTime',[r.deal.deadline+1]);await chain.provider.send('evm_mine',[]);await engine.expire(r.deal.deal_id);}catch{report.cleanup_attention=true;}}}
 }finally{report.completed_at=new Date().toISOString();report.usage=store?.usage()??[];report.summary={checks:report.checks.length,passed:report.checks.filter(c=>c.pass).length,model_calls:report.usage.length,total_tokens:report.usage.reduce((n,r)=>n+(r.total_tokens??0),0),public_chain_transactions:0,real_human_participants:approvalOrigin==='BROWSER_HUMAN_APPROVAL'?null:0};report.ending_source_fingerprint=verificationSource().sha256;if(report.ending_source_fingerprint!==source.sha256){report.status='FAIL';report.error='SOURCE_CHANGED_DURING_RUN';}if(ledger)report.sessions=[main,other,...(report.extra_sessions??[])].filter(Boolean).map(s=>ledger.session(s.session_id));delete report.extra_sessions;save('report.json',report);writeFileSync('artifacts/dealtrace/latest.json',JSON.stringify({run,status:report.status,report:`${out}/report.json`},null,2)+'\n');onProgress(structuredClone(report));store?.close();await chain?.close();}
 return report;
}
