import {efficiency} from './efficiency.mjs';
import {randomUUID} from 'node:crypto';
import {existsSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {DealStore} from '../deal-escrow/store.ts';import {DealEngine} from '../deal-escrow/engine.ts';import {openChain} from '../deal-escrow/chain.mjs';import {receipt,verifyReceipt} from '../deal-escrow/audit.ts';import {referenceRows} from '../deal-escrow/reference.ts';import {verificationSource} from '../deal-escrow/verification-source.mjs';import {hash,ensure} from '../deal-escrow/domain.ts';import {observeOperation,saveJson,readJson} from '../deal-escrow/public-run.mjs';
import {NegotiationLedger,expectedTerms,verifyNegotiationPacket} from './ledger.mjs';import {ConversationModel} from './kiln.mjs';import {newMandate} from './scenario.mjs';import {assuranceProfile,claimHistory} from './claims.mjs';import {startAgent} from './agent-client.mjs';

export const procurementOpening='Need actual quarterly facility investment cash outflow for 2025-Q1, 2025-Q2, 2025-Q3, 2025-Q4. Original official source cells required. Deliver in 5 minutes from the escrow funding block. Refund the buyer on delivery mismatch or expiry. All seller fees must be included in the fixed price. My human mandate allows at most 40.00 DEMO for this task.';
const openingProposal=e=>({event_id:e.event_id,kind:'propose',patch:[...Object.entries(expectedTerms).map(([field,value])=>({field,value,quote:procurementOpening})),{field:'deadline_seconds',value:300,quote:'5 minutes'}]});

export async function runDealTrace({live=false,onProgress=()=>{},onMandate=()=>{},cancelled=()=>false,approvalOrigin='SCRIPTED_DEMO_APPROVAL',publicNetwork=false,chainDirectory=null,resumeRun=null}={}){
 if(resumeRun)ensure(/^[a-f0-9-]{36}$/.test(resumeRun),'RUN_ID');if(publicNetwork)ensure(chainDirectory&&existsSync(`${chainDirectory}/deployment.json`),'PROVISIONED_SEPOLIA_DIRECTORY_REQUIRED');
 const run=resumeRun??randomUUID(),out=`artifacts/dealtrace/runs/${run}`,directory=`data/private/dealtrace/${run}`;mkdirSync(directory,{recursive:true});mkdirSync(out,{recursive:true});
 const source=verificationSource(),journalFile=`${directory}/execution.json`,journal=resumeRun?readJson(journalFile):{run,sessions:{},mandates:{},claims:{}};
 const report=resumeRun?readJson(`${out}/report.json`):{product:'DealTrace',version:3,run,mode:(live?'LIVE_KILN_':'SCRIPTED_')+(publicNetwork?'SEPOLIA':'LOCAL_EVM'),status:'RUNNING',started_at:new Date().toISOString(),approval_origin:approvalOrigin,source_fingerprint:source.sha256,source_manifest:source.files,sessions:[],session_roles:{},outcomes:[],usage:[],checks:[],limits:['Buyer/Seller are separate local processes with separate keys and stores; all are operated by the demo author, not independently authenticated organizations.','Pinned official source/reference validation; not general factual certification or evidence of paid customer demand.','Signed HTTP envelope, not an A2A/AP2 compatibility claim.','Controlled invoice overcharge and wrong-value delivery are labeled attack fixtures.','Only visible messages and structured outputs are retained; hidden chain-of-thought is not stored.','DEMO uses test-asset units. Gas is a separately bounded operator cost.','No measured NPU power advantage.']};
 if(resumeRun){ensure(journal.financial_ready,'INCOMPLETE_INFERENCE_REQUIRES_REVIEW');ensure(report.version===3&&report.source_fingerprint===source.sha256,'RESUME_SOURCE_MISMATCH');ensure(report.mode===(live?'LIVE_KILN_':'SCRIPTED_')+(publicNetwork?'SEPOLIA':'LOCAL_EVM'),'RESUME_MODE_MISMATCH');report.status='RUNNING';delete report.error;delete report.diagnostic;}
 let chain,store,engine,ledger;const agents={};const save=(name,value)=>saveJson(`${out}/${name}`,value),persist=()=>saveJson(journalFile,journal),checkpoint=()=>ensure(!cancelled(),'HUMAN_STOPPED');
 const check=(name,pass=true)=>{assert(pass,name);const old=report.checks.find(c=>c.name===name);if(old)old.pass=pass;else report.checks.push({name,pass});};
 const refresh=stage=>{report.stage=stage;if(ledger)report.sessions=Object.values(journal.sessions).map(id=>ledger.session(id));report.session_roles={...journal.sessions};report.usage=store?.usage()??[];report.financial_states=store?.list().map(r=>({deal_id:r.deal.deal_id,state:r.state,claims:claimHistory(store,r.deal.deal_id),transactions:Object.fromEntries(['fund','release','refund'].flatMap(k=>{const op=store.operation(r.deal.deal_id,k);return op?[[k,{status:op.status,tx_hash:op.txHash}]]:[];}))}))??[];save('progress.json',report);onProgress(structuredClone(report));};
 try{
  chain=await openChain({directory:publicNetwork?chainDirectory:directory,publicNetwork,devnetRpc:null});store=new DealStore(`${directory}/state.sqlite`);engine=new DealEngine(store,chain);ledger=new NegotiationLedger(engine);report.network=chain.deployment;report.reference_rows=referenceRows();
  for(const role of ['buyer-agent','seller-a','seller-b'])agents[role]=await startAgent(`${directory}/agents/${role}`,role);
  report.agent_processes=Object.values(agents).map(a=>({role:a.role,pid:a.pid,public_key:a.identity.public_key,transport:'HTTP loopback',private_key_returned:false}));check('Three agent processes have separate identities',new Set(report.agent_processes.map(a=>a.pid)).size===3&&new Set(report.agent_processes.map(a=>a.public_key)).size===3);
  const mandate=(name,patch={})=>{if(!journal.mandates[name]){const m=newMandate(engine,{company_id:`dealtrace-${run}`,task_budget_minor:4000,max_single_minor:4000,deal_assurance_required:true,...patch});journal.mandates[name]=m.mandate_id;persist();}return store.mandate(journal.mandates[name]);};
  const m=mandate('main');report.mandate=m;onMandate({engine,mandate:m});
  async function open(name,m,seller='seller-a'){
   if(!journal.sessions[name]){const s=ledger.create(m.mandate_id,agents['buyer-agent'].identity,agents[seller].identity,assuranceProfile(chain.deployment,seller));journal.sessions[name]=s.session_id;persist();}
   const s=ledger.session(journal.sessions[name]);for(const role of [s.buyer,s.seller])await agents[role].request('/open',{...s,network:chain.deployment});return s;
  }
  async function speak(s,role,request_id,scripted,instruction='',useLive=false){
   checkpoint();const result=await agents[role].request('/speak',{session_id:s.session_id,request_id,scripted,instruction,live:useLive});for(const u of result.usage??[])store.telemetry(run,u);ensure(!result.error,result.error??'AGENT_INFERENCE_FAILED');
   const event=result.event,current=ledger.session(s.session_id);if(!current.events.some(e=>e.event_id===event.event_id))ledger.append(s.session_id,event);
   await agents[event.recipient_agent].request('/receive',{session_id:s.session_id,event});refresh('NEGOTIATING');return event;
  }
  async function confirm(s){const packet=ledger.packet(s.session_id);if(packet.commit)return packet.commit;for(const role of [s.buyer,s.seller]){const response=await agents[role].request('/confirm',{packet});ledger.confirm(s.session_id,response.ack);ledger.note(s.session_id,'PARTY_REVIEWED_COMPLETE_DEAL',response.review);}return ledger.commit(s.session_id);}
  const semantics=live?new ConversationModel(u=>store.telemetry(run,u),5,p=>{report.semantic_proposals??=[];report.semantic_proposals.push(p);}):null;
  const compile=async(s,e,patch=[],kind='propose',useLive=false)=>{const proposal=useLive?(await semantics.extract([e],ledger.session(s.session_id).revisions.at(-1)?.terms??{})).args.interpretations[0]:{event_id:e.event_id,kind,patch:patch.map(([field,value])=>({field,value,quote:e.content}))};ledger.interpret(s.session_id,proposal);refresh('COMPILING_TERMS');};
  let main;
  if(!resumeRun){
   save('plan.json',{run,version:3,max_model_calls:10,max_chain_transactions:4,main_budget_minor:4000,main_agreed_minor:2600,attack_claim_minor:3100,source_fingerprint:source.sha256,simulated:['invoice overcharge','wrong value delivery','seller business constraints'],actual:['HTTP role processes','signatures','policy checks','EVM transactions',...(live?['Kiln inference']:[])]});
   main=await open('normal',m);const e=await speak(main,'buyer-agent','opening',procurementOpening);ledger.interpret(main.session_id,openingProposal(e));
   const rounds=[['seller-a','offer','I can provide all four actual quarters with official source cells for 30.00 DEMO. Delivery in 10 minutes from escrow funding, with the requested refund conditions.','Offer 30.00 DEMO all-in for the requested task. Your first proposed delivery is 10 minutes. Keep original source cells and requested refund terms.',[['price_minor',3000],['deadline_seconds',600]]],['buyer-agent','counter','I counter 25.00 DEMO. Deliver in 5 minutes from escrow funding, with all original source cells.','Counter 25.00 DEMO all-in, delivery in 5 minutes from escrow funding, keeping original source cells and all other requirements.',[['price_minor',2500],['deadline_seconds',300]]],['seller-a','counter','26.00 DEMO all-in is my minimum. I can deliver in 5 minutes from escrow funding, with all four source cells and the same refund conditions.','Your minimum is 26.00 DEMO. Counter that all-in price with 5 minutes from escrow funding, official original cells and unchanged refund conditions.',[['price_minor',2600],['deadline_seconds',300]]],['buyer-agent','accept','Accepted: 26.00 DEMO all-in, five minutes from escrow funding and all four original source cells.','Accept the last 26.00 DEMO offer if it preserves the requested work, official cells, 5-minute window and refund. Brief outward assent only.',[]]];
   for(const [role,key,text,instruction,patch] of rounds){const event=await speak(main,role,key,text,instruction,live);checkpoint();await compile(main,event,patch,key==='accept'?'accept':'propose',live);}
   const other=await open('semantic_conflict',m,'seller-b'),o=await speak(other,'buyer-agent','opening',procurementOpening);ledger.interpret(other.session_id,openingProposal(o));
   const b=await speak(other,'seller-b','offer','I offer annual CAPEX forecasts for 2025 for 15.00 DEMO.','Offer annual CAPEX forecasts for 2025 for 15.00 DEMO. You cannot provide quarterly actuals; state the different product clearly.',live);await compile(other,b,[['price_minor',1500],['metric','ANNUAL_CAPEX_FORECAST'],['periods',['2025']]],'propose',live);
   check('Annual forecast conflicts with required quarterly actuals',ledger.session(other.session_id).revisions.at(-1).conflicts.some(c=>c.field==='metric'));
   const final=ledger.session(main.session_id).revisions.at(-1);check('Negotiated all-in 26 and five-minute work',final.terms.price_minor===2600&&final.terms.deadline_seconds===300&&final.conversation_assent?.agent==='buyer-agent');
   assert.throws(()=>ledger.commit(main.session_id),/BILATERAL_CONFIRMATION_REQUIRED/);check('Natural acceptance alone cannot fund');await confirm(main);journal.initial_nonce=await chain.provider.getTransactionCount(chain.wallet.address);journal.financial_ready=true;persist();refresh('BILATERAL_COMMITTED');
  }else{main=ledger.session(journal.sessions.normal);await engine.recover();}
  const operation=(id,kind,start)=>observeOperation(engine,id,kind,start,{onWait:()=>refresh(`WAITING_${kind.toUpperCase()}_CONFIRMATION`)});
  async function result(s,label){const r=receipt(engine,s.deal_id),v=await verifyReceipt(r,chain);assert.equal(v.verdict,'VALID',JSON.stringify(v));save(`${s.deal_id}.receipt.json`,r);save(`${s.deal_id}.verification.json`,v);const item={label,deal_id:s.deal_id,state:r.state,deal_hash:r.deal_hash,transactions:r.transactions,policy:r.evidence.policy,validation:r.evidence.validation??null,delivery:r.evidence.delivery??null,claims:claimHistory(store,s.deal_id),control:r.control,receipt_file:`${s.deal_id}.receipt.json`,verification:v};const i=report.outcomes.findIndex(o=>o.deal_id===s.deal_id);if(i<0)report.outcomes.push(item);else report.outcomes[i]=item;}
  async function fund(s){checkpoint();const op=store.operation(s.deal_id,'fund');if(op?.status!=='CONFIRMED')await operation(s.deal_id,'fund',op?undefined:()=>engine.fund(s.deal_id));refresh('ESCROW_FUNDED');}
  async function delivery(s,wrong=false){const delivered=await agents[s.seller].request('/delivery',{session_id:s.session_id,wrong});if(store.get(s.deal_id).state==='ESCROW_FUNDED'){if(wrong)await operation(s.deal_id,'refund',()=>engine.deliver(s.deal_id,delivered.raw));else await engine.deliver(s.deal_id,delivered.raw);}return delivered;}
  await fund(main);checkpoint();const delivered=await delivery(main);refresh('DELIVERY_VERIFIED_AWAITING_CLAIM');
  const claim=async(name,amount)=>{if(!journal.claims[name]){journal.claims[name]=randomUUID();persist();}return agents[main.seller].request('/claim',{session_id:main.session_id,delivery_hash:delivered.hash,amount_minor:amount,claim_id:journal.claims[name]});};
  const incorrect=await claim('overcharge',3100);
  if(!journal.overcharge_observation){const before=await chain.provider.getTransactionCount(chain.wallet.address);const rejection=await engine.claim(main.deal_id,incorrect);assert.equal(rejection.decision.reason,'CLAIM_AMOUNT');assert.equal(store.operation(main.deal_id,'release'),null);assert.equal(await chain.provider.getTransactionCount(chain.wallet.address),before);journal.overcharge_observation={checked_at:new Date().toISOString(),budget_minor:4000,agreed_minor:2600,claimed_minor:3100,state:store.get(main.deal_id).state,controller_nonce_before:before,controller_nonce_after:before,escrow:await chain.inspect(store.get(main.deal_id).dealHash)};persist();}
  report.overcharge_observation=journal.overcharge_observation;check('31 is under the budget but cannot change the committed 26');refresh('INVOICE_31_BLOCKED');
  const correct=await claim('corrected',2600),release=store.operation(main.deal_id,'release');if(release?.status!=='CONFIRMED')await operation(main.deal_id,'release',release?undefined:()=>engine.claim(main.deal_id,correct));check('Corrected 26 paid exactly once',store.get(main.deal_id).state==='SETTLED');await result(main,'합의 26 → 청구 31 차단 → 정정 26 지급');refresh('CORRECTED_26_PAID');
  async function fixture(name,mandateName=name){const fm=mandate(mandateName),s=await open(name,fm);let current=ledger.session(s.session_id);if(!current.events.length){const e=await speak(s,'buyer-agent','opening',procurementOpening);ledger.interpret(s.session_id,openingProposal(e));}current=ledger.session(s.session_id);if(current.events.length===1){const e=await speak(s,s.seller,'offer','26.00 DEMO all-in for all four requested actual quarters, with the same five-minute window and refund terms.');await compile(s,e,[['price_minor',2600]]);}current=ledger.session(s.session_id);if(current.events.length===2){const e=await speak(s,'buyer-agent','accept','Agreed.');await compile(s,e,[],'accept');}await confirm(s);return s;}
  checkpoint();const bad=await fixture('bad_delivery');await fund(bad);await delivery(bad,true);await result(bad,'별도 작업 · 오납품 환불');check('Wrong delivery refunds and creates company/seller preview control',!!store.control(m.company_id,'seller-a'));refresh('REFUND_ADDS_PREVIEW');
  checkpoint();const repeat=await fixture('repeat');const before=await chain.provider.getTransactionCount(chain.wallet.address);if(!store.events(repeat.deal_id).some(e=>e.event_type==='TRANSACTION_BLOCKED'))await engine.fund(repeat.deal_id);check('New mandate does not erase the seller preview requirement',store.get(repeat.deal_id).state==='PREVIEW_REQUIRED'&&!store.operation(repeat.deal_id,'fund')&&await chain.provider.getTransactionCount(chain.wallet.address)===before);await result(repeat,'새 작업 · 샘플 없어서 예치 차단');
  // Each boundary case has its own mandate and retained stop receipt. No synthetic tx hashes.
  const stopped=await fixture('revoked');if(store.mandate(stopped.mandate_id).status==='ACTIVE')store.revoke(stopped.mandate_id);if(!store.events(stopped.deal_id).some(e=>e.event_type==='TRANSACTION_BLOCKED'))await engine.fund(stopped.deal_id);check('Human revocation stops a signed agreement before funding',store.get(stopped.deal_id).state==='BLOCKED'&&!store.operation(stopped.deal_id,'fund'));await result(stopped,'사람이 위임 중지 · 예치 차단');
  const expired=await fixture('expired');const actualClock=engine.clock;engine.clock=()=>store.mandate(expired.mandate_id).expires_at+1;try{if(!store.events(expired.deal_id).some(e=>e.event_type==='TRANSACTION_BLOCKED'))await engine.fund(expired.deal_id);}finally{engine.clock=actualClock;}report.expiry_test='Injected policy clock past the actual stored mandate expiry; no claim of real-time waiting.';check('Expired mandate stops funding',store.get(expired.deal_id).state==='EXPIRED'&&!store.operation(expired.deal_id,'fund'));await result(expired,'만료 경계 · 정책 시계 주입으로 예치 차단');
  for(const id of Object.values(journal.sessions)){const packet=ledger.packet(id);check('Conversation packet '+id+' verifies',verifyNegotiationPacket(packet).verdict==='VALID');save(`${id}.conversation.json`,packet);}
  const tampered=ledger.packet(main.session_id);tampered.events[3].content='We agreed to 31.00 DEMO.';check('Changing a message invalidates the signed evidence',verifyNegotiationPacket(tampered).verdict==='INVALID');save('tampered-negotiation.json',tampered);
  report.agent_evidence=[];for(const a of Object.values(agents))report.agent_evidence.push(await a.request('/evidence'));save('agent-evidence.json',report.agent_evidence);
  report.controller_transactions=await chain.provider.getTransactionCount(chain.wallet.address)-journal.initial_nonce;report.final_locked_wei=(await chain.provider.getBalance(chain.deployment.contract)).toString();report.status='PASS';refresh('COMPLETE');
 }catch(error){report.status=cancelled()?'STOPPED':'FAIL';report.error=/^[A-Z0-9_: -]+$/.test(error.message)?error.message.slice(0,180):'DEALTRACE_RUN_FAILED';report.diagnostic=String(error.message).slice(0,1000);refresh('STOPPED');report.resume_command=`pnpm dealtrace:demo ${live?'--live ':''}${publicNetwork?'--sepolia ':''}--resume=${run}`;report.cleanup_attention=store?.list().some(r=>['ESCROW_FUNDED','DELIVERY_VERIFIED','DELIVERY_SUBMITTED'].includes(r.state));
 }finally{
  report.usage=store?.usage()??[];report.efficiency=efficiency(report.usage);save('efficiency.json',report.efficiency);report.operator_gas_cap_wei=process.env.DEALTRACE_MAX_GAS_WEI??(publicNetwork?'200000000000000':'5000000000000000');report.completed_at=new Date().toISOString();report.summary={checks:report.checks.length,passed:report.checks.filter(c=>c.pass).length,model_calls:report.usage.length,total_tokens:report.usage.reduce((n,u)=>n+(u.total_tokens??0),0),public_chain_transactions:publicNetwork?report.outcomes.reduce((n,o)=>n+Object.values(o.transactions).filter(tx=>tx.status==='CONFIRMED').length,0):0,real_human_participants:approvalOrigin==='BROWSER_HUMAN_APPROVAL'?null:0};report.ending_source_fingerprint=verificationSource().sha256;if(source.sha256!==report.ending_source_fingerprint){report.status='FAIL';report.error='SOURCE_CHANGED_DURING_RUN';}if(ledger)report.sessions=Object.values(journal.sessions).map(id=>ledger.session(id));save('report.json',report);saveJson('artifacts/dealtrace/latest.json',{run,status:report.status,report:`${out}/report.json`});if(publicNetwork)saveJson('artifacts/dealtrace/public-latest.json',{run,status:report.status,report:`${out}/report.json`});onProgress(structuredClone(report));for(const a of Object.values(agents))await a.close();store?.close();await chain?.close();
 }
 return report;
}
