import {randomUUID} from 'node:crypto';
import {now} from '../deal-escrow/domain.ts';
import {researchRequirements} from '../deal-escrow/reference.ts';
import {expectedTerms,identity,signedMessage,signedConfirmation} from './ledger.mjs';

export const opening='Need actual quarterly facility investment cash outflow for 2025-Q1, 2025-Q2, 2025-Q3, 2025-Q4. Original official source cells required. Deliver in 5 minutes from the escrow funding block. Refund the buyer on delivery mismatch or expiry. My human mandate allows at most 2.00 DEMO per purchase.';
export function newMandate(engine,patch={}){const t=engine.clock();return engine.mandate({mandate_id:randomUUID(),company_id:'dealtrace-research-team',buyer_id:'buyer-agent',task_budget_minor:500,max_single_minor:200,allowed_sellers:['seller-a','seller-b'],category:'RESEARCH_DATA',status:'ACTIVE',created_at:t,expires_at:t+3600,task_requirements:{...researchRequirements,max_delivery_seconds:300},...patch});}
export function participants(){return {buyer:identity('buyer-agent'),sellerA:identity('seller-a'),sellerB:identity('seller-b')};}
export function send(ledger,id,actor,content){const s=ledger.session(id);return ledger.append(id,signedMessage(s,actor,actor.id===s.buyer?s.seller:s.buyer,content,ledger.engine.clock()));}
export function openingInterpretation(event){return {event_id:event.event_id,kind:'propose',patch:[...Object.entries(expectedTerms).map(([field,value])=>({field,value,quote:opening})),{field:'deadline_seconds',value:300,quote:'5 minutes'}]};}
export function priceInterpretation(event,value){return {event_id:event.event_id,kind:'propose',patch:[{field:'price_minor',value,quote:event.content}]};}
export function fixtureSession(ledger,m,actors,{seller=actors.sellerA,price=190,forecast=false}={}){const s=ledger.create(m.mandate_id,actors.buyer,seller);const first=send(ledger,s.session_id,actors.buyer,opening);ledger.interpret(s.session_id,openingInterpretation(first));const second=send(ledger,s.session_id,seller,forecast?'1.50 DEMO for annual CAPEX forecast for 2025.':`${(price/100).toFixed(2)} DEMO for the requested quarterly actual values, same other terms.`);ledger.interpret(s.session_id,forecast?{event_id:second.event_id,kind:'propose',patch:[{field:'price_minor',value:150,quote:'1.50 DEMO'},{field:'metric',value:'ANNUAL_CAPEX_FORECAST',quote:'annual CAPEX forecast'},{field:'periods',value:['2025'],quote:'2025'}]}:priceInterpretation(second,price));const last=send(ledger,s.session_id,actors.buyer,'Agreed.');ledger.interpret(s.session_id,{event_id:last.event_id,kind:'accept',patch:[]});return ledger.session(s.session_id);}
export function confirmBoth(ledger,id,actors,seller=actors.sellerA){const s=ledger.session(id),r=s.revisions.at(-1);for(const actor of [actors.buyer,seller])ledger.confirm(id,signedConfirmation(s,r,actor));return ledger.commit(id);}
