import {useCallback,useEffect,useState} from 'react';
import {Wallet,type TypedDataDomain,type TypedDataField} from 'ethers';
import {ArrowRight,Check,Download,FileText,Pause,Play,Plus,RefreshCw,ShieldCheck,Unplug,Zap} from 'lucide-react';
import './purchase.css';
type Consent={purchaseId:string;owner:string;resourceSpecHash:string;totalCap:string;perTxCap:string;expiresAt:string;merchantsHash:string;maxSettlements:string;nonce:string};
type Usage={flow:string;model:string;promptTokens:number|null;completionTokens:number|null;totalTokens:number|null;requestId?:string;latencyMs?:number};
type Purchase={id:string;question:string;consent:Consent;workflow:string;payment:string;delivery:string;reason?:string;stopRequested:boolean;createdAt:string;paidAmount?:string;attempts:{id:string;pid:number}[];usage:Usage[];signature?:string;quote?:{quote:{total:string;subtotal:string;fee:string}};receipt?:{hash:string};answer?:{answer:string;citations:{paragraph_id:string;quote:string}[]};result?:{document:{title:string;paragraphs:{id:string;text:string}[]};delivery:{contentHash:string}}};
type Worker={pid:number|null;ready:boolean;active:string|null;generation:number;restarting:boolean};
type Config={domain:TypedDataDomain;consentTypes:Record<string,TypedDataField[]>;revokeTypes:Record<string,TypedDataField[]>;question:string;kilnConfigured:boolean;model:string;chain:{network:string;chainId:number;vault:string};merchants:{id:string;name:string;address:string}[]};
type Draft={purchase:Purchase;domain:TypedDataDomain;types:Record<string,TypedDataField[]>;value:Consent};
type Event={seq:number;type:string;at:string;runId:string|null;data:Record<string,unknown>};
type Report={status:string;scope?:string;reason?:string;paymentCount?:number;delivery?:string;checks?:{name:string;ok:boolean}[]};
const labels:Record<string,string>={AWAITING_APPROVAL:'승인 대기',APPROVAL_PENDING:'승인 등록 중',READY:'실행 준비',ASSESSING:'자료 필요성 판단 중',PAYING:'지급 확인 중',WAITING_FOR_RESULT:'자료 회수 대기',DELIVERED:'자료 수령',ANSWERING:'근거 답변 작성 중',COMPLETE:'완료',STOPPED:'중지',REVIEW_REQUIRED:'확인 필요',NOT_SUBMITTED:'지급 전',PREPARED:'서명 거래 보관',SUBMITTED:'제출됨',UNKNOWN:'지급 확인 중',CONFIRMING:'최종 확정 대기',SETTLED:'지급 확인',REVOKED:'권한 취소',FAILED_FINAL:'거래 실패 확인',NONE:'수령 전',PENDING:'자료 미수령',RECEIVED_VALID:'자료 수령',UNRECOVERABLE:'자료 회수 불가'};
const reasons:Record<string,string>={RESULT_RESPONSE_LOST:'지급은 확인했지만 자료 응답이 끊겼습니다. 다시 실행하면 기존 구매를 회수합니다.',RESULT_UNRECOVERABLE:'지급 완료 후 판매자가 자료를 제공하지 못했습니다. 새 결제는 하지 않습니다.',BUDGET_EXCEEDED:'수수료를 포함한 총액이 승인 한도를 넘었습니다.',MERCHANT_NOT_ALLOWED:'승인한 판매자 목록에 없습니다.',DEADLINE_EXPIRED:'승인 또는 견적의 기한이 지났습니다.',USER_STOPPED:'사람의 중지 요청으로 실행을 멈췄습니다.',USER_REVOKED:'취소가 체인에 반영됐습니다. 기존 지급은 유지됩니다.',KILN_OUTPUT_TRUNCATED:'모델 응답이 길이 제한으로 끝났습니다. 결제 권한으로 사용하지 않았습니다.',PAYMENT_CONFIRMATION_PENDING:'지급 결과가 불확실하여 새 결제를 보류합니다.',NO_PURCHASE_NEEDED:'Qwen이 추가 구매가 필요하지 않다고 판단했습니다.'};
const eventNames:Record<string,string>={PURCHASE_DRAFTED:'구매 조건 작성',HUMAN_APPROVED:'사람이 구매 1회 승인',EXECUTION_STARTED:'구매 worker 실행',SIGNED_QUOTE:'판매자의 확정 견적',KILN_REQUEST_STARTED:'Kiln 요청',KILN_RESPONSE:'실제 응답과 토큰 기록',SIGNED_TRANSACTION_DURABLE:'지급 전 서명 거래 저장',PAYMENT_BROADCAST_ATTEMPT:'저장한 거래 제출',PAYMENT_CONFIRMED:'체인 지급 확인',DEMO_DROP_RESPONSE_ARMED:'실험: 결과 응답 연결 끊기',RESULT_NOT_RECEIVED:'지급과 미수령을 별도 기록',DOCUMENT_RECEIVED:'기존 구매의 자료 수령',ANSWER_COMPLETED:'근거가 있는 답변',CACHED_RESULT_REUSED:'수령 자료 재사용',EXECUTION_STOPPED:'경계에서 중지',WORKER_EXIT:'worker 프로세스 종료',WORKER_DONE:'worker 작업 종료',PURCHASE_REVOKED:'온체인 권한 취소'};
const money=(value?:string)=>(Number(value??0)/100).toFixed(2);
const short=(value?:string)=>value?value.slice(0,10)+'…'+value.slice(-6):'—';
async function api<T>(route:string,body?:unknown):Promise<T>{const response=await fetch('/api/purchase'+route,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'REQUEST_FAILED');return result;}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function PurchaseApp(){
  const [config,setConfig]=useState<Config|null>(null),[wallet,setWallet]=useState<Wallet|null>(null),[logged,setLogged]=useState(false),[purchases,setPurchases]=useState<Purchase[]>([]),[worker,setWorker]=useState<Worker|null>(null),[selected,setSelected]=useState(''),[events,setEvents]=useState<Event[]>([]),[draft,setDraft]=useState<Draft|null>(null),[question,setQuestion]=useState(''),[per,setPer]=useState('8'),[scenario,setScenario]=useState('drop-response'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[report,setReport]=useState<Report|null>(null),[notice,setNotice]=useState('');
  const p=purchases.find(x=>x.id===selected)??null;
  useEffect(()=>{api<Config>('/config').then(c=>{setConfig(c);setQuestion(c.question);}).catch(e=>setError(e.message));},[]);
  const refresh=useCallback(async()=>{if(!logged)return;const data=await api<{purchases:Purchase[];worker:Worker}>('/dashboard');setPurchases(data.purchases);setWorker(data.worker);},[logged]);
  useEffect(()=>{if(!logged)return;let ended=false;let timer:ReturnType<typeof setTimeout>;const tick=async()=>{try{const data=await api<{purchases:Purchase[];worker:Worker}>('/dashboard');if(!ended){setPurchases(data.purchases);setWorker(data.worker);}if(selected){const list=await api<Event[]>(`/${selected}/events`);if(!ended)setEvents(list);}}catch(e){if(!ended)setError((e as Error).message);}if(!ended)timer=setTimeout(tick,1400);};void tick();return()=>{ended=true;clearTimeout(timer);};},[logged,selected]);
  const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const login=()=>perform(async()=>{let key=localStorage.getItem('cm-purchase-demo-wallet-v3');if(!key){key=Wallet.createRandom().privateKey;localStorage.setItem('cm-purchase-demo-wallet-v3',key);}const w=new Wallet(key),challenge=await api<{nonce:string;message:string}>('/auth/challenge',{address:w.address});await api('/auth/login',{nonce:challenge.nonce,signature:await w.signMessage(challenge.message)});setWallet(w);setLogged(true);});
  const create=()=>perform(async()=>{if(!/^\d{1,5}(?:\.\d{1,2})?$/.test(per))throw new Error('소수 두 자리 이내의 금액을 입력하세요.');const [whole,fraction='']=per.split('.');const minor=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(minor<=0||minor>2000000)throw new Error('유효한 한도를 입력하세요.');const d=await api<Draft>('/draft',{question,perTxCap:String(minor),totalCap:String(Math.max(2000,minor)),durationMinutes:30});setDraft(d);setSelected(d.purchase.id);});
  const approve=()=>perform(async()=>{if(!wallet||!draft)return;await api(`/${draft.purchase.id}/approve`,{signature:await wallet.signTypedData(draft.domain,draft.types,draft.value)});setDraft(null);});
  const run=()=>perform(async()=>{if(!p)return;setReport(null);await api(`/${p.id}/run`,{scenario:p.payment==='SETTLED'?'normal':scenario});});
  const stop=()=>perform(async()=>{if(!p||!wallet||!config)return;const signature=await wallet.signTypedData(config.domain,config.revokeTypes,{purchaseId:p.id,owner:wallet.address});await api(`/${p.id}/stop`,{signature});});
  const restart=()=>perform(async()=>{const result=await api<{previous:Worker;current:Worker}>('/worker/restart',{});setNotice(`worker ${result.previous.pid} 종료 → ${result.current.pid} 시작. 구매 기록은 그대로 유지됩니다.`);});
  const verify=()=>perform(async()=>{if(!p)return;const bundle=await api(`/${p.id}/evidence`);setReport(await api<Report>('/verify',bundle));});
  return <div className="purchase-console">
    <header className="pc-header"><a className="pc-brand" href="/purchase"><ShieldCheck size={25}/><span>Control Memory<small>RESEARCH PURCHASE / v3</small></span></a><div className="pc-header-meta"><span>테스트 자산 · 합성 자료</span><span>{logged?short(wallet?.address):'로컬 데모 지갑'}</span>{!logged&&<button className="pc-button pc-primary" disabled={busy||!config} onClick={login}>데모 지갑 연결 <ArrowRight size={16}/></button>}</div></header>
    <div className="pc-layout"><aside className="pc-sidebar"><div className="pc-section-label">한 번의 구매, 이어지는 작업</div><button className="pc-button pc-new" disabled={busy} onClick={()=>{setSelected('');setDraft(null);setReport(null);}}><Plus size={17}/>새 자료 조회</button><div className="pc-history">{purchases.map(item=><button key={item.id} className={selected===item.id?'selected':''} onClick={()=>{setSelected(item.id);setDraft(null);setReport(null);setEvents([]);}}><span>{item.question}</span><small>{labels[item.workflow]??item.workflow} · {money(item.paidAmount)} TC</small></button>)}</div><div className="pc-sidebar-note"><ShieldCheck size={19}/><strong>새 실행은 새 구매 허가가 아닙니다.</strong><p>승인한 구매 ID당 지급은 최대 한 번입니다.</p><a href="http://127.0.0.1:3400/">기존 실험 콘솔 ↗</a></div></aside>
    <main className="pc-main">
      {error&&<div className="pc-message pc-error" role="alert">{reasons[error]??error}<button aria-label="오류 닫기" onClick={()=>setError('')}>×</button></div>}
      {notice&&<div className="pc-message" role="status">{notice}</div>}
      <div className="pc-topline"><span className="pc-eyebrow">한 번 허락한 자료, 한 번만 결제</span><span className="pc-network">● {config?.chain.network??'연결 중'} · {config?.chain.chainId??'—'}</span></div>
      {!p&&!draft?<section className="pc-compose"><h1>돈은 나갔는데,<br/>자료가 안 왔다면.</h1><p className="pc-intro">리서치봇을 다시 실행해도 같은 자료를 또 사지 않도록.<br/>구매 한 건의 승인부터 지급, 회수, 근거까지 이어집니다.</p><label className="pc-field">확인할 질문<textarea rows={3} value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000}/></label><div className="pc-approval-fields"><label className="pc-field">수수료 포함 최대 금액<input type="number" step="0.01" min="0.01" value={per} onChange={e=>setPer(e.target.value)}/><small>TC · 테스트 단위</small></label><div><small>승인 범위</small><strong>자료 조회 1회</strong><span>A사 협업 안내 · 지정 버전 · 30분</span></div></div><button className="pc-button pc-primary" disabled={!logged||busy||!question.trim()} onClick={create}>구매 조건 확인 <ArrowRight size={17}/></button><p className="pc-footnote">팀 운영 자료 API와 로컬 EVM을 사용하는 테스트입니다. 실제 회사의 요금제나 상용 x402 결제가 아닙니다.</p></section>:<>
        <div className="pc-title"><div><h1>{p?.question??draft?.purchase.question}</h1><p>{short(p?.id??draft?.purchase.id)} · 승인 자료 1건 · 최대 {money(p?.consent.perTxCap??draft?.value.perTxCap)} TC</p></div><span className={`pc-status ${p?.workflow==='COMPLETE'?'good':''}`}>{labels[p?.workflow??'AWAITING_APPROVAL']??p?.workflow}</span></div>
        {(draft||p?.workflow==='AWAITING_APPROVAL')&&<section className="pc-card pc-consent"><h2>이 자료를 한 번만 구매하도록 승인합니다.</h2><div className="pc-consent-grid"><div><small>판매자 수수료 포함</small><strong>최대 {money(draft?.value.perTxCap??p?.consent.perTxCap)} TC</strong></div><div><small>지급 횟수</small><strong>최대 1회</strong></div><div><small>유효 기한</small><strong>{new Date(Number(draft?.value.expiresAt??p?.consent.expiresAt)*1000).toLocaleTimeString('ko-KR')}</strong></div></div><p>허용 판매자: {config?.merchants.map(m=>m.name).join(', ')}. 네트워크 가스는 운영자 테스트 ETH로 지원합니다. Kiln 추론 비용도 운영자가 부담합니다.</p><button className="pc-button pc-primary" disabled={busy||!!worker?.active} onClick={()=>{if(!draft&&p&&config){setDraft({purchase:p,domain:config.domain,types:config.consentTypes,value:p.consent});return;}void approve();}}><ShieldCheck size={16}/>{draft?'서명하고 구매 1회 승인':'승인 내용 확인'}</button></section>}
        {p?.signature&&<>
          <div className="pc-stats"><div><small>이번 구매의 지급</small><strong>{['PREPARED','SUBMITTED','UNKNOWN'].includes(p.payment)?'확인 중':<>{money(p.paidAmount)} <em>TC</em></>}</strong><span>{labels[p.payment]??p.payment}</span></div><div><small>자료</small><strong className="pc-state-word">{labels[p.delivery]??p.delivery}</strong><span>{p.result?'서명·요청·내용 hash 검사 통과':'지급 상태와 따로 확인합니다'}</span></div><div><small>실행 / 성공 지급</small><strong>{p.attempts.length} <em>/ {p.receipt?'1':['PREPARED','SUBMITTED','UNKNOWN'].includes(p.payment)?'?':'0'}</em></strong><span>재시작해도 같은 구매 ID</span></div></div>
          {p.reason&&<div className={`pc-message ${p.workflow==='STOPPED'?'pc-warning':''}`} role="status">{reasons[p.reason]??p.reason}</div>}
          <section className="pc-card pc-controls"><div><h2>{p.payment==='SETTLED'?'기존 구매로 이어가기':'자료 조회 실행'}</h2><p>실제 Kiln Qwen3-32B · 판매자의 서명 견적 · 테스트 체인 지급</p></div>{p.payment!=='SETTLED'&&<label className="pc-field">검증 시나리오<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="drop-response">지급 후 결과 응답 끊기</option><option value="normal">정상 수령</option><option value="over-budget">수수료 포함 12 TC 청구</option><option value="unlisted">허용 밖 판매자</option><option value="expired">만료된 견적</option><option value="unrecoverable">지급 후 자료 회수 불가</option></select></label>}<div className="pc-actions"><button className="pc-button pc-primary" disabled={busy||!!worker?.active||p.stopRequested||!worker?.ready} onClick={run}><Play size={16}/>{worker?.active===p.id?'실행 중':p.payment==='SETTLED'?'다시 실행 · 추가 지급 없음':'자료 조회 시작'}</button><button className="pc-button" disabled={busy||p.stopRequested} onClick={stop}><Pause size={16}/>권한 중지</button></div></section>
          <section className="pc-restart"><Unplug size={22}/><div><strong>worker를 실제로 종료하고 다시 켭니다.</strong><p>프로세스 {worker?.pid??'—'} · {worker?.ready?'연결됨':'시작 중'} · 새 worker가 저장 기록과 체인을 대조합니다.</p></div><button className="pc-button" disabled={busy||worker?.restarting} onClick={restart}><RefreshCw size={16}/>worker 재시작</button></section>
          {p.answer&&<section className="pc-card pc-answer"><div className="pc-section-label"><Check size={17}/>자료를 받아 답변을 이어갔습니다</div><h2>{p.answer.answer}</h2>{p.answer.citations.map((citation,index)=><blockquote key={index}>{citation.quote}<cite>{p.result?.document.title} · {citation.paragraph_id}</cite></blockquote>)}<small>인용문 존재 여부는 코드가 확인합니다. 답변 내용의 사실성은 별도 검토 대상입니다.</small></section>}
          <div className="pc-details-grid"><section className="pc-card"><h2>실행 기록</h2><ol className="pc-timeline">{events.slice(-18).map(event=><li key={event.seq}><span>{eventNames[event.type]??event.type}</span><time>{new Date(event.at).toLocaleTimeString('ko-KR')}</time></li>)}</ol></section><div><section className="pc-card"><h2><Zap size={17}/> 실제 추론 사용량</h2>{p.usage.length?p.usage.map((u,index)=><div className="pc-usage" key={index}><strong>{u.flow==='need-assessment'?'자료 필요성 판단':'근거 답변'}</strong><span>입력 {u.promptTokens??'미확인'} / 출력 {u.completionTokens??'미확인'}</span><small>{u.model} · {u.requestId?short(u.requestId):'요청 ID 미확인'}</small></div>):<p>아직 모델 호출이 없습니다.</p>}<p className="pc-footnote">전력 미계측. 복구·금액 검사는 코드로 수행합니다.</p></section><section className="pc-card pc-evidence"><h2><FileText size={17}/> 승인과 지급의 증빙</h2><p>지급 tx: <code>{short(p.receipt?.hash)}</code></p><div className="pc-actions"><button className="pc-button" disabled={busy} onClick={verify}><ShieldCheck size={16}/>체인 대조</button><button className="pc-button" disabled={busy} onClick={()=>perform(async()=>download(await api(`/${p.id}/evidence`),`purchase-${p.id.slice(2,10)}.json`))}><Download size={16}/>증빙 받기</button></div>{report&&<div className={`pc-verdict ${report.status==='VALID'?'good':''}`} role="status"><strong>{report.status}</strong><p>{report.reason??report.scope}</p><small>지급 {report.paymentCount??'미확인'}회 · 자료 {report.delivery??'미확인'}</small></div>}<details><summary>원 서버 없이 검증하기</summary><p>내려받은 증빙, 별도로 신뢰한 배포 manifest, 체인 RPC로 검증 CLI를 실행합니다. 이 화면의 대조 버튼은 현재 서버를 사용합니다.</p><code>node scripts/verify-purchase.mjs bundle.json manifest.json RPC_URL</code></details></section></div></div>
        </>}
      </>}
    </main></div>
  </div>;
}
