import express from 'express';
import {randomBytes} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {getAddress,verifyMessage} from 'ethers';
import {startChain} from './chain.mjs';
import {deployPurchaseChain} from './purchase-chain.mjs';
import {openSepoliaPurchaseChain} from './purchase-public-chain.mjs';
import {Store} from './store.mjs';
import {PurchaseEngine} from './purchase-engine.mjs';
import {PurchaseWorker} from './purchase-worker-control.mjs';
import {ResearchModel} from './purchase-model.mjs';
import {sellerApp,SellerClient} from './purchase-seller.mjs';
import {verifyPurchaseBundle} from './purchase-verifier.mjs';
import {saveSourceSnapshot} from './purchase-source.mjs';
import {CONSENT_TYPES,PURCHASE_REVOKE_TYPES,QUESTION,RESOURCE,sameAddress} from '../shared/purchase.mjs';
const publicTestnet=process.env.PURCHASE_NETWORK==='sepolia';
const directory=path.resolve(process.env.PURCHASE_DATA_DIR??(publicTestnet?'data/private/purchase-sepolia':'data/private/purchase-devnet'));
const port=Number(process.env.PURCHASE_PORT??3500),sellerPort=Number(process.env.PURCHASE_SELLER_PORT??3501);
const base=publicTestnet?await openSepoliaPurchaseChain(directory):await startChain({directory,port:Number(process.env.PURCHASE_RPC_PORT??8546)});
const chain=publicTestnet?base.chain:await deployPurchaseChain(base,{directory});
const database=path.join(directory,'purchases.sqlite'),store=new Store(database),sellerStore=new Store(path.join(directory,'seller.sqlite'));
const sellerServer=sellerApp({chain,store:sellerStore}).listen(sellerPort,'127.0.0.1');await new Promise(r=>sellerServer.once('listening',r));
const sellerUrl=`http://127.0.0.1:${sellerPort}`;
const artifactDirectory=publicTestnet?'artifacts/purchase-sepolia':'artifacts/purchase';
await mkdir(artifactDirectory,{recursive:true});await writeFile(path.join(artifactDirectory,'deployment.json'),JSON.stringify({...chain.deployment,rpcUrl:publicTestnet?'REQUIRES_INDEPENDENT_RPC':chain.deployment.rpcUrl},null,2)+'\n');
const runtime=await saveSourceSnapshot(artifactDirectory);
await writeFile(path.join(directory,'worker-config.json'),JSON.stringify({deployment:chain.deployment,database,sellerUrl,runtime},null,2)+'\n');
const engine=new PurchaseEngine({store,chain,model:new ResearchModel(),seller:new SellerClient({url:sellerUrl,chain}),runtime});
const worker=new PurchaseWorker({directory,onEvent:event=>{if(event.purchaseId)store.event(event.purchaseId,'WORKER_'+event.type.toUpperCase(),event);}});await worker.boot();
const app=express(),origin=`http://127.0.0.1:${port}`,challenges=new Map(),sessions=new Map();
app.disable('x-powered-by');
app.use((req,res,next)=>{if(![`127.0.0.1:${port}`,`localhost:${port}`].includes(req.headers.host))return res.status(403).json({error:'HOST_NOT_ALLOWED'});if(req.headers.origin&&![origin,`http://localhost:${port}`].includes(req.headers.origin))return res.status(403).json({error:'ORIGIN_NOT_ALLOWED'});res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'"});next();});
app.use(express.json({limit:'4mb'}));
app.get('/api/purchase/config',(req,res)=>res.json({mode:publicTestnet?'PUBLIC_TESTNET_TEST_ASSETS':'LOCAL_DEVNET_TEST_ASSETS',model:'qwen3-32b',kilnConfigured:!!process.env.KILN_API_KEY,domain:chain.domain,consentTypes:CONSENT_TYPES,revokeTypes:PURCHASE_REVOKE_TYPES,chain:{...chain.deployment,rpcUrl:publicTestnet?'REQUIRES_INDEPENDENT_RPC':chain.deployment.rpcUrl},question:QUESTION,resource:RESOURCE,merchants:chain.deployment.merchantRegistry.filter(m=>['alpha','beta'].includes(m.id))}));
app.get('/api/purchase/health',async(req,res)=>{try{await chain.provider.getBlockNumber();res.json({status:worker.ready?'READY':'WORKER_OFFLINE',worker:worker.snapshot()});}catch{res.status(503).json({status:'NOT_READY'});}});
app.post('/api/purchase/auth/challenge',(req,res)=>{const address=getAddress(req.body.address),nonce=randomBytes(24).toString('hex'),message=`Control Memory Purchase v3 login\nOrigin: ${origin}\nAddress: ${address}\nNonce: ${nonce}`;challenges.set(nonce,{address,message,expires:Date.now()+120000});res.json({nonce,message});});
app.post('/api/purchase/auth/login',(req,res)=>{const c=challenges.get(req.body.nonce);challenges.delete(req.body.nonce);if(!c||c.expires<Date.now()||!sameAddress(verifyMessage(c.message,req.body.signature),c.address))return res.status(401).json({error:'LOGIN_SIGNATURE'});const token=randomBytes(32).toString('hex');sessions.set(token,{address:c.address,expires:Date.now()+12*3600000});res.cookie('cm_purchase_auth',token,{httpOnly:true,sameSite:'strict',path:'/',maxAge:12*3600000});res.json({address:c.address});});
app.post('/api/purchase/verify',async(req,res)=>res.json(await verifyPurchaseBundle(req.body,{provider:chain.provider,deployment:chain.deployment,artifact:chain.artifact})));
app.use('/api/purchase',(req,res,next)=>{const cookie=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('cm_purchase_auth='))?.slice('cm_purchase_auth='.length);const s=sessions.get(cookie);if(!s||s.expires<Date.now())return res.status(401).json({error:'LOGIN_REQUIRED'});req.owner=s.address;next();});
const own=(req,id)=>{const p=engine.get(id);if(!sameAddress(p.consent.owner,req.owner))throw new Error('FORBIDDEN');return p;};
app.get('/api/purchase/dashboard',(req,res)=>res.json({owner:req.owner,purchases:store.all('purchase').filter(p=>sameAddress(p.consent.owner,req.owner)).map(p=>engine.view(p.id)).reverse(),worker:worker.snapshot()}));
app.post('/api/purchase/draft',async(req,res)=>res.json(await engine.draft(req.owner,req.body)));
app.post('/api/purchase/:id/approve',async(req,res)=>{own(req,req.params.id);if(worker.active)throw new Error('WORKER_BUSY');res.json(await engine.approve(req.params.id,req.body.signature));});
app.post('/api/purchase/:id/run',(req,res)=>{own(req,req.params.id);const scenario=req.body.scenario??'normal';if(!['normal','drop-response','unrecoverable','over-budget','unlisted','expired'].includes(scenario))throw new Error('INVALID_SCENARIO');res.status(202).json(worker.run(req.params.id,scenario));});
app.post('/api/purchase/:id/stop',async(req,res)=>{own(req,req.params.id);res.json(await engine.stop(req.params.id,req.body.signature));});
app.post('/api/purchase/worker/restart',async(req,res)=>{if(worker.active)own(req,worker.active);res.json(await worker.restart());});
app.get('/api/purchase/:id/events',(req,res)=>{own(req,req.params.id);res.json(store.events(req.params.id));});
app.get('/api/purchase/:id/evidence',(req,res)=>{own(req,req.params.id);res.setHeader('Content-Disposition',`attachment; filename="purchase-${req.params.id.slice(2,10)}.json"`);res.json(engine.bundle(req.params.id));});
app.get('/api/purchase/:id/document',(req,res)=>{const p=own(req,req.params.id);if(!p.result)return res.status(404).json({error:'DOCUMENT_NOT_RECEIVED'});res.json(p.result.document);});
let httpPaused=false;
app.post('/api/purchase/:id/testing/pause-http',(req,res)=>{own(req,req.params.id);if(worker.active||httpPaused)throw new Error('WORKER_BUSY');httpPaused=true;res.json({pauseMs:8000,scope:'HTTP_LISTENER_ONLY_CHAIN_RPC_REMAINS_AVAILABLE'});setTimeout(()=>{server.closeAllConnections();server.close(()=>{setTimeout(()=>{server.listen(port,'127.0.0.1');httpPaused=false;},8000);});},100);});
app.get('/',(req,res)=>res.redirect('/purchase'));
app.use(express.static('dist'));
app.get('/{*path}',(req,res)=>res.sendFile('index.html',{root:'dist'}));
app.use((e,req,res,next)=>res.status(e.message==='FORBIDDEN'?403:400).json({error:/^[A-Z_0-9]+$/.test(e.message)?e.message:'REQUEST_FAILED'}));
const server=app.listen(port,'127.0.0.1',()=>console.log(`Purchase recovery console ready: ${origin}/purchase | worker ${worker.child.pid} | ${chain.deployment.network} ${chain.deployment.chainId}`));
let reconciliation=null;
const reconcileTimer=setInterval(()=>{if(reconciliation)return;reconciliation=(async()=>{for(const p of store.all('purchase').filter(p=>p.signature)){try{await engine.sync(p.id);}catch{}}})().finally(()=>{reconciliation=null;});},15000);reconcileTimer.unref();
let closing=false;
async function close(){if(closing)return;closing=true;clearInterval(reconcileTimer);await worker.close();await reconciliation;server.closeAllConnections();sellerServer.closeAllConnections();await Promise.all([new Promise(r=>server.close(r)),new Promise(r=>sellerServer.close(r))]);store.close();sellerStore.close();await base.close();process.exit(0);}
process.on('SIGINT',close);process.on('SIGTERM',close);
