import React,{useEffect,useState} from 'react';
export function Replay(){
  const [record,setRecord]=useState<any>(null),[error,setError]=useState(''),[step,setStep]=useState(Number(new URLSearchParams(location.search).get('step')??0)),[playing,setPlaying]=useState(false);
  useEffect(()=>{fetch('/api/showcase').then(async r=>{if(!r.ok)throw new Error('새 실행 데모가 아직 준비되지 않았습니다.');const v=await r.json();setRecord(v);setStep(s=>Number.isInteger(s)&&s>=0&&s<v.steps.length?s:0);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!playing||!record)return;const timer=setInterval(()=>setStep(s=>Math.min(s+1,record.steps.length-1)),25000);return()=>clearInterval(timer);},[playing,record]);
  const current=record?.steps[step];
  return <main className="showcase"><div className="showcase-top"><a href="/">Agent Deal Escrow</a><span>{record?.network_label??'실제 실행 기록 재생 · 실시간 아님 · 로컬 테스트 자산'}</span></div>{error&&<p role="status">{error}</p>}{current&&<><div className="showcase-title"><p className="eyebrow">검증 가능한 에이전트 거래 · {step+1} / {record.steps.length}</p><h1>{current.title}</h1></div><div className="showcase-metrics">{current.metrics.map((m:any)=><article key={m.label}><span>{m.label}</span><strong>{m.value}</strong></article>)}</div>
    <div className="showcase-content"><p className="showcase-narration">{current.narration}</p>{current.rows&&<table><thead><tr><th>기간</th><th>시설투자 (십억 원)</th><th>원문 부호</th><th>근거</th></tr></thead><tbody>{current.rows.map((r:any)=><tr key={r.quarter}><td>{r.quarter}</td><td>{r.capex.toLocaleString()}</td><td>{r.source_value.toLocaleString()}</td><td>{r.source_page}쪽 · 시설투자 행</td></tr>)}</tbody></table>}{current.quote&&<blockquote>{current.quote}</blockquote>}{current.checks&&<div className="showcase-checks">{current.checks.filter((c:any)=>/^(REFERENCE_|SOURCE_)/.test(c.name)).map((c:any)=><span className={c.pass?'pass':'fail'} key={c.name}>{c.pass?'✓':'✕'} {c.name.replace(/^(REFERENCE_|SOURCE_)/,'')} · {c.pass?'일치':'불일치'}</span>)}</div>}{current.benchmark&&<table><thead><tr><th>비교군</th><th>올바른 결과</th><th>정상 납품</th><th>오차단</th><th>호출</th><th>토큰</th></tr></thead><tbody>{current.benchmark.map((r:any)=><tr key={r.variant}><td>{r.variant}</td><td>{r.correct_outcomes}/{r.tasks}</td><td>{r.delivered}</td><td>{r.false_blocks}</td><td>{r.model_calls}</td><td>{r.total_tokens?.toLocaleString()??'미확인'}</td></tr>)}</tbody></table>}</div>
    <details className="showcase-evidence"><summary>이 장면의 실제 증거</summary><pre>{JSON.stringify(current.evidence,null,2)}</pre></details><div className="showcase-controls"><button onClick={()=>{setStep(0);setPlaying(true);}}>기록 재생</button>{record.steps.map((s:any,i:number)=><button aria-label={`장면 ${i+1}: ${s.title}`} className={i===step?'active':''} key={i} onClick={()=>{setStep(i);setPlaying(false);}}>{i+1}</button>)}<a href="/?study=1">참여자 질문지 ↗</a></div></>}</main>;
}
