import React,{useEffect,useState} from 'react';
import {SourceResult} from './SourceResult';
import './research.css';
const money=(n:number)=>(n/100).toFixed(2);
const labels:Record<string,string>={DEAL_ACCEPTED:'조건 합의',PREVIEW_REQUIRED:'샘플을 먼저 확인해야 합니다',PREVIEW_VERIFIED:'샘플 통과 · 예치 가능',POLICY_APPROVED:'예치 준비',ESCROW_FUNDED:'대금 보관 중',DELIVERY_SUBMITTED:'납품 검수 중',DELIVERY_VERIFIED:'지급 처리 중',SETTLED:'납품 확인 · 지급 완료',REFUNDED:'지급하지 않고 환불 완료',BLOCKED:'예치 전 중단',EXPIRED:'기한 만료',REJECTED:'의뢰 거절'};
async function read(path:string,signal?:AbortSignal){const r=await fetch('/api/'+path,{signal});if(!r.ok)throw new Error('화면 자료를 불러오지 못했습니다.');return r.json();}
export function ResearchWorkbench({data,action,openDeal,openAudit,busy=false}:{data:any;action:(path:string,body?:unknown)=>Promise<any>;openDeal:(id:string)=>void;openAudit:(id:string)=>void;busy?:boolean}){
 const [catalog,setCatalog]=useState<any[]>([]),[documentId,setDocumentId]=useState('lges-2025-pdf'),[source,setSource]=useState<any>(null),[selectedId,setSelectedId]=useState('');
 const [budget,setBudget]=useState('3.00'),[cap,setCap]=useState('2.00'),[seconds,setSeconds]=useState('180'),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[local,setLocal]=useState(false),[firstValue,setFirstValue]=useState(''),[verification,setVerification]=useState<any>(null);
 useEffect(()=>{const controller=new AbortController();void read('research/sources',controller.signal).then(r=>setCatalog(r.documents)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{const controller=new AbortController();setSource(null);setLocal(false);setVerification(null);void read('research/sources/'+encodeURIComponent(documentId),controller.signal).then(setSource).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[documentId]);
 const rows=data.deals.filter((r:any)=>r.deal.requirements.source_document_id===documentId),row=rows.find((r:any)=>r.deal.deal_id===selectedId)??rows[0];
 const requests=(data.research_requests??[]).filter((r:any)=>data.mandates.find((m:any)=>m.mandate_id===r.mandate_id)?.task_requirements?.source_document_id===documentId),request=requests[0];
 const pending=working||busy||request?.status==='RUNNING',ready=source?.ready===true,doc=source?.document,mandate=row?data.mandates.find((m:any)=>m.mandate_id===row.mandateId):null;
 useEffect(()=>{setFirstValue(String(source?.rows?.[0]?.capex??''));setVerification(null);},[source,row?.deal.deal_id]);
 const perform=async(fn:()=>Promise<any>)=>{setWorking(true);setError('');setNotice('');try{return await fn();}catch(e){setError(e instanceof Error?e.message:'작업을 완료하지 못했습니다.');}finally{setWorking(false);}};
 const approve=()=>perform(async()=>{const approved=await action('mandates',{task_budget_minor:Math.round(Number(budget)*100),max_single_minor:Math.round(Number(cap)*100),expiry_minutes:30,task_requirements:{...source.requirements,max_delivery_seconds:Number(seconds)}});if(approved){setLocal(false);setSelectedId('');await action('research/purchases',{mandate_id:approved.mandate_id});}});
 const submit=()=>perform(async()=>{const delivery=source.rows.map((value:any,i:number)=>i===0?{...value,capex:Number(firstValue)}:value);await action(`deals/${row.deal.deal_id}/deliver`,{raw:JSON.stringify(delivery)});});
 const locked=row&&['ESCROW_FUNDED','DELIVERY_SUBMITTED','DELIVERY_VERIFIED'].includes(row.state),settled=row?.state==='SETTLED',refunded=row?.state==='REFUNDED',amount=row?.deal.price_minor??0;
 let delivered:any[]=[];try{const parsed=JSON.parse(row?.details.delivery??'[]');if(Array.isArray(parsed))delivered=parsed;}catch{}
 const stage=row?(settled||refunded?4:locked?3:2):1;
 return <section className="research-workbench">
  <div className={`rw-heading ${row?'rw-compact':''}`}><div><p className="eyebrow">원문으로 확인하는 데이터 납품</p><h1>약속한 결과가 와야<br/>{' '}<em>대금이 나갑니다.</em></h1><p>분기별 시설투자 수치 4개. 원문과 다른 납품은 지급하지 않고,<br className="desktop-break"/> 실패한 공급자는 다음 의뢰에서 샘플을 먼저 확인합니다.</p></div><span className="rw-mode">● {data.network==='local-devnet'?'로컬 체인':'Sepolia'} · 테스트 거래</span></div>
  <ol className="rw-steps" aria-label="의뢰 진행 단계">{['원문과 조건','견적 선택','납품 검수','지급 또는 환불'].map((text,i)=><li key={text} className={i+1===stage?'current':i+1<stage?'done':''} aria-current={i+1===stage?'step':undefined}><span>{i+1<stage?'✓':String(i+1).padStart(2,'0')}</span>{text}</li>)}</ol>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="rw-notice" role="status">{notice}</p>}
  <details className={`rw-config ${row?'':'rw-config-new'}`} open={!row}><summary>원문·승인 조건 보기 / 새 의뢰 설정</summary><div className="rw-setup"><article className="card rw-document"><p className="eyebrow">01 / 검수할 원문</p><h2>어느 자료의 수치인가요?</h2><label>승인된 문서<select value={documentId} disabled={pending} onChange={e=>{setDocumentId(e.target.value);setSelectedId('');setError('');setNotice('');}}>{catalog.map(d=><option value={d.id} key={d.id}>{d.label} · {d.year}년 수치 · {d.page}쪽</option>)}</select></label>
   {!source?<p role="status">원본 PDF와 지원하는 표 형식을 확인하고 있습니다…</p>:<><div className="rw-document-stamp"><span className={ready?'rw-ready':'rw-unsupported'}>{ready?'원본 확인 · 셀 검수 가능':'이 표 형식은 지원하지 않습니다'}</span><strong>{doc.company} · {doc.year}</strong><span>Investment in Facilities · Q1–Q4 · 십억 원</span><a href={doc.url+'#page='+doc.page} target="_blank" rel="noreferrer">공식 PDF {doc.page}쪽 열기 ↗</a></div>{!ready&&<p className="rw-warning" role="status">예치를 시작하지 않습니다. 다른 지원 문서를 선택하세요.<br/><code>{source.reason}</code></p>}<details><summary>원본 버전과 검수 범위</summary><p>파일 지문 <code>{doc.sha256}</code></p><p>페이지·연도·행·셀·부호·단위를 비교합니다. 회사 발표의 진실성을 인증하지 않으며, 사람의 원문 검토는 미완료입니다.</p></details></>}
  </article><article className="card rw-approval"><p className="eyebrow">02 / 사람이 정하는 한도</p><h2>조건을 승인하고 견적을 비교합니다.</h2><form onSubmit={e=>{e.preventDefault();void approve();}}><div className="rw-fields"><label>전체 예산<input type="number" min="0.01" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} required/></label><label>건별 최대액<input type="number" min="0.01" max={budget} step="0.01" value={cap} onChange={e=>setCap(e.target.value)} required/></label><label>최대 납품 시간 (초)<input type="number" min="1" max="3600" value={seconds} onChange={e=>setSeconds(e.target.value)} required/></label></div><p className="rw-terms">{doc?.year??'선택 연도'} Q1–Q4 · 원문에 대응하는 4행 · 가격과 조건 고정</p><button className="primary" disabled={pending||!ready||!data.kiln_configured}>{request?.status==='RUNNING'?'Qwen이 견적을 비교하고 있습니다…':'조건 승인 · Qwen으로 견적 비교'}</button></form><p className="muted">금액은 테스트 단위입니다. 실제 Kiln 비교 호출 1회가 발생하며, 예치는 다음 단계에서 별도로 실행합니다.</p>{!data.kiln_configured&&<p className="rw-warning">Kiln 연결 설정이 필요합니다. 원문 확인과 로컬 추출은 사용할 수 있습니다.</p>}</article></div>
  <div className="rw-baseline"><div><strong>{ready?'이 문서는 외주 없이도 추출할 수 있습니다.':'지원하는 문서는 외주 없이 추출할 수 있습니다.'}</strong><p>지원하는 표는 로컬 코드로 끝낼 수 있습니다. 아래 정산 흐름은 외주 검수의 기술 실험입니다.</p></div><button disabled={!ready||pending} onClick={()=>{setLocal(true);setNotice('로컬 추출 완료 · 모델 호출 0 · 결제 0. 기존 거래의 상태는 바뀌지 않습니다.');}}>로컬 추출 결과 보기</button></div>
  {local&&ready&&<SourceResult title="로컬 추출 결과" source={source} rows={source.rows} paid={false}/>}
  {ready&&<details className="card rw-offers"><summary>Qwen이 비교하는 견적 3개 · 실제 실적 / 전망치 / 납품 시간</summary><div className="three">{source.offers.map((offer:any)=><div key={offer.offer_id}><h3>{offer.offer_id}</h3><strong>{money(offer.price_minor)} → 최저 {money(offer.floor_price_minor)} 단위 · {offer.deadline}초</strong><p>{offer.description}</p></div>)}</div><p className="muted">공급자는 로컬 시뮬레이터입니다. 공개된 최저가 범위의 수락 규칙을 사용하며 실제 외부 공급자 협상을 주장하지 않습니다.</p></details>}
  </details>
  {request&&<details className="card rw-decision" open={request.status!=='READY'}><summary>Qwen 견적 선택 근거 · {request.selected_offer??request.status}</summary><p className="eyebrow">{data.model??'Kiln'} · 견적 판단</p><h2>{request.status==='RUNNING'?'승인 범위에 맞는 작업을 찾고 있습니다.':request.status==='READY'?'선택한 견적과 판단 근거':request.status==='REJECTED'?'적합한 견적을 선택하지 않았습니다.':'판단이 중단되었습니다.'}</h2><p>{request.decision?.args.reason??request.reason??'의미 비교 결과를 기다리는 중입니다.'}</p><small>상태 {request.status} · {request.selected_offer??'아직 선택하지 않음'}</small><p className="muted">모델 설명은 참고용입니다. 구매 금액은 테스트 단위이며, KRW는 납품 수치의 단위입니다. 모델 설명은 승인 금액·권한을 바꾸지 않습니다.</p></details>}
  <p className="rw-usage">이 작업공간의 Kiln 사용 · {data.efficiency.calls}회 · {data.efficiency.flows.some((f:any)=>f.missing_usage)?'토큰 집계 불완전':data.efficiency.flows.reduce((sum:number,f:any)=>sum+f.total_tokens,0).toLocaleString('ko-KR')+' 토큰'} · PDF 로컬 추출은 모델 호출 0회</p>
  {row&&<article className={`card rw-current ${settled?'rw-success':refunded?'rw-refund':''}`}><div className="section-heading"><div><p className="eyebrow">현재 의뢰 · {row.deal.deal_id.slice(0,8)} · {row.deal.seller_id}</p><h2 aria-live="polite">{labels[row.state]??row.state}</h2></div><span className="rw-order-price">{money(amount)}<small>테스트 단위</small></span></div>
   <div className="rw-money" aria-label="현재 자금 위치"><div className={refunded?'active':''}><span>구매자 회수</span><strong>{money(refunded?amount:0)}</strong></div><span aria-hidden="true">↔</span><div className={locked?'active':''}><span>에스크로 보관</span><strong>{money(locked?amount:0)}</strong></div><span aria-hidden="true">→</span><div className={settled?'active':''}><span>공급자 수령</span><strong>{money(settled?amount:0)}</strong></div></div>
   {locked&&<p className="rw-notice">판매자는 아직 돈을 받지 않았습니다. 납품 마감 {new Date(row.details.escrow.deadline*1000).toLocaleTimeString('ko-KR')} · 원문과 납품을 검수한 뒤 정산합니다.</p>}
   {row.state==='PREVIEW_REQUIRED'&&<div className="rw-warning"><strong>이 공급자의 이전 납품이 실패했습니다.</strong><p>다음 예치에는 한 행의 원문 대응 샘플이 필요합니다. 샘플 통과 뒤에도 최종 4행을 다시 검사합니다.</p></div>}
   <div className="intent-actions">{['DEAL_ACCEPTED','POLICY_APPROVED','PREVIEW_VERIFIED','PREVIEW_REQUIRED'].includes(row.state)&&<button className="primary" disabled={pending} onClick={()=>void perform(async()=>{const result=await action(`deals/${row.deal.deal_id}/fund`);if(result?.state==='PREVIEW_REQUIRED')setNotice('샘플이 없어 예치를 차단했습니다. 서명과 지급은 발생하지 않았습니다.');})}>{row.state==='PREVIEW_REQUIRED'?'샘플 없이 예치 시도':'승인 금액 예치하기'}</button>}{row.state==='PREVIEW_REQUIRED'&&ready&&<button disabled={pending} onClick={()=>void perform(()=>action(`deals/${row.deal.deal_id}/preview`,{raw:JSON.stringify(source.rows.slice(0,1))}))}>한 행 샘플 제출 · 검사</button>}{['REFUNDED','BLOCKED','EXPIRED','REJECTED'].includes(row.state)&&<button disabled={pending||mandate?.status==='REVOKED'} onClick={()=>void perform(async()=>{const retry=await action(`deals/${row.deal.deal_id}/repeat`);if(retry){setSelectedId(retry.deal.deal_id);setNotice('같은 승인 조건으로 재의뢰했습니다. 추가 모델 호출은 없습니다.');}})}>같은 공급자에게 재의뢰</button>}{mandate?.status==='ACTIVE'&&<button disabled={pending} onClick={()=>void perform(async()=>{const result=await action(`mandates/${mandate.mandate_id}/revoke`);if(result)setNotice('위임을 중지했습니다. 이미 예치된 금액은 별도로 정산 또는 만료 환불되며, 완료된 지급은 취소되지 않습니다.');})}>위임 중지</button>}</div>
   {row.state==='ESCROW_FUNDED'&&ready&&<div className="rw-delivery"><h3>직접 바꿔보는 납품 검수</h3><p>원문 셀은 {source.cells[0].text}, 양수 지출액은 {source.rows[0].capex.toLocaleString('ko-KR')}입니다. 아래 납품값만 바꾸면 나머지 3행과 공식 출처가 같아도 검수에 실패합니다.</p><label>첫 분기 납품값<input type="number" value={firstValue} onChange={e=>setFirstValue(e.target.value)} step="any"/></label><button className="primary" disabled={pending||!firstValue.trim()||!Number.isFinite(Number(firstValue))} onClick={()=>void submit()}>이 값으로 납품 검수 · 정산</button><p className="muted">이 조작은 명시적인 공격 실험입니다. 모델 오류로 집계하지 않습니다. 로컬 코드로 만든 납품이며 추출 모델 호출은 0입니다.</p></div>}
   {!!row.details.validation&&<p className="rw-validation">{row.details.validation.verified?'4개 값의 원문 대응 검수 통과':`검수 실패: ${row.details.validation.checks.filter((c:any)=>!c.pass).map((c:any)=>c.name==='SOURCE_CELL_VALUES'?'납품값과 원문값 불일치':c.name).join(' · ')}`}</p>}
   <div className="intent-actions"><button onClick={()=>openDeal(row.deal.deal_id)}>계약·기록 상세</button><button onClick={()=>openAudit(row.deal.deal_id)}>영수증 열기</button><button disabled={pending} onClick={()=>void perform(async()=>setVerification(await read(`audit/${row.deal.deal_id}/verify`)))}>저장 기록과 체인 대조</button><a href={`/api/audit/${row.deal.deal_id}`} download={`receipt-${row.deal.deal_id}.json`}>영수증 JSON ↓</a></div>{verification&&<p role="status" className={verification.verdict==='VALID'?'rw-notice':'rw-warning'}>{verification.verdict==='VALID'?'저장 기록과 체인 상태가 일치합니다.':verification.verdict} {verification.reason??''} · 검수 운영자에 대한 신뢰는 남습니다.</p>}
  </article>}
  {!!delivered.length&&ready&&<SourceResult title="실제 납품과 원문 비교" source={source} rows={delivered} paid={settled} download={`/api/deals/${row.deal.deal_id}/dataset`}/>}
  {!!rows.length&&<details className="card rw-history"><summary>이 문서의 거래 이력 · {rows.length}건</summary>{rows.map((r:any)=><button key={r.deal.deal_id} onClick={()=>{setSelectedId(r.deal.deal_id);setLocal(false);}}>{r.deal.deal_id.slice(0,8)} · {labels[r.state]??r.state} · {money(r.deal.price_minor)} 단위</button>)}</details>}
 </section>;
}
