import React,{useEffect,useState} from 'react';
const money=(n:number)=>(n/100).toFixed(2);
export function ReviewResearchWorkbench({data,action,openDeal,openAudit}:{data:any;action:(path:string,body?:unknown)=>Promise<any>;openDeal:(id:string)=>void;openAudit:(id:string)=>void}){
  const [info,setInfo]=useState<any>(null),[documentId,setDocumentId]=useState('lges-2026q2-pdf'),[extractionMode,setExtractionMode]=useState('deterministic'),[budget,setBudget]=useState('3.00'),[cap,setCap]=useState('2.00'),[seconds,setSeconds]=useState('180'),[working,setWorking]=useState(false),[error,setError]=useState('');
  const refresh=async()=>{const r=await fetch('/api/research'+(documentId?'?document_id='+encodeURIComponent(documentId):''));if(!r.ok)throw new Error('Research workspace unavailable');setInfo(await r.json());};
  useEffect(()=>{let active=true;const update=async()=>{try{const r=await fetch('/api/research'+(documentId?'?document_id='+encodeURIComponent(documentId):''));if(!r.ok)throw new Error('Research workspace unavailable');const next=await r.json();if(active){setInfo(next);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:String(e));}};void update();const timer=setInterval(()=>void update(),2000);return()=>{active=false;clearInterval(timer);};},[documentId]);
  if(!info)return <p role="status">{error||'Loading source-backed research task…'}</p>;
  const latest=info.requests[0],row=data.deals.find((r:any)=>r.deal.deal_id===latest?.deal_id);let rows:any[]=[];try{rows=JSON.parse(row?.details.delivery??'[]');}catch{}
  const ready=!info.selected_document||info.selected_document.status==='READY',page=info.reference.source.pdf_page,year=info.selected_document?.year??2025;
  const run=async()=>{setWorking(true);try{const mandate=await action('mandates',{task_budget_minor:Math.round(Number(budget)*100),max_single_minor:Math.round(Number(cap)*100),expiry_minutes:30,task_requirements:{...info.requirements,max_delivery_seconds:Number(seconds)}});if(mandate)await action('research/purchases',{mandate_id:mandate.mandate_id});await refresh();}finally{setWorking(false);}};
  return <section className="research-workbench">
    <div className="heading"><div><p className="eyebrow">REAL DOCUMENT · AGENT PROCUREMENT</p><h1>Buy research you can check.</h1><p className="sub">Get four quarterly investment figures, tied to their original report.<br/>Release payment after the agreed evidence passes.</p></div><a className="button" href="/?replay=1">Recorded walkthrough ↗</a></div>
    <div className="two"><article className="card"><p className="eyebrow">YOUR DELIVERABLE</p><h2>LG Energy Solution · {year} CAPEX</h2><label>Source report<select aria-label="Source report" value={documentId} onChange={e=>{setInfo(null);setDocumentId(e.target.value);}}><option value="">Earlier registered-reference demo</option>{info.documents.map((d:any)=><option key={d.id} value={d.id}>{d.id.replace('lges-','LGES ').replace('-pdf','').toUpperCase()} · {d.year} data {d.status!=='READY'?'· review required':' '}</option>)}</select></label><p>Four quarters of facility-investment cash outflows, in billion KRW. Each value includes its signed original, source page and document fingerprint.</p><a href={info.reference.source.url+'#page='+page} target="_blank" rel="noreferrer">Open issuer report · page {page} ↗</a><p className="muted">{info.mode==='pdf_cells'?'Each value is checked against its cited cell in the original PDF. No numeric answer table is registered. A one-quarter sample is required after a supplier failure; the full four quarters are still checked before payment.':'A fixed issuer-document comparison with registered reference values.'} Human review and measured time savings are pending.</p></article>
    <article className="card"><h2>Approve this purchase</h2>{!ready&&<p role="alert">This report needs manual review: {info.selected_document.reason}. Automatic purchase is unavailable for this table layout.</p>}<form onSubmit={e=>{e.preventDefault();void run();}}><div className="form-grid"><label>Task budget (test units)<input aria-label="Research task budget" type="number" min="0.01" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} required/></label><label>Maximum price<input aria-label="Research maximum price" type="number" min="0.01" step="0.01" value={cap} onChange={e=>setCap(e.target.value)} required/></label><label>Delivery window (seconds)<input aria-label="Research delivery window" type="number" min="1" max="3600" value={seconds} onChange={e=>setSeconds(e.target.value)} required/></label></div><p>Fixed quality: all 4 actual quarters, billion KRW, exact document/page/row. Seller descriptions cannot change this approval.</p><button className="primary" disabled={!ready||working||latest?.status==='RUNNING'}>{working?'Approving…':'Approve & compare offers'}</button></form><p className="muted">One real Kiln call reviews the promised work. Code ranks matching offers by their published minimum price and checks your limits. Funding is a separate action; all assets are test assets.</p></article></div>
    <article className="card"><h2>How to extract the agreed rows</h2><label>Extraction method<select aria-label="Extraction method" disabled={info.mode!=='pdf_cells'} value={info.mode==='pdf_cells'?extractionMode:'model'} onChange={e=>setExtractionMode(e.target.value)}><option value="deterministic">Direct PDF cells · no extraction model call</option><option value="model">AI extraction · one paid extraction call</option></select></label><p>The direct method handles supported tables using the same final checks. The buyer still uses AI to interpret offers. Unsupported layouts require review.</p></article><h2>Offers with different tradeoffs</h2><div className="three">{info.offers.map((offer:any)=><article className="card" key={offer.offer_id}><p className="eyebrow">{offer.seller_id} · {offer.offer_id}</p><h3>{money(offer.price_minor)} units · {offer.deadline}s</h3><p>{offer.description}</p><small>Posted minimum price: {money(offer.floor_price_minor)}. The local seller simulator accepts a counter within its published range.</small></article>)}</div>
    {latest&&<article className="card"><p className="eyebrow">BUYER DECISION · {latest.status}</p><h2>{latest.status==='RUNNING'?'Comparing the actual task with each offer…':latest.decision?.args.decision==='counter'?'A counteroffer within your approval':latest.status==='REJECTED'?'No suitable offer accepted':'Recorded purchase decision'}</h2><p>{latest.decision?.args.reason??latest.reason}</p>{latest.decision?.selection_source==='deterministic_ranking_after_ai_review'&&<details><summary>Why each offer matched or failed</summary>{latest.decision.evidence.map((review:any)=><p key={review.offer_id}><strong>{review.offer_id} · {review.fit}</strong><br/>“{review.quote}”<br/>{review.reason}</p>)}</details>}{latest.selected_offer&&<p>Selected: {latest.selected_offer} · agreed {row?money(row.deal.price_minor):'…'} units</p>}<div className="intent-actions">{row&&['DEAL_ACCEPTED','PREVIEW_VERIFIED','POLICY_APPROVED'].includes(row.state)&&<button className="primary" onClick={()=>void action(`deals/${row.deal.deal_id}/fund`)}>Lock approved amount</button>}{row?.state==='ESCROW_FUNDED'&&<button className="primary" disabled={working||row.details.extraction_started} onClick={async()=>{setWorking(true);try{await action(`research/deals/${row.deal.deal_id}/extract`,{mode:info.mode==='pdf_cells'?extractionMode:'model'});}finally{setWorking(false);}}}>{row.details.extraction_started?'Extracting source data…':'Extract report & validate delivery'}</button>}{row&&<button onClick={()=>openDeal(row.deal.deal_id)}>Inspect Deal</button>}{row&&<button onClick={()=>openAudit(row.deal.deal_id)}>Inspect receipt</button>}</div>{row&&<p className="research-outcome" role="status">{row.state==='SETTLED'?'Evidence matched. Seller paid.':row.state==='REFUNDED'?'Delivery or authority failed. Buyer refunded.':row.state==='ESCROW_FUNDED'?'Funds locked. Seller has not been paid.':row.state}</p>}{row?.details.extraction_error&&<p role="alert">{row.details.extraction_error} · Submit a corrected file from the Deal screen, or wait for the refund deadline.</p>}</article>}
    {!!rows.length&&<article className="card"><div className="section-heading"><div><p className="eyebrow">DELIVERED DATA · {row.details.validation?.verified?'SOURCE MATCH':'FAILED VALIDATION'}</p><h2>Quarterly facility investment</h2></div><a href={`/api/deals/${row.deal.deal_id}/dataset`}>Download JSON ↓</a></div><div className="table-wrap"><table><thead><tr><th>Quarter</th><th>Spend (bn KRW)</th><th>Original value</th><th>Evidence</th></tr></thead><tbody>{rows.map((r:any,i:number)=><tr key={i}><td>{r?.quarter??'Missing'}</td><td>{r?.capex??'Missing'}</td><td>{r?.source_value??'Missing'}</td><td><a href={info.reference.source.url+'#page='+page} target="_blank" rel="noreferrer">Report page {r?.source_page??'?'}</a></td></tr>)}</tbody></table></div><p className="muted">No investment recommendation. This is a procurement and source-extraction demonstration using issuer-reported cash-flow figures.</p></article>}
    <article className="card"><h2>Recent source-backed purchases</h2>{info.requests.length?info.requests.map((request:any)=><p key={request.mandate_id}>{request.mandate_id.slice(0,8)} · {request.status} · {request.selected_offer??request.reason??'Comparison in progress'} {request.deal_id&&<button onClick={()=>openDeal(request.deal_id)}>Open</button>}</p>):<p>Approve the first purchase to start.</p>}</article>
  </section>;
}
